// SPDX-License-Identifier: AGPL-3.0-or-later
/// E2d (#738) -- pinned masternode-set checkpoint + forward-replay bridge KAT.
///
/// THE GAP THIS CLOSES: E2c gave the payout-bearing DMN set exactly one
/// cold-start source, dashd RPC `protx list valid true`. With no RPC the arm
/// printed "seed UNAVAILABLE" and every template kept routing to the dashd
/// fallback -- the last structurally daemon-dependent input on the daemonless
/// path. mn_checkpoint.hpp + mn_checkpoint_lane.hpp replace the RPC with a
/// release-pinned anchor replayed forward through the existing block-connect
/// ingest.
///
/// The anchor is a TRUST ANCHOR (see mn_checkpoint.hpp and
/// src/impl/dash/coin/checkpoints/README.md). This suite pins the parts that
/// are NOT trusted -- every local check, and every way the load can refuse.
///
/// Pinned here, network-free, against REAL captured testnet data:
///   * the committed fixture (test/dash_mn_checkpoint_testnet_1519543.inc,
///     produced by tools/dash/gen_mn_checkpoint.py from a real
///     `protx list valid true 1519543`) parses, and the resulting MNStates are
///     FIELD-IDENTICAL to what the E2c RPC parser produces from the same
///     dashd JSON -- the checkpoint seed and the RPC seed are the same set;
///   * fail-closed on every defect class: unpinned, bad magic, unknown key,
///     network mismatch, count mismatch, DIGEST mismatch, duplicate proTxHash,
///     duplicate collateral, missing scriptPayout, negative/garbage numbers;
///   * the bridge replays the REAL accepted blocks 1519544..1519546 onto the
///     anchored set and publishes at the tip with dashd-exact lastPaidHeights;
///   * chain-position mismatch, staleness over the bridge bound, a replay gap
///     and a replay payee-desync each fail closed TERMINALLY (never publish);
///   * end-to-end: the bridge's publish flows through the REAL leg-4 event
///     (mn_list_update -> wire_mn_list_ingest -> on_mn_list_update) and, with
///     a live tip, flips populated() so select_work() takes the EMBEDDED arm;
///   * NEGATIVE CONTROL: the same end-to-end wiring with a corrupted anchor
///     leaves populated() FALSE and select_work() on the fallback.
///
/// #895 note: NOTHING in this file is #ifdef-guarded. Every TEST() below is
/// unconditionally compiled and registered, so a green tick here means the
/// bodies actually ran.

#include <gtest/gtest.h>

#include <impl/dash/coin/mn_checkpoint.hpp>       // parse_mn_checkpoint (DUT)
#include <impl/dash/coin/mn_checkpoint_lane.hpp>  // MnCheckpointLane (DUT)
#include <impl/dash/coin/vendor/providertx.hpp>   // CProUpServTx (revival leg)
#include <impl/dash/coin/vendor/simplifiedmns.hpp>// CSimplifiedMNList (attestation source)
#include <impl/dash/coin/mn_seed.hpp>             // parse_protx_list_seed (E2c cross-check)
#include <impl/dash/coin/node_interface.hpp>
#include <impl/dash/coin/mn_list_ingest.hpp>      // wire_mn_list_ingest (leg 4)
#include <impl/dash/coin/tip_ingest.hpp>          // wire_tip_ingest (leg 2)
#include <impl/dash/coin/coin_state_maintainer.hpp>
#include <impl/dash/coin/node_coin_state.hpp>

#include <core/hash.hpp>
#include <core/pack.hpp>
#include <core/uint256.hpp>

#include <nlohmann/json.hpp>

#include <algorithm>
#include <functional>
#include <map>
#include <span>
#include <optional>
#include <string>
#include <utility>
#include <vector>

using dash::coin::MNState;
using dash::coin::MnCheckpoint;
using dash::coin::MnCheckpointLane;
using dash::coin::mn_checkpoint_digest;
using dash::coin::parse_mn_checkpoint;

namespace {

constexpr uint8_t TESTNET_PUBKEY_VER = 140;
constexpr uint8_t TESTNET_P2SH_VER   = 19;

// ── The real captured anchor ───────────────────────────────────────────────
// Generated by tools/dash/gen_mn_checkpoint.py from dashd testnet
// `protx list valid true 1519543`. Same 6 masternodes the E2c suite's
// kProtxFront6At1519543 carries; blockhash is block 1519544's hashPrevBlock.
const char* const kRealCheckpoint1519543 =
#include "dash_mn_checkpoint_testnet_1519543.inc"
    ;

// Height + hash the anchor pins, restated so a fixture regeneration that
// silently moved either is caught here rather than in the bridge.
constexpr uint32_t kAnchorHeight = 1519543;
const char* const  kAnchorHash =
    "00000048ba417fd364d4220de99d16d6e17651a565b9b529417905b99b3a541b";

// Real accepted testnet blocks 1519544..1519546. Same bodies the E2c suite
// replays; kept here so this TU is self-contained (the two suites link into
// the same target, so a shared symbol would collide).
const char* const kBlockHex1519544 =
        "000000201b543a9bb905794129b5b965a55176e1d6169de90d22d464d37f41ba4800000095d95cbd42771d55f34c46009d29"
        "27f0684b22ca85667a2c0cb1626b0952138dfcc9606a4518511d0002780e0103000500010000000000000000000000000000"
        "000000000000000000000000000000000000ffffffff1303b82f170e2f5032506f6f6c2d74444153482fffffffff05056583"
        "03000000001976a9142629e1bbb4960da4c86226c876019e55c7c0346288ac2ed5fd0300000000016af80da7060000000019"
        "76a91464f2b2b84f62d68a2cd7f7f5fb2b5aa75ef716d788acb3e60800000000001976a91420cb5c22b1e4d5947e5c112c76"
        "96b51ad9af3c6188ac00000000000000002a6a282ad8f902c1ae2fece365590e4009eda31825336f273077a41697c43a54c0"
        "835f000000000000000000000000af0300b82f17007edd5fec21fd07f7b9d44b5029884ebc71d2e2812fd3029a76690045ce"
        "5c1647eb3ef20c2f89e9b8525f21e7064a47305b867ed642db1166faa9e0461fa0ee1d01b1a377ba4ad754bcc9bc00da609a"
        "d3482ad7acc7847039a0424300c35a2e99c4ea6f3659e987f86eb9559fb88a020bf404d9fe2c33e097e13647f55fbe0d6941"
        "e306f7bf206728634bff7e52a49d9e4b1b969017abd30c32ebc08d0c623cd98bb460a399f41e0000";

const char* const kBlockHex1519545 =
        "0000002013912532ebf7d4e655abf829f99d670de25fdb46d2cbcc6d567b6f294200000070151825df25a1f90162dfc2d978"
        "8b7dfdc8a690f9a61f0f8dd3f93e43bb5a2234ca606ac3fd4c1d00358c470103000500010000000000000000000000000000"
        "000000000000000000000000000000000000ffffffff1303b92f170e2f5032506f6f6c2d74444153482fffffffff050c6583"
        "03000000001976a9142629e1bbb4960da4c86226c876019e55c7c0346288ac2ed5fd0300000000016af80da7060000000019"
        "76a914c69a0bda7daaae481be8def95e5f347a1d00a4b488acace60800000000001976a91420cb5c22b1e4d5947e5c112c76"
        "96b51ad9af3c6188ac00000000000000002a6a2863ff5a8eb9b8e769435056d98f1831c46eaee642b6d17d0e9148d9b8385e"
        "434a000000000000000000000000af0300b92f17007edd5fec21fd07f7b9d44b5029884ebc71d2e2812fd3029a76690045ce"
        "5c1647eb3ef20c2f89e9b8525f21e7064a47305b867ed642db1166faa9e0461fa0ee1d0191d1a83a98f0b7b8cfb7f7ffca11"
        "6dd416960ec91ef8a0052ca0ac2ff7f0fcddf0c38f6894765f7ba11c6fa25385ca9d1498cd5d5581b9ca2603fd2d35a16dfe"
        "24cfd3dd49326da6d0d371cf3f97921c471ab5ad2eba487f680ced98063b26a9e235a19df41e0000";

const char* const kBlockHex1519546 =
        "00000020c9497b889ffb56364da48fd35c7673dc51df02c382bc2a3876b91e5138000000a2de65097455b4ae92412e868d9a"
        "c9d71c6f79322c1c10ddcab218e0bf004ff4e2ca606a76b04b1d000441980403000500010000000000000000000000000000"
        "000000000000000000000000000000000000ffffffff1303ba2f170e2f5032506f6f6c2d74444153482fffffffff05e16483"
        "03000000001976a9142629e1bbb4960da4c86226c876019e55c7c0346288ac2ed5fd0300000000016af80da7060000000019"
        "76a914c69a0bda7daaae481be8def95e5f347a1d00a4b488acd7e60800000000001976a91420cb5c22b1e4d5947e5c112c76"
        "96b51ad9af3c6188ac00000000000000002a6a2867e657696ff842bd354401663fb597a5edb52be7d029fdbdc710894c9776"
        "3512000000000000000000000000af0300ba2f17007edd5fec21fd07f7b9d44b5029884ebc71d2e2812fd3029a76690045ce"
        "5c1647eb3ef20c2f89e9b8525f21e7064a47305b867ed642db1166faa9e0461fa0ee1d01b836c031e91cc8b43129c7b1a93b"
        "2bf2e5ce31803a848318680d8144ba28379a8d769a313882306a5e3f4a10814466a511415c388a2ab98201c312e7ec291194"
        "31693053caad6df9d98a187588145cea3eb42b741eb3959abdf9138167fe993a100b9fa1f41e000003000600000000000000"
        "fd49010100ba2f170003000148f97725a2106d1fa6c4dc099de8acdc72b5b6b601751e65201adf9512000000320000000000"
        "0000320000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "000000000000000000000000000000000000000000000000000000000000000003000600000000000000fd55010100ba2f17"
        "0003000448f97725a2106d1fa6c4dc099de8acdc72b5b6b601751e65201adf95120000006400000000000000000000000000"
        "6400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "00000000000000000000000000000000000000000000000000000000000000000000000003000600000000000000fd430101"
        "00ba2f170003000648f97725a2106d1fa6c4dc099de8acdc72b5b6b601751e65201adf951200000019000000001900000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "00000000000000000000000000000000000000000000";

dash::coin::BlockType block_from_hex(const char* hex)
{
    std::string h(hex);
    std::vector<unsigned char> raw;
    raw.reserve(h.size() / 2);
    for (size_t i = 0; i + 1 < h.size(); i += 2)
        raw.push_back(static_cast<unsigned char>(
            std::stoul(h.substr(i, 2), nullptr, 16)));
    ::PackStream ps(raw);
    dash::coin::BlockType blk;
    ps >> blk;
    return blk;
}

// Re-digest a mutated payload so a test can isolate the field it is probing
// from the digest guard (otherwise EVERY mutation would merely prove the
// digest works).
std::string reseal(std::string payload)
{
    const size_t at = payload.find("digest ");
    if (at == std::string::npos) return payload;
    const size_t eol = payload.find('\n', at);
    std::string stripped = payload.substr(0, at) + payload.substr(eol + 1);
    const std::string d = mn_checkpoint_digest(stripped);
    return payload.substr(0, at) + "digest " + d + payload.substr(eol);
}

// Replace the first occurrence of `from` with `to`, then reseal.
std::string mutate(const std::string& payload, const std::string& from,
                   const std::string& to, bool reseal_it = true)
{
    std::string p = payload;
    const size_t at = p.find(from);
    EXPECT_NE(at, std::string::npos) << "mutation anchor not found: " << from;
    if (at == std::string::npos) return p;
    p.replace(at, from.size(), to);
    return reseal_it ? reseal(p) : p;
}

// ── A driveable harness around the lane ────────────────────────────────────
// Stands in for main_dash's seams: a synthetic header chain (height -> hash),
// a block store the request seam serves from, and a capture of what the lane
// publishes.
struct BridgeHarness {
    MnCheckpointLane lane;
    std::map<uint32_t, uint256>                    headers;   // height -> hash
    std::map<uint32_t, dash::coin::BlockType>      blocks;    // height -> body
    uint32_t tip{0};
    std::vector<uint32_t> requested;
    bool     published{false};
    uint32_t published_as_of{0};
    std::vector<std::pair<uint256, MNState>> published_set;
    // When set, request_block_fn delivers the block INLINE (the ordered-stream
    // behaviour of a real peer answering getdata on one TCP connection).
    bool auto_deliver{true};

    BridgeHarness()
    {
        lane.set_tip_height_fn([this] { return tip; });
        lane.set_header_hash_at_fn(
            [this](uint32_t h) -> std::optional<uint256> {
                auto it = headers.find(h);
                if (it == headers.end()) return std::nullopt;
                return it->second;
            });
        lane.set_publish_fn(
            [this](std::vector<std::pair<uint256, MNState>> set, uint32_t as_of) {
                published = true;
                published_as_of = as_of;
                published_set = std::move(set);
            });
        lane.set_request_block_fn([this](uint32_t h) {
            requested.push_back(h);
            if (!auto_deliver) return;
            auto it = blocks.find(h);
            if (it == blocks.end()) return;
            lane.on_block_connected(it->second, h);
        });
    }
};

MnCheckpoint good_checkpoint()
{
    auto cp = parse_mn_checkpoint(kRealCheckpoint1519543, "testnet");
    EXPECT_TRUE(cp.ok) << cp.error;
    return cp;
}

} // namespace

// ═══════════════════════════════════════════════════════════════════════════
// 1. The committed anchor parses, and says what it claims to say.
// ═══════════════════════════════════════════════════════════════════════════
TEST(DashMnCheckpoint, RealCapturedAnchorParses)
{
    auto cp = parse_mn_checkpoint(kRealCheckpoint1519543, "testnet");
    ASSERT_TRUE(cp.ok) << cp.error;
    EXPECT_FALSE(cp.unpinned);
    EXPECT_EQ(cp.network, "testnet");
    EXPECT_EQ(cp.height, kAnchorHeight);
    EXPECT_EQ(cp.blockhash.GetHex(), std::string(kAnchorHash));
    EXPECT_EQ(cp.entries.size(), 6u);
    EXPECT_FALSE(cp.source.empty()) << "provenance must be recorded in-file";
    EXPECT_FALSE(cp.generated.empty());
    // Every masternode carries a payee -- the whole point of the anchor.
    for (const auto& [h, mn] : cp.entries)
        EXPECT_FALSE(mn.scriptPayout.m_data.empty()) << h.GetHex();
}

// ═══════════════════════════════════════════════════════════════════════════
// 2. Checkpoint seed == RPC seed. The generator's field mapping is the same
//    mapping mn_seed.hpp makes from the same dashd JSON, so an operator who
//    switches between the two arms gets a byte-identical masternode set.
// ═══════════════════════════════════════════════════════════════════════════
TEST(DashMnCheckpoint, CheckpointSetIsFieldIdenticalToRpcSeed)
{
    // The SAME six masternodes as dashd reported them, reduced to the fields
    // the E2c parser consumes. (The full captured JSON lives in
    // test_dash_mn_seed.cpp; restating the payee-relevant subset here keeps the
    // two suites independent while still cross-checking the mapping.)
    const char* kJson = R"([
      {"type":"Regular","proTxHash":"dc2e02ac95ce4ccc9843c38de7bdaf32f2a1d5966c054127a3f4ca4f4bbd5991",
       "collateralHash":"4ee3ff5074723d995f4cb957a954587c6c637a42655ada8f4054037b28d1e7a8","collateralIndex":34,
       "operatorReward":0,"state":{"version":1,"registeredHeight":838365,"lastPaidHeight":1519459,
       "consecutivePayments":0,"PoSeRevivedHeight":1367840,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yVXDAM73Tg6A44Bm3qduXsMCYxzuqBCT48"}},
      {"type":"Evo","proTxHash":"9b653e767b978c10346d938c08dc8c5acd03c495f9d913e6fc652bfcae11a348",
       "collateralHash":"75fe9d8d90619576ef11deb8550d023366bf9d85e686dc6d5afba0aca8827e21","collateralIndex":2,
       "operatorReward":0,"state":{"version":2,"registeredHeight":1427623,"lastPaidHeight":1519460,
       "consecutivePayments":0,"PoSeRevivedHeight":1446613,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yeRZBWYfeNE4yVUHV4ZLs83Ppn9aMRH57A"}},
      {"type":"Evo","proTxHash":"91bbce94c34ebde0d099c0a2cb7635c0c31425ebabcec644f4f1a0854bfa605d",
       "collateralHash":"6ce8545e25d4f03aba1527062d9583ae01827c65b234bd979aca5954c6ae3a59","collateralIndex":30,
       "operatorReward":0,"state":{"version":2,"registeredHeight":850334,"lastPaidHeight":1519461,
       "consecutivePayments":0,"PoSeRevivedHeight":1368973,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yeRZBWYfeNE4yVUHV4ZLs83Ppn9aMRH57A"}},
      {"type":"Regular","proTxHash":"72ee70fa75262781a17d1eb69a6c3e97328208be98b59d5530164f31e481d3aa",
       "collateralHash":"4ee3ff5074723d995f4cb957a954587c6c637a42655ada8f4054037b28d1e7a8","collateralIndex":96,
       "operatorReward":0,"state":{"version":1,"registeredHeight":838365,"lastPaidHeight":1519462,
       "consecutivePayments":0,"PoSeRevivedHeight":1367330,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yVXDAM73Tg6A44Bm3qduXsMCYxzuqBCT48"}},
      {"type":"Regular","proTxHash":"c87218fb9d031f4926c22430c69b4edf1f0fb80c331c1a79e3b1b3873407c0ac",
       "collateralHash":"4ee3ff5074723d995f4cb957a954587c6c637a42655ada8f4054037b28d1e7a8","collateralIndex":62,
       "operatorReward":0,"state":{"version":1,"registeredHeight":838365,"lastPaidHeight":1519463,
       "consecutivePayments":0,"PoSeRevivedHeight":1367840,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yVXDAM73Tg6A44Bm3qduXsMCYxzuqBCT48"}},
      {"type":"Regular","proTxHash":"ecebeb952f56a61abaccd7bda7f4df5eccbd5f87a91bc4a8969535df1058158e",
       "collateralHash":"f329c4c9d194159e81597e50144ce41a40e2b40860c7813a85eabb0454700a3d","collateralIndex":1,
       "operatorReward":0,"state":{"version":2,"registeredHeight":1491043,"lastPaidHeight":1519464,
       "consecutivePayments":0,"PoSeRevivedHeight":1507780,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yjTpMw9buZfv4jNkf87AHpDj95YSAFuDiX"}}
    ])";

    dash::coin::MnSeedStats st;
    auto rpc_seed = dash::coin::parse_protx_list_seed(
        nlohmann::json::parse(kJson), TESTNET_PUBKEY_VER, TESTNET_P2SH_VER, &st);
    ASSERT_EQ(rpc_seed.size(), 6u);

    auto cp = good_checkpoint();
    ASSERT_EQ(cp.entries.size(), rpc_seed.size());

    std::map<uint256, MNState> from_ckpt(cp.entries.begin(), cp.entries.end());
    for (const auto& [h, rpc_mn] : rpc_seed) {
        auto it = from_ckpt.find(h);
        ASSERT_NE(it, from_ckpt.end())
            << "checkpoint is missing masternode " << h.GetHex();
        const MNState& ck = it->second;
        EXPECT_EQ(ck.scriptPayout.m_data, rpc_mn.scriptPayout.m_data)
            << "PAYEE MISMATCH for " << h.GetHex()
            << " -- the checkpoint would mint a different coinbase than the"
               " RPC seed";
        EXPECT_EQ(ck.nLastPaidHeight, rpc_mn.nLastPaidHeight);
        EXPECT_EQ(ck.nRegisteredHeight, rpc_mn.nRegisteredHeight);
        EXPECT_EQ(ck.nPoSeRevivedHeight, rpc_mn.nPoSeRevivedHeight);
        EXPECT_EQ(ck.nPoSeBanHeight, rpc_mn.nPoSeBanHeight);
        EXPECT_EQ(ck.nType, rpc_mn.nType);
        EXPECT_EQ(ck.nVersion, rpc_mn.nVersion);
        EXPECT_EQ(ck.isValid, rpc_mn.isValid);
        EXPECT_EQ(ck.collateralOutpoint.hash, rpc_mn.collateralOutpoint.hash);
        EXPECT_EQ(ck.collateralOutpoint.index, rpc_mn.collateralOutpoint.index);
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// 3. Fail-closed: every defect class refuses the WHOLE checkpoint.
// ═══════════════════════════════════════════════════════════════════════════
TEST(DashMnCheckpoint, UnpinnedPayloadIsReportedDistinctly)
{
    // What a fresh checkout ships: a comment-only .inc.
    auto cp = parse_mn_checkpoint("", "mainnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_TRUE(cp.unpinned) << "an absent anchor must not look like corruption";
    EXPECT_NE(cp.error.find("UNPINNED"), std::string::npos);

    auto cp2 = parse_mn_checkpoint("# nothing here\n\n# still nothing\n", "mainnet");
    EXPECT_FALSE(cp2.ok);
    EXPECT_TRUE(cp2.unpinned);
}

TEST(DashMnCheckpoint, DigestMismatchRefusesEverything)
{
    // Flip ONE masternode's lastPaidHeight without resealing: exactly the shape
    // of a hand edit or a half-applied merge.
    std::string tampered = mutate(kRealCheckpoint1519543,
                                  "1519459", "1519999", /*reseal_it=*/false);
    auto cp = parse_mn_checkpoint(tampered, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_FALSE(cp.unpinned);
    EXPECT_NE(cp.error.find("DIGEST MISMATCH"), std::string::npos) << cp.error;
    EXPECT_TRUE(cp.entries.empty()) << "no partial set may survive a refusal";
}

TEST(DashMnCheckpoint, NetworkMismatchRefuses)
{
    auto cp = parse_mn_checkpoint(kRealCheckpoint1519543, "mainnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("network mismatch"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, BadMagicRefuses)
{
    std::string p = mutate(kRealCheckpoint1519543,
                           "c2pool-dash-mn-checkpoint/1",
                           "c2pool-dash-mn-checkpoint/2");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("bad magic"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, UnknownKeyRefusesRatherThanIgnoring)
{
    // A future format could add a load-bearing key; silently skipping it would
    // load a set we do not actually understand.
    std::string p = mutate(kRealCheckpoint1519543,
                           "count 6", "quorumhint 42\ncount 6");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("unknown key"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, CountMismatchRefuses)
{
    std::string p = mutate(kRealCheckpoint1519543, "count 6", "count 5");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("count mismatch"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, MissingPayoutScriptRefuses)
{
    std::string p = mutate(
        kRealCheckpoint1519543,
        "76a91464f2b2b84f62d68a2cd7f7f5fb2b5aa75ef716d788ac", "-");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("scriptPayout"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, DuplicateProTxHashRefuses)
{
    // Duplicate the first mn line verbatim (and bump count so this test probes
    // the duplicate guard, not the count guard).
    std::string p(kRealCheckpoint1519543);
    const size_t at = p.find("mn 72ee70fa");
    ASSERT_NE(at, std::string::npos);
    const size_t eol = p.find('\n', at);
    const std::string line = p.substr(at, eol - at + 1);
    p.insert(eol + 1, line);
    p = mutate(p, "count 6", "count 7");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("duplicate proTxHash"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, NegativeAndGarbageNumbersRefuse)
{
    // strtoul would silently wrap "-1" to UINT32_MAX -- the exact sentinel bug
    // class that froze the projected payee. And "12abc" would parse as 12.
    for (const char* bad : {"-1", "12abc", "999999999999999999999", ""}) {
        std::string p = mutate(kRealCheckpoint1519543,
                               " 838365 1519462 ",
                               std::string(" ") + bad + " 1519462 ");
        auto cp = parse_mn_checkpoint(p, "testnet");
        EXPECT_FALSE(cp.ok) << "accepted registeredHeight '" << bad << "'";
        EXPECT_TRUE(cp.entries.empty());
    }
}

TEST(DashMnCheckpoint, ZeroBlockhashRefuses)
{
    std::string p = mutate(kRealCheckpoint1519543, kAnchorHash,
                           std::string(64, '0'));
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("all-zero"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, DigestRuleIgnoresCommentsAndBlankLines)
{
    // Comments must be free to add (the .inc header block is comments), so the
    // digest domain must exclude them -- but must NOT exclude anything else.
    std::string p = std::string("# a comment\n\n")
                  + kRealCheckpoint1519543 + "\n# trailing comment\n";
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_TRUE(cp.ok) << cp.error;
    EXPECT_EQ(cp.entries.size(), 6u);
}

// ═══════════════════════════════════════════════════════════════════════════
// 4. The bridge: real anchor + real blocks -> published set.
// ═══════════════════════════════════════════════════════════════════════════
TEST(DashMnCheckpointBridge, ReplaysRealBlocksAndPublishesAtTip)
{
    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.blocks[1519544] = block_from_hex(kBlockHex1519544);
    h.blocks[1519545] = block_from_hex(kBlockHex1519545);
    h.blocks[1519546] = block_from_hex(kBlockHex1519546);
    h.tip = 1519546;

    h.lane.arm(good_checkpoint());
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Waiting);

    h.lane.pump();

    ASSERT_TRUE(h.published) << "bridge status: " << h.lane.status();
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Published);
    EXPECT_EQ(h.published_as_of, 1519546u)
        << "the published snapshot must be labelled with the height it bridged"
           " to, or the maintainer's apply cursor starts wrong";
    EXPECT_EQ(h.published_set.size(), 6u);

    // dashd's actual payment schedule over those three blocks (the same
    // attribution the E2c suite pins against the RPC seed).
    std::map<uint256, MNState> out(h.published_set.begin(), h.published_set.end());
    EXPECT_EQ(out.at(uint256S("dc2e02ac95ce4ccc9843c38de7bdaf32f2a1d5966c05412"
                              "7a3f4ca4f4bbd5991")).nLastPaidHeight, 1519544u);
    EXPECT_EQ(out.at(uint256S("9b653e767b978c10346d938c08dc8c5acd03c495f9d913e"
                              "6fc652bfcae11a348")).nLastPaidHeight, 1519545u);
    EXPECT_EQ(out.at(uint256S("91bbce94c34ebde0d099c0a2cb7635c0c31425ebabcec64"
                              "4f4f1a0854bfa605d")).nLastPaidHeight, 1519546u);

    // The blocks were requested in ascending order from the cursor.
    ASSERT_FALSE(h.requested.empty());
    EXPECT_EQ(h.requested.front(), 1519544u);
    EXPECT_TRUE(std::is_sorted(h.requested.begin(), h.requested.end()));
}

TEST(DashMnCheckpointBridge, IgnoresLiveTipBlocksArrivingMidBridge)
{
    // The cold-start race: the new_block inv leg delivers a block at the CURRENT
    // tip while the bridge is still replaying history. Folding it would advance
    // a stale cursor -- the E4-soak bad-cb-payee shape.
    BridgeHarness h;
    h.auto_deliver = false;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.tip = 1519546;
    h.lane.arm(good_checkpoint());
    h.lane.pump();
    ASSERT_EQ(h.lane.state(), MnCheckpointLane::State::Bridging);

    // A far-future block arrives first. It must be ignored, NOT folded.
    h.lane.on_block_connected(block_from_hex(kBlockHex1519546), 1519546);
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Bridging)
        << "an out-of-order live block must not fail or advance the bridge";
    EXPECT_EQ(h.lane.cursor_height(), kAnchorHeight);
    EXPECT_FALSE(h.published);

    // Now the ordered replay proceeds normally.
    h.lane.on_block_connected(block_from_hex(kBlockHex1519544), 1519544);
    h.lane.on_block_connected(block_from_hex(kBlockHex1519545), 1519545);
    h.lane.on_block_connected(block_from_hex(kBlockHex1519546), 1519546);
    EXPECT_TRUE(h.published) << h.lane.status();
    EXPECT_EQ(h.published_as_of, 1519546u);
}

TEST(DashMnCheckpointBridge, ChainPositionMismatchFailsClosed)
{
    // The anchor names a block our PoW-validated header chain does not hold at
    // that height: wrong chain, wrong fork, or a fabricated anchor.
    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(
        "00000000000000000000000000000000000000000000000000000000deadbeef");
    h.tip = 1519546;
    h.lane.arm(good_checkpoint());
    h.lane.pump();

    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed);
    EXPECT_NE(h.lane.status().find("CHAIN-POSITION MISMATCH"), std::string::npos)
        << h.lane.status();
    EXPECT_FALSE(h.published);
    // Terminal: further drives must not resurrect it.
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.lane.pump();
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed);
    EXPECT_FALSE(h.published);
}

TEST(DashMnCheckpointBridge, StaleAnchorBeyondBridgeBoundFailsClosed)
{
    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.tip = kAnchorHeight + 5000;
    h.lane.set_max_bridge_blocks(100);
    h.lane.arm(good_checkpoint());
    h.lane.pump();

    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed);
    EXPECT_NE(h.lane.status().find("STALE"), std::string::npos) << h.lane.status();
    EXPECT_FALSE(h.published);
    EXPECT_TRUE(h.requested.empty())
        << "a refused anchor must not start pulling block bodies";
}

TEST(DashMnCheckpointBridge, ReplayGapFailsClosed)
{
    // Blocks skipped mid-replay: dashd advanced its payment queue at heights we
    // never folded, so ours is silently behind. Never publish.
    BridgeHarness h;
    h.auto_deliver = false;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.tip = 1519546;
    h.lane.arm(good_checkpoint());
    h.lane.pump();
    ASSERT_EQ(h.lane.state(), MnCheckpointLane::State::Bridging);

    h.lane.on_block_connected(block_from_hex(kBlockHex1519544), 1519544);
    EXPECT_EQ(h.lane.cursor_height(), 1519544u);
    // 1519545 never arrives; the lane is waiting for it, so 1519546 is simply
    // ignored and the bridge NEVER publishes.
    h.lane.on_block_connected(block_from_hex(kBlockHex1519546), 1519546);
    EXPECT_FALSE(h.published);
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Bridging);
    EXPECT_EQ(h.lane.cursor_height(), 1519544u);
}

TEST(DashMnCheckpointBridge, PayeeDesyncOnWrongAnchorFailsClosed)
{
    // THE anchor falsification test. Corrupt the anchor so it projects the
    // wrong payee, then replay a real block. The block's real coinbase does not
    // pay what we project -> the anchor is proven wrong -> terminal refusal.
    // This is what stops a bad trust anchor from ever reaching a template.
    //
    // 1519459 is dc2e02ac's lastPaidHeight, the LOWEST in the set, which is why
    // dashd paid it at 1519544. Pushing it to the top of the queue makes some
    // OTHER masternode our projected payee.
    std::string p = mutate(kRealCheckpoint1519543, " 838365 1519459 ",
                           " 838365 1519543 ");
    auto bad = parse_mn_checkpoint(p, "testnet");
    ASSERT_TRUE(bad.ok) << bad.error;  // structurally valid, semantically wrong

    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.blocks[1519544] = block_from_hex(kBlockHex1519544);
    h.tip = 1519544;
    h.lane.arm(bad);
    h.lane.pump();

    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << h.lane.status();
    EXPECT_NE(h.lane.status().find("PAYEE DESYNC"), std::string::npos)
        << h.lane.status();
    EXPECT_FALSE(h.published)
        << "a falsified anchor must NEVER reach the maintainer";
}

TEST(DashMnCheckpointBridge, RefusedCheckpointArmsTerminallyFailedClosed)
{
    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.tip = 1519546;
    h.lane.arm(parse_mn_checkpoint("", "mainnet"));   // UNPINNED
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed);
    h.lane.pump();
    EXPECT_FALSE(h.published);
    EXPECT_TRUE(h.requested.empty());
}

TEST(DashMnCheckpointBridge, WaitsQuietlyUntilHeadersReachTheAnchor)
{
    // Cold start: headers are still syncing. Not an error, and MUST NOT publish.
    BridgeHarness h;
    h.tip = 1000;
    h.lane.arm(good_checkpoint());
    h.lane.pump();
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Waiting);
    EXPECT_FALSE(h.published);
    EXPECT_TRUE(h.requested.empty());
}

// ═══════════════════════════════════════════════════════════════════════════
// 5. End-to-end through the REAL leg-4 event, plus the negative control.
// ═══════════════════════════════════════════════════════════════════════════
namespace {

// Mirrors main_dash's wiring: the lane publishes into Node::mn_list_update,
// leg 4 carries it to the maintainer, leg 2 supplies the tip.
struct E2eRig {
    dash::interfaces::Node                        node;
    dash::coin::NodeCoinState                     state;
    dash::coin::CoinStateMaintainer               maint{state};
    std::vector<std::shared_ptr<EventDisposable>> subs;
    BridgeHarness                                 h;

    E2eRig()
    {
        // The anti-mint latch main_dash enables for the embedded arm.
        maint.set_require_seeded_mn_set(true);
        subs.push_back(c2pool::dash::wire_mn_list_ingest(node, maint));
        subs.push_back(c2pool::dash::wire_tip_ingest(node, maint));
        h.lane.set_publish_fn(
            [this](std::vector<std::pair<uint256, MNState>> set, uint32_t as_of) {
                dash::interfaces::MnListUpdate up;
                up.mnstates     = std::move(set);
                up.as_of_height = as_of;
                node.mn_list_update.happened(up);
            });
        h.headers[kAnchorHeight] = uint256S(kAnchorHash);
        h.blocks[1519544] = block_from_hex(kBlockHex1519544);
        h.blocks[1519545] = block_from_hex(kBlockHex1519545);
        h.blocks[1519546] = block_from_hex(kBlockHex1519546);
        h.tip = 1519546;
    }

    void fire_tip()
    {
        dash::interfaces::TipAdvance ta;
        ta.prev_height           = 1519546;
        ta.prev_hash             = uint256S(kAnchorHash);
        ta.bits_for_next         = 0x1d00ffff;
        ta.mtp_at_tip            = 1751000000;
        ta.address_version       = TESTNET_PUBKEY_VER;
        ta.address_p2sh_version  = TESTNET_P2SH_VER;
        node.new_tip.happened(ta);
    }
};

} // namespace

TEST(DashMnCheckpointE2e, BridgePublishFlipsPopulatedThroughTheRealLeg4Event)
{
    E2eRig r;
    EXPECT_FALSE(r.state.populated()) << "cold start must not be populated";

    r.h.lane.arm(good_checkpoint());
    r.h.lane.pump();
    ASSERT_EQ(r.h.lane.state(), MnCheckpointLane::State::Published)
        << r.h.lane.status();

    r.fire_tip();

    EXPECT_TRUE(r.state.populated())
        << "the bridged masternode set + a live tip must flip the embedded arm";
}

// NEGATIVE CONTROL. Identical wiring; the ONLY difference is a corrupted
// anchor. If this ever passes populated()==true, the fail-closed path is
// decorative.
TEST(DashMnCheckpointE2e, NegativeControlCorruptAnchorLeavesArmUnpopulated)
{
    E2eRig r;
    std::string tampered = mutate(kRealCheckpoint1519543,
                                  "1519459", "1519999", /*reseal_it=*/false);
    auto bad = parse_mn_checkpoint(tampered, "testnet");
    ASSERT_FALSE(bad.ok);

    r.h.lane.arm(bad);
    r.h.lane.pump();
    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed);

    r.fire_tip();

    EXPECT_FALSE(r.state.populated())
        << "a refused anchor must leave the embedded arm unarmed -- templates"
           " keep routing to the dashd fallback";
}

// Second negative control, one layer down: prove the anti-mint latch main_dash
// enables actually blocks the "one accidental ProRegTx arms the queue" path.
TEST(DashMnCheckpointE2e, NegativeControlAntiMintLatchBlocksUnseededArming)
{
    dash::coin::NodeCoinState state;
    dash::coin::CoinStateMaintainer maint{state};
    maint.set_require_seeded_mn_set(true);

    // A non-empty masternode set with NO height stamp: what an unauthoritative
    // source (or a block-connect registration) would produce.
    auto cp = good_checkpoint();
    maint.on_mn_list_update(cp.entries, /*as_of_height=*/0);

    auto fire_tip = [&maint] {
        maint.on_new_tip(/*prev_height=*/1519546, uint256S(kAnchorHash),
                         /*bits_for_next=*/0x1d00ffff,
                         /*mtp_at_tip=*/1751000000,
                         TESTNET_PUBKEY_VER, TESTNET_P2SH_VER);
    };
    fire_tip();

    EXPECT_FALSE(state.populated())
        << "an unheighted masternode set must never arm the embedded arm";

    // Positive control on the same object: the SAME set WITH its height arms it.
    maint.on_mn_list_update(cp.entries, kAnchorHeight);
    fire_tip();
    EXPECT_TRUE(state.populated())
        << "a height-stamped authoritative snapshot must still arm normally";
}

// ═══════════════════════════════════════════════════════════════════════════
// 6. POST-ANCHOR PoSe BANS — the SML-attested recovery walk.
//
// A PoSe ban is applied by dashd from CONSENSUS (accumulated
// MAX_PoSe_PENALTY); it never appears as a special transaction in any block.
// MnStateMachine::apply_block walks special txs, so it is STRUCTURALLY unable
// to observe one. A masternode banned after the anchor height therefore stays
// isValid=true through the whole replay, holds the head of our payment queue,
// and is projected as the payee for a block dashd paid to somebody else. The
// bridge cross-check fires, and here that is TERMINAL — so ONE post-anchor ban
// anywhere in the window means the daemonless arm never publishes a masternode
// set at all, and every template keeps routing to dashd.
//
// The SML is the only carrier of that ban. These cases drive the recovery
// through the PRODUCTION SEAMS ONLY: a real MnCheckpointLane, armed with the
// real fixture checkpoint, all four existing seams wired plus a
// fixture-SML-backed validity fn built the same way main_dash builds it, then
// pump()/on_block_connected() with blocks whose non-payee bytes are the REAL
// accepted testnet blocks. The lane was missed by the original suite precisely
// because nothing entered it this way.
// ═══════════════════════════════════════════════════════════════════════════
namespace {

using dash::coin::MutableTransaction;
using dash::coin::vendor::CProUpServTx;
using dash::coin::vendor::CSimplifiedMNList;
using dash::coin::vendor::CSimplifiedMNListEntry;

// The six anchored masternodes in DIP-3 queue order at h=1519543 (ascending
// nLastPaidHeight 1519459..1519464, which is the CompareByLastPaid key for all
// six). The payout-address groups matter: Q1/Q4/Q5 share yVXDA…, Q2/Q3 share
// yeRZB…, Q6 is alone on yjTpMw… — which is why a demotion from Q1 lands on Q2
// (different script, cross-checkable) and why reaching Q6 costs five.
const char* const kQ1 = "dc2e02ac95ce4ccc9843c38de7bdaf32f2a1d5966c054127a3f4ca4f4bbd5991";
const char* const kQ2 = "9b653e767b978c10346d938c08dc8c5acd03c495f9d913e6fc652bfcae11a348";
const char* const kQ3 = "91bbce94c34ebde0d099c0a2cb7635c0c31425ebabcec644f4f1a0854bfa605d";
const char* const kQ4 = "72ee70fa75262781a17d1eb69a6c3e97328208be98b59d5530164f31e481d3aa";
const char* const kQ5 = "c87218fb9d031f4926c22430c69b4edf1f0fb80c331c1a79e3b1b3873407c0ac";
const char* const kQ6 = "ecebeb952f56a61abaccd7bda7f4df5eccbd5f87a91bc4a8969535df1058158e";

// Take the payout script from the ANCHOR rather than hardcoding hex, so a
// fixture regeneration cannot leave these tests quietly probing a script no
// masternode owns any more.
std::vector<unsigned char> payout_of(const MnCheckpoint& cp, const char* protx)
{
    const uint256 want = uint256S(protx);
    for (const auto& [h, st] : cp.entries)
        if (h == want) return st.scriptPayout.m_data;
    ADD_FAILURE() << "the anchor carries no masternode " << protx;
    return {};
}

// Rewrite the coinbase output paying `from` so it pays `to`. This synthesises
// "dashd skipped our projected payee and paid a later queue slot" on top of a
// REAL accepted block: every byte except that one output script — header,
// CbTx payload, the rest of the outputs — stays exactly as the network
// produced it.
dash::coin::BlockType repay_coinbase(dash::coin::BlockType blk,
                                     const std::vector<unsigned char>& from,
                                     const std::vector<unsigned char>& to)
{
    EXPECT_FALSE(blk.m_txs.empty());
    bool hit = false;
    for (auto& o : blk.m_txs[0].vout) {
        if (o.scriptPubKey.m_data == from) {
            o.scriptPubKey.m_data = to;
            hit = true;
        }
    }
    EXPECT_TRUE(hit) << "template block does not pay the script being replaced";
    return blk;
}

// A fixture SML plus the EXACT lambda shape main_dash wires around
// NodeCoinState::sml(): linear scan, three-state, std::nullopt when the
// masternode is absent. Captured BY VALUE so the hook cannot outlive its data.
MnCheckpointLane::SmlValidityFn sml_fn(
    const std::vector<std::pair<const char*, bool>>& entries)
{
    std::vector<CSimplifiedMNListEntry> v;
    v.reserve(entries.size());
    for (const auto& [hex, valid] : entries) {
        CSimplifiedMNListEntry e;
        e.proRegTxHash = uint256S(hex);
        e.isValid      = valid;
        v.push_back(e);
    }
    CSimplifiedMNList sml(std::move(v));
    return [sml](const uint256& h) -> std::optional<bool> {
        for (const auto& e : sml.mnList)
            if (e.proRegTxHash == h) return e.isValid;
        return std::nullopt;
    };
}

// Every masternode attested VALID except the listed ones.
std::vector<std::pair<const char*, bool>> all_valid_except(
    std::initializer_list<const char*> banned)
{
    std::vector<std::pair<const char*, bool>> out;
    for (const char* q : {kQ1, kQ2, kQ3, kQ4, kQ5, kQ6}) {
        bool is_banned = false;
        for (const char* b : banned) if (std::string(b) == q) is_banned = true;
        out.emplace_back(q, !is_banned);
    }
    return out;
}

// A one-block bridge over the real anchor: arm, then let pump() pull and fold
// the single block through the real request/deliver path.
struct RecoveryRig {
    MnCheckpoint  cp{good_checkpoint()};
    BridgeHarness h;

    void run(const dash::coin::BlockType& blk, uint32_t tip = 1519544)
    {
        h.headers[kAnchorHeight] = uint256S(kAnchorHash);
        h.blocks[1519544] = blk;
        h.tip = tip;
        h.lane.arm(cp);
        h.lane.pump();
    }
};

std::vector<unsigned char> protx_payload_bytes(const CProUpServTx& p)
{
    auto ps = ::pack(p);
    auto sp = ps.get_span();
    return std::vector<unsigned char>(
        reinterpret_cast<const unsigned char*>(sp.data()),
        reinterpret_cast<const unsigned char*>(sp.data()) + sp.size());
}

// A ProUpServTx reviving `protx`. dashcore's revival branch — which
// MnStateMachine mirrors — is gated on nPoSeBanHeight != 0, so this tx is a
// NO-OP unless something recorded a ban height for that masternode first.
MutableTransaction pro_up_serv_tx(const char* protx)
{
    CProUpServTx p;
    p.nVersion  = dash::coin::vendor::ProTxVersion::BASIC_BLS;
    p.nType     = dash::coin::vendor::MnType::REGULAR;
    p.proTxHash = uint256S(protx);
    p.netInfo.port_be = 0x2334;

    MutableTransaction tx;
    tx.type          = CProUpServTx::SPECIALTX_TYPE;
    tx.extra_payload = protx_payload_bytes(p);
    bitcoin_family::coin::TxIn in;
    in.prevout.hash  = uint256{};
    in.prevout.index = 0xFFFFFFFF;
    in.sequence      = 0xFFFFFFFF;
    tx.vin.push_back(in);
    return tx;
}

uint256 synth_tx_hash(const MutableTransaction& tx)
{
    ::PackStream s;
    s << tx;
    auto sp = s.get_span();
    uint256 h;
    CHash256()
        .Write(std::span<const unsigned char>(
            reinterpret_cast<const unsigned char*>(sp.data()), sp.size()))
        .Finalize(std::span<unsigned char>(h.data(), 32));
    return h;
}

// A ProRegTx registering a brand-new masternode with `payout` as its
// scriptPayout. Its proTxHash is the tx hash (synth_tx_hash).
MutableTransaction pro_reg_tx(const std::vector<unsigned char>& payout,
                              uint32_t nonce)
{
    dash::coin::vendor::CProRegTx p;
    p.nVersion = dash::coin::vendor::ProTxVersion::BASIC_BLS;
    p.nType    = dash::coin::vendor::MnType::REGULAR;
    p.collateralOutpoint.hash  = uint256{};
    p.collateralOutpoint.index = nonce;
    p.netInfo.port_be          = 0x2334;
    p.scriptPayout.m_data      = payout;

    MutableTransaction tx;
    tx.type = dash::coin::vendor::CProRegTx::SPECIALTX_TYPE;
    {
        auto ps = ::pack(p);
        auto sp = ps.get_span();
        tx.extra_payload.assign(
            reinterpret_cast<const unsigned char*>(sp.data()),
            reinterpret_cast<const unsigned char*>(sp.data()) + sp.size());
    }
    bitcoin_family::coin::TxIn in;
    in.prevout.hash  = uint256{};
    in.prevout.index = 0xFFFF0000u | nonce;
    in.sequence      = 0xFFFFFFFF;
    tx.vin.push_back(in);
    return tx;
}

// A distinctive P2PKH-shaped script no fixture masternode owns.
std::vector<unsigned char> synth_script(uint8_t tag)
{
    std::vector<unsigned char> s{0x76, 0xa9, 0x14};
    for (int i = 0; i < 20; ++i) s.push_back(static_cast<unsigned char>(tag));
    s.push_back(0x88);
    s.push_back(0xac);
    return s;
}

} // namespace

// CASE 1. The bug this whole change exists for. dashd banned our queue head
// after the anchor was cut, so the block pays queue slot 2. Today that is a
// terminal payee_desync and the arm never arms. With the SML attesting the
// ban, the bridge COMPLETES — and the published set carries the exclusion
// permanently, because a one-shot skip would desync again at that masternode's
// next queue turn (~|set| blocks later).
TEST(DashMnCheckpointSmlRecovery, PostAnchorBanAttestedBySmlCompletesTheBridge)
{
    RecoveryRig r;
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({kQ1})));
    r.run(blk);

    ASSERT_TRUE(r.h.published) << "lane status: " << r.h.lane.status();
    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::Published);
    EXPECT_EQ(r.h.lane.sml_recovered(), 1u);
    EXPECT_NE(r.h.lane.status().find("1 SML-recovered exclusions"),
              std::string::npos)
        << "the recovery count must be on the published status, not only in"
           " scrollback: " << r.h.lane.status();

    std::map<uint256, MNState> out(r.h.published_set.begin(),
                                   r.h.published_set.end());
    const MNState& demoted = out.at(uint256S(kQ1));
    EXPECT_FALSE(demoted.isValid) << "the exclusion must be PERMANENT";
    EXPECT_EQ(demoted.nPoSeBanHeight, 1519544u)
        << "a nonzero ban height is what makes the ProUpServTx revival gate"
           " functional for this masternode";
    EXPECT_EQ(demoted.nLastPaidHeight, 1519459u)
        << "the demoted masternode must NOT be credited with the payment";
    EXPECT_EQ(out.at(uint256S(kQ2)).nLastPaidHeight, 1519544u)
        << "the accepted candidate is the one whose script the coinbase pays";
}

// CASE 2. Same desync, but the SML says the projected payee is LIVE. Then the
// mismatch is a real desync (bad anchor, missed block, corrupt seed) and the
// only correct answer is the old one. Attested-valid is COUNTER-evidence, and
// this is the case that stops the walk from excusing anything it likes.
TEST(DashMnCheckpointSmlRecovery, SmlAttestingProjectedPayeeValidStillFailsClosed)
{
    RecoveryRig r;
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({})));
    r.run(blk);

    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << r.h.lane.status();
    EXPECT_NE(r.h.lane.status().find("PAYEE DESYNC"), std::string::npos)
        << r.h.lane.status();
    EXPECT_FALSE(r.h.published);
    EXPECT_EQ(r.h.lane.sml_recovered(), 0u);
}

// CASE 3. No hook at all — the pre-change wiring. Behaviour must be exactly
// what it was: terminal.
TEST(DashMnCheckpointSmlRecovery, NoSmlSeamWiredKeepsTheTerminalFailClosed)
{
    RecoveryRig r;
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    r.run(blk);   // deliberately no set_sml_validity_fn

    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << r.h.lane.status();
    EXPECT_FALSE(r.h.published);
    EXPECT_EQ(r.h.lane.sml_recovered(), 0u);
    EXPECT_NE(r.h.lane.status().find("no SML validity seam is wired"),
              std::string::npos)
        << "the operator must be told WHICH input was missing: "
        << r.h.lane.status();
}

// CASE 3b. A hook that has no opinion. Absent-from-SML is not evidence of a
// ban; collapsing nullopt into "banned" would turn every SML gap into a
// licence to re-attribute payments.
TEST(DashMnCheckpointSmlRecovery, SmlWithoutTheMasternodeIsNotEvidence)
{
    RecoveryRig r;
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    // An SML that carries only OTHER masternodes: the projected payee is
    // simply absent, so the hook answers std::nullopt for it.
    r.h.lane.set_sml_validity_fn(sml_fn({{kQ3, true}, {kQ4, true}}));
    r.run(blk);

    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << r.h.lane.status();
    EXPECT_FALSE(r.h.published);
    EXPECT_EQ(r.h.lane.sml_recovered(), 0u);
}

// CASE 4. The demotion is licensed, but the re-projection ALSO does not match
// the coinbase, and the next candidate down is attested live. Acceptance
// requires an EXACT coinbase script match at some licensed step; there is
// none, so nothing is attributed and nothing is excluded.
TEST(DashMnCheckpointSmlRecovery, ReProjectionThatAlsoMismatchesFailsClosed)
{
    RecoveryRig r;
    // Pay Q6's script. Q2 (the first demotion target) is on a different
    // script, so the walk stalls immediately after one licensed demotion.
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ6));
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({kQ1})));
    r.run(blk);

    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << r.h.lane.status();
    EXPECT_NE(r.h.lane.status().find("PAYEE DESYNC"), std::string::npos)
        << r.h.lane.status();
    EXPECT_FALSE(r.h.published);
    EXPECT_EQ(r.h.lane.sml_recovered(), 0u)
        << "a refused walk must not leave a partial exclusion behind";
}

// CASE 5. The budget. The lane sizes it at 4 + replay_distance/1000, so a
// one-block bridge allows 4. Reaching Q6 costs FIVE demotions (Q1..Q5), and
// every one of them is attested — the walk would otherwise succeed. Past the
// cap this stops being a repair of a few known-banned nodes and becomes a
// wholesale override of the projection, so it fails closed instead.
TEST(DashMnCheckpointSmlRecovery, ExclusionsPastThePerBridgeCapFailClosed)
{
    RecoveryRig r;
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ6));
    r.h.lane.set_sml_validity_fn(
        sml_fn(all_valid_except({kQ1, kQ2, kQ3, kQ4, kQ5})));
    r.run(blk);

    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << r.h.lane.status();
    EXPECT_FALSE(r.h.published);
    EXPECT_EQ(r.h.lane.sml_recovered(), 0u);
}

// CASE 6. The permanence pays off. The excluded masternode is later revived by
// a real ProUpServTx inside the same replay window. dashcore's revival branch
// is gated on nPoSeBanHeight != 0 — so it fires ONLY because the recovery
// recorded a ban height. Without that (the one-shot-skip design), this
// masternode's revivedHeight would stay at its stale anchor value of 1367840
// and it would sit at the wrong queue position for the rest of the bridge.
TEST(DashMnCheckpointSmlRecovery, RevivalTxLaterInWindowFiresOffTheRecoveredBan)
{
    RecoveryRig r;
    auto b44 = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    auto b45 = block_from_hex(kBlockHex1519545);
    b45.m_txs.push_back(pro_up_serv_tx(kQ1));

    r.h.blocks[1519545] = b45;
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({kQ1})));
    r.run(b44, /*tip=*/1519545);

    ASSERT_TRUE(r.h.published) << "lane status: " << r.h.lane.status();
    EXPECT_EQ(r.h.published_as_of, 1519545u);
    EXPECT_EQ(r.h.lane.sml_recovered(), 1u);

    std::map<uint256, MNState> out(r.h.published_set.begin(),
                                   r.h.published_set.end());
    const MNState& revived = out.at(uint256S(kQ1));
    EXPECT_TRUE(revived.isValid) << "the ProUpServTx must bring it back";
    EXPECT_EQ(revived.nPoSeBanHeight, 0u);
    EXPECT_EQ(revived.nPoSeRevivedHeight, 1519545u)
        << "revivedHeight still at the anchor's 1367840 means the revival"
           " branch never fired -- i.e. the exclusion did not record a ban"
           " height and the queue position is now wrong";
    // 1519545's own payee is unaffected: pass 0 projects from the PRE-block
    // list, where kQ1 is still excluded, so queue slot 3 was paid.
    EXPECT_EQ(out.at(uint256S(kQ3)).nLastPaidHeight, 1519545u);
}


// ═══════════════════════════════════════════════════════════════════════════
// 7. PoSe REMOVALS — the replay must SUBTRACT, and must survive a ban BURST
// ═══════════════════════════════════════════════════════════════════════════
//
// MEASURED, mainnet, hotel dashd 23.1.7, 2026-08-02:
//
//     protx list valid false 2513000  -> 2068 entries   (the anchor)
//     protx list valid false 2514874  -> 2059 entries   the chain FELL by 9
//     the bridge's replayed set        2067 -> 2070      we CLIMBED by 3
//
// A block replay can only ADD: a PoSe ban is derived by dashd from consensus
// and never appears as a special transaction.
//
// WHAT ACTUALLY BROKE was NOT missing machinery. The reactive per-mismatch
// walk RAN AND WORKED five times during that replay (bridge total 1/6 … 5/6).
// The chain then shows THREE masternodes leaving `protx list valid` together:
//
//     h=2514800   valid 2062, the projected MN PRESENT
//     h=2514873   valid 2059, the projected MN ABSENT   <- 3 bans / 73 blocks
//     h=2515025   valid 2063, still ABSENT (never revived)
//
// The walk adjudicates ONE exclusion per height and every step must land an
// exact coinbase script match, so three consecutive banned queue-head
// candidates defeat it. The WHOLESALE fold of sync_validity_from_sml() at the
// bridge's apply cursor is the fix precisely because it makes a burst
// indistinguishable from a single ban.
//
// The fold is valid at EXACTLY ONE cursor position (cursor == the height the
// SML is current at). Early is dangerous, late is benign — the cases below
// pin both directions.
// ═══════════════════════════════════════════════════════════════════════════
namespace {

using dash::coin::MnStateMachine;

// The SML the production seam hands the lane: the whole list plus the height
// it is current at. Both halves are load-bearing.
struct SmlSource {
    CSimplifiedMNList list;
    uint32_t          height{0};
    bool              present{false};

    void set(uint32_t h, const std::vector<std::pair<const char*, bool>>& es)
    {
        std::vector<CSimplifiedMNListEntry> v;
        v.reserve(es.size());
        for (const auto& [hex, valid] : es) {
            CSimplifiedMNListEntry e;
            e.proRegTxHash = uint256S(hex);
            e.isValid      = valid;
            v.push_back(e);
        }
        list    = CSimplifiedMNList(std::move(v));
        height  = h;
        present = true;
    }
};

void wire_sml_snapshot(MnCheckpointLane& lane, const SmlSource& src)
{
    lane.set_sml_snapshot_fn([&src]() -> MnCheckpointLane::SmlSnapshot {
        MnCheckpointLane::SmlSnapshot snap;
        if (!src.present) return snap;
        snap.list   = &src.list;
        snap.height = src.height;
        return snap;
    });
}

} // namespace

// ── CASE B1 (THE LOAD-BEARING ONE). A ban BURST: three masternodes banned at
// consecutive queue-head positions. This is the measured h=2514874 shape.
//
// The per-mismatch walk cannot carry it — it demotes kQ1, must then attribute
// the payment to kQ2 by exact coinbase script match, and kQ2 is banned too, so
// the block does not pay kQ2's script either and the walk stalls. The
// WHOLESALE fold removes all three in one pass before any of them is
// projected, and the bridge completes.
//
// The fold lands at cursor == H_sml = 1519544 (after that block is folded),
// and the burst bites at 1519545 — the first height the three could be
// projected. That is the ordering rule doing exactly its job.
TEST(DashMnCheckpointPoseFold, BanBurstSurvivesWholesaleFold)
{
    RecoveryRig r;
    SmlSource sml;
    sml.set(1519544, all_valid_except({kQ1, kQ2, kQ3}));
    wire_sml_snapshot(r.h.lane, sml);
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({kQ1, kQ2, kQ3})));

    // 1519544 is the REAL accepted block and pays kQ1 — untouched, so the
    // pre-fold replay of it must succeed on its own.
    // 1519545 really pays the kQ2/kQ3 (yeRZB) group; with kQ1..kQ3 all gone the
    // queue head is kQ4, so re-point that coinbase at kQ4's script.
    auto b45 = repay_coinbase(block_from_hex(kBlockHex1519545),
                              payout_of(r.cp, kQ2), payout_of(r.cp, kQ4));
    r.h.blocks[1519545] = b45;
    r.run(block_from_hex(kBlockHex1519544), /*tip=*/1519545);

    ASSERT_TRUE(r.h.published) << "lane status: " << r.h.lane.status();
    EXPECT_TRUE(r.h.lane.sml_folded());
    EXPECT_EQ(r.h.lane.sml_folded_at(), 1519544u)
        << "the fold must land at cursor == the height the SML is current at";
    EXPECT_EQ(r.h.lane.pose_removed(), 3u)
        << "all three leave in ONE pass -- that is what makes a burst"
           " indistinguishable from a single ban";
    EXPECT_EQ(r.h.lane.sml_recovered(), 0u)
        << "the per-mismatch walk must not have been needed, and must not"
           " have spent ANY of its per-bridge budget -- budget exhaustion is"
           " what actually kills a bridge on a burst (see"
           " TwinBanBurstExhaustsTheWalkBudgetAndIsTerminal)";
    EXPECT_EQ(r.h.lane.eligible_size(), 3u);

    std::map<uint256, MNState> out(r.h.published_set.begin(),
                                   r.h.published_set.end());
    for (const char* q : {kQ1, kQ2, kQ3})
        EXPECT_FALSE(out.at(uint256S(q)).isValid) << q;
    EXPECT_EQ(out.at(uint256S(kQ4)).nLastPaidHeight, 1519545u);
}

// ── CASE B1-TWIN (NEGATIVE) + THE CORRECTED MECHANISM.
//
// A burst does NOT defeat the per-mismatch walk merely by being consecutive:
// recover_from_sml_ban demotes a consecutive RUN inside one height (its loop
// keeps going while each candidate is attested invalid). What actually stops
// it is the CUMULATIVE PER-BRIDGE BUDGET —
//
//     m_sml_recovered_total + demoted.size() > m_sml_recovery_cap  -> refuse
//
// — and that budget is sized for ISOLATED bans: 4 + replay_distance/1000.
// The mainnet incident fits this exactly: the walk had legitimately reached
// "bridge total 5/6", the chain then put THREE masternodes out inside 73
// blocks, 5 + 3 = 8 > 6, the walk refused, and refusal is TERMINAL.
//
// This drives that arithmetic on a synthetic set with UNIQUE payout scripts,
// so rank and script are controlled exactly and no shared-payoutAddress group
// can short-circuit the walk. Budget 2 stands in for "4 of 6 already spent".
// The wholesale fold spends NO budget at all, which is why it survives.
namespace {

// Ten masternodes, unique scripts, strictly ascending CompareByLastPaid
// order: index 0 is the queue head.
std::vector<std::pair<uint256, MNState>> ranked_synthetic_set(size_t n)
{
    std::vector<std::pair<uint256, MNState>> out;
    for (size_t i = 0; i < n; ++i) {
        MNState st;
        st.isValid             = true;
        st.nRegisteredHeight   = 1000000;
        st.nLastPaidHeight     = static_cast<uint32_t>(1500000 + i);
        st.scriptPayout.m_data = synth_script(static_cast<uint8_t>(0x40 + i));
        st.collateralOutpoint.hash  = uint256S(kQ1);
        st.collateralOutpoint.index = static_cast<uint32_t>(i);
        uint256 h = uint256S(kQ2);
        h.data()[0] = static_cast<unsigned char>(0xa0 + i);
        out.emplace_back(h, st);
    }
    return out;
}

CSimplifiedMNList sml_banning(
    const std::vector<std::pair<uint256, MNState>>& set,
    std::initializer_list<size_t> banned_ranks)
{
    std::vector<CSimplifiedMNListEntry> v;
    for (size_t i = 0; i < set.size(); ++i) {
        CSimplifiedMNListEntry e;
        e.proRegTxHash = set[i].first;
        e.isValid      = true;
        for (size_t b : banned_ranks) if (b == i) e.isValid = false;
        v.push_back(e);
    }
    return CSimplifiedMNList(std::move(v));
}

// Block 1519544's real body with its coinbase re-pointed at one script.
dash::coin::BlockType block_paying(const std::vector<unsigned char>& script)
{
    auto blk = block_from_hex(kBlockHex1519544);
    blk.m_txs[0].vout[1].scriptPubKey.m_data = script;
    return blk;
}

MnStateMachine::SmlValidityFn validity_from(const CSimplifiedMNList& sml)
{
    return [&sml](const uint256& h) -> std::optional<bool> {
        for (const auto& e : sml.mnList)
            if (e.proRegTxHash == h) return e.isValid;
        return std::nullopt;
    };
}

} // namespace

TEST(DashMnCheckpointPoseFold, TwinBanBurstExhaustsTheWalkBudgetAndIsTerminal)
{
    const auto set = ranked_synthetic_set(10);
    const auto sml = sml_banning(set, {0, 1, 2});   // three at the queue head
    const auto blk = block_paying(set[3].second.scriptPayout.m_data);

    MnStateMachine walk_only;
    walk_only.load(set, 2514873);
    walk_only.set_sml_validity_fn(validity_from(sml));
    walk_only.set_sml_current_height(2514874);
    // Budget left after the walk legitimately reached 5/6 on this bridge.
    walk_only.set_sml_recovery_cap(2);

    const auto r = walk_only.apply_block(blk, 2514874);

    EXPECT_TRUE(r.payee_desync)
        << "3 demotions against a budget of 2 must be REFUSED, and refusal on"
           " the bridge is terminal -- this is the h=2514874 fail-close";
    EXPECT_EQ(r.sml_recovered, 0u);
    EXPECT_TRUE(walk_only.entries().at(set[0].first).isValid)
        << "a refused walk must not leave a partial exclusion behind";
    EXPECT_EQ(walk_only.eligible_size(), 10u)
        << "the set did not fall at all -- the measured 'we only ever ADD'";
}

// The same burst, same budget, with the WHOLESALE FOLD applied first. The fold
// spends no budget, so the burst costs nothing and the queue head is already
// correct when the block is projected.
TEST(DashMnCheckpointPoseFold, WholesaleFoldSurvivesTheSameBurstOnTheSameBudget)
{
    const auto set = ranked_synthetic_set(10);
    const auto sml = sml_banning(set, {0, 1, 2});
    const auto blk = block_paying(set[3].second.scriptPayout.m_data);

    MnStateMachine folded;
    folded.load(set, 2514873);
    folded.set_sml_validity_fn(validity_from(sml));
    folded.set_sml_current_height(2514873);
    folded.set_sml_recovery_cap(2);

    // Fold at cursor == the height the SML is current at (2514873), i.e. after
    // apply_block(2514873) and BEFORE apply_block(2514874).
    const auto vr = folded.sync_validity_from_sml(sml, 2514873);
    EXPECT_EQ(vr.flipped_to_invalid, 3u) << "all three leave in ONE pass";
    EXPECT_EQ(folded.eligible_size(), 7u) << "the set FALLS, as the chain's did";

    const auto r = folded.apply_block(blk, 2514874);

    EXPECT_FALSE(r.payee_desync) << "the bridge survives the burst";
    EXPECT_EQ(r.sml_recovered, 0u)
        << "a fold spends NO walk budget -- that is why a burst costs nothing";
    EXPECT_EQ(r.paid, 1u);
    EXPECT_EQ(folded.entries().at(set[3].first).nLastPaidHeight, 2514874u)
        << "the payment lands on the first masternode the chain still held"
           " eligible";
}

// ISOLATION CONTROL. The very same burst with a budget that can absorb it is
// handled by the walk alone. Without this, the two cases above would look like
// "bursts are unhandleable" rather than "the BUDGET is the binding constraint",
// which is the finding that matters for sizing it.
TEST(DashMnCheckpointPoseFold, SameBurstWithAmpleBudgetIsHandledByTheWalk)
{
    const auto set = ranked_synthetic_set(10);
    const auto sml = sml_banning(set, {0, 1, 2});
    const auto blk = block_paying(set[3].second.scriptPayout.m_data);

    MnStateMachine m;
    m.load(set, 2514873);
    m.set_sml_validity_fn(validity_from(sml));
    m.set_sml_current_height(2514874);
    m.set_sml_recovery_cap(8);

    const auto r = m.apply_block(blk, 2514874);
    EXPECT_FALSE(r.payee_desync);
    EXPECT_EQ(r.sml_recovered, 3u)
        << "the walk CAN demote a consecutive run inside one height -- it is"
           " the cumulative cap, not the burst shape, that defeats it";
}

// ── CASE B2. ORDERING: the fold NEVER runs early. cursor < H_sml must leave
// the set untouched.
//
// Why early is the dangerous direction: a masternode banned at h_ban <= H_sml
// would be removed at heights where the chain still held it valid and paid it.
// Inside a shared-payoutAddress group that divergence is SCRIPT-INVISIBLE, so
// the coinbase cross-check passes and the bridge publishes a WRONG queue
// silently. An early fold also perturbs queue POSITION, because
// sync_validity_from_sml bumps nPoSeRevivedHeight -- a CompareByLastPaid key.
TEST(DashMnCheckpointPoseFold, FoldNeverRunsBeforeTheCursorReachesTheSmlHeight)
{
    RecoveryRig r;
    SmlSource sml;
    // The SML is current at a height the bridge never reaches.
    sml.set(1519600, all_valid_except({kQ1}));
    wire_sml_snapshot(r.h.lane, sml);
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({kQ1})));

    // The real block pays kQ1, which is still eligible at this height. An
    // early fold would have removed it, projected kQ2, and desynced.
    r.run(block_from_hex(kBlockHex1519544));

    ASSERT_TRUE(r.h.published) << r.h.lane.status();
    EXPECT_FALSE(r.h.lane.sml_folded())
        << "cursor 1519544 != SML height 1519600 -- the fold must NOT run";
    EXPECT_EQ(r.h.lane.pose_removed(), 0u);
    EXPECT_EQ(r.h.lane.eligible_size(), 6u);

    std::map<uint256, MNState> out(r.h.published_set.begin(),
                                   r.h.published_set.end());
    EXPECT_TRUE(out.at(uint256S(kQ1)).isValid)
        << "the chain still held it valid here and actually paid it";
    EXPECT_EQ(out.at(uint256S(kQ1)).nLastPaidHeight, 1519544u);
    EXPECT_EQ(out.at(uint256S(kQ1)).nPoSeRevivedHeight, 1367840u)
        << "an early fold would also have moved its CompareByLastPaid key";
}

// ── CASE B2-TWIN (POSITIVE CONTROL for B2). Move the SML's height onto the
// cursor and the very same wiring folds. Without this, B2 could be passing
// because the seam does nothing at all.
TEST(DashMnCheckpointPoseFold, TwinSameWiringFoldsOnceTheHeightsMeet)
{
    RecoveryRig r;
    SmlSource sml;
    sml.set(1519544, all_valid_except({kQ1}));
    wire_sml_snapshot(r.h.lane, sml);
    r.run(block_from_hex(kBlockHex1519544));

    ASSERT_TRUE(r.h.published) << r.h.lane.status();
    EXPECT_TRUE(r.h.lane.sml_folded());
    EXPECT_EQ(r.h.lane.sml_folded_at(), 1519544u);
    EXPECT_EQ(r.h.lane.pose_removed(), 1u);
    EXPECT_EQ(r.h.lane.eligible_size(), 5u);
    // The fold runs AFTER apply_block(1519544), so that block's own payee was
    // still projected from the pre-fold set -- kQ1 was paid, exactly as the
    // chain did. That is the "late is benign" half of the ordering rule.
    std::map<uint256, MNState> out(r.h.published_set.begin(),
                                   r.h.published_set.end());
    EXPECT_EQ(out.at(uint256S(kQ1)).nLastPaidHeight, 1519544u);
    EXPECT_FALSE(out.at(uint256S(kQ1)).isValid);
}

// ── CASE B3. A masternode banned AND revived inside the window ends VALID.
// sync_validity_from_sml owns the (isValid, banHeight, revivedHeight) triple,
// so a fold against an SML that shows it live leaves it live.
TEST(DashMnCheckpointPoseFold, BannedThenRevivedInsideTheWindowEndsValid)
{
    RecoveryRig r;
    SmlSource sml;
    sml.set(1519545, all_valid_except({}));   // live again by the fold height
    wire_sml_snapshot(r.h.lane, sml);
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({kQ1})));

    // 1519544 is repaid to kQ2, i.e. dashd skipped kQ1 while it was banned.
    // The walk carries that single mismatch; the fold at 1519545 then confirms
    // kQ1 is live again and lifts the exclusion the walk recorded.
    auto b44 = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    r.h.blocks[1519545] = block_from_hex(kBlockHex1519545);
    r.run(b44, /*tip=*/1519545);

    ASSERT_TRUE(r.h.published) << r.h.lane.status();
    EXPECT_EQ(r.h.lane.sml_recovered(), 1u) << "the walk handled the mismatch";
    EXPECT_TRUE(r.h.lane.sml_folded());
    EXPECT_EQ(r.h.lane.pose_reinstated(), 1u)
        << "the fold must be able to REVIVE, not only remove";

    std::map<uint256, MNState> out(r.h.published_set.begin(),
                                   r.h.published_set.end());
    const MNState& revived = out.at(uint256S(kQ1));
    EXPECT_TRUE(revived.isValid) << "ban+revive inside the window ends VALID";
    EXPECT_EQ(revived.nPoSeBanHeight, 0u);
}

// ── CASE B4. FRESHNESS GATE. A STALE SML must not license a PERMANENT
// demotion: it can attest isValid=false for a masternode that has since been
// revived, and with a coincidental runner-up script match the walk would
// exclude it for the rest of the bridge. An SML older than the height being
// adjudicated cannot speak to that height, so it is NO OPINION, never false.
TEST(DashMnCheckpointPoseFold, StaleSmlCannotLicenseAPermanentDemotion)
{
    MnStateMachine m;
    auto cp = good_checkpoint();
    m.load(cp.entries, 1519543);
    m.set_sml_recovery_cap(8);
    m.set_sml_validity_fn(
        [](const uint256& h) -> std::optional<bool> {
            return h == uint256S(kQ1) ? std::optional<bool>{false}
                                      : std::optional<bool>{true};
        });
    // The SML is current at 1519500 — BEFORE the block being adjudicated.
    m.set_sml_current_height(1519500);
    EXPECT_FALSE(m.sml_covers(1519544));

    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(cp, kQ1), payout_of(cp, kQ2));
    const auto r = m.apply_block(blk, 1519544);

    EXPECT_TRUE(r.payee_desync)
        << "a stale attestation must not be accepted as evidence of a ban";
    EXPECT_EQ(r.sml_recovered, 0u);
    EXPECT_TRUE(m.entries().at(uint256S(kQ1)).isValid)
        << "nothing may be permanently excluded on a stale SML";
}

// ── CASE B4-TWIN (POSITIVE CONTROL). The same attestation from an SML that IS
// current at the adjudicated height is accepted. Without this twin, B4 could
// be passing because the walk never fires at all.
TEST(DashMnCheckpointPoseFold, TwinFreshSmlAtTheSameHeightIsAccepted)
{
    MnStateMachine m;
    auto cp = good_checkpoint();
    m.load(cp.entries, 1519543);
    m.set_sml_recovery_cap(8);
    m.set_sml_validity_fn(
        [](const uint256& h) -> std::optional<bool> {
            return h == uint256S(kQ1) ? std::optional<bool>{false}
                                      : std::optional<bool>{true};
        });
    m.set_sml_current_height(1519544);
    EXPECT_TRUE(m.sml_covers(1519544));

    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(cp, kQ1), payout_of(cp, kQ2));
    const auto r = m.apply_block(blk, 1519544);

    EXPECT_FALSE(r.payee_desync);
    EXPECT_EQ(r.sml_recovered, 1u);
    EXPECT_FALSE(m.entries().at(uint256S(kQ1)).isValid);
}

// ── CASE B5. Set-size accounting on a fixture modelled directly on the real
// mainnet delta: 2068 payee-eligible at the anchor, 12 PoSe-banned and 3
// registered inside the window. The chain reported 2068 -> 2059. A replay that
// can only ADD reports 2068 -> 2071 — a climb of exactly the +3 that was
// measured. Both machines are driven identically except for the fold.
TEST(DashMnCheckpointPoseFold, SetSizeAccountingMatchesTheMainnetDelta)
{
    constexpr uint32_t kAnchor  = 2513000;
    constexpr uint32_t kApplyAt = 2513001;
    constexpr size_t   kAnchorEligible = 2068;
    constexpr size_t   kBanned = 12;
    constexpr size_t   kAdds   = 3;

    auto seed_set = [&] {
        std::vector<std::pair<uint256, MNState>> out;
        out.reserve(kAnchorEligible);
        for (size_t i = 0; i < kAnchorEligible; ++i) {
            MNState st;
            st.isValid             = true;
            st.nRegisteredHeight   = 2000000;
            st.nLastPaidHeight     = static_cast<uint32_t>(kAnchor - 2100 + i);
            st.scriptPayout.m_data = synth_script(0);
            // Unique payout script per masternode: a shared one would hide a
            // wrong attribution behind the script-granular cross-check.
            st.scriptPayout.m_data[3] = static_cast<unsigned char>(i & 0xff);
            st.scriptPayout.m_data[4] = static_cast<unsigned char>(i >> 8);
            st.collateralOutpoint.hash  = uint256S(kQ1);
            st.collateralOutpoint.index = static_cast<uint32_t>(i);
            uint256 h = uint256S(kQ2);
            h.data()[0] = static_cast<unsigned char>(i & 0xff);
            h.data()[1] = static_cast<unsigned char>(i >> 8);
            out.emplace_back(h, st);
        }
        return out;
    };

    const auto anchor_set = seed_set();
    // The 12 the SML attests banned are spread through the queue, NOT at its
    // head, so nothing the coinbase cross-check could have stumbled into.
    std::vector<CSimplifiedMNListEntry> v;
    v.reserve(anchor_set.size());
    for (size_t i = 0; i < anchor_set.size(); ++i) {
        CSimplifiedMNListEntry e;
        e.proRegTxHash = anchor_set[i].first;
        e.isValid      = !((i % 3 == 0) && (i / 3) < kBanned);
        v.push_back(e);
    }
    const CSimplifiedMNList sml(std::move(v));

    auto make_block = [&](const std::vector<unsigned char>& pay_to) {
        auto blk = block_from_hex(kBlockHex1519544);
        blk.m_txs[0].vout[1].scriptPubKey.m_data = pay_to;
        for (size_t i = 0; i < kAdds; ++i)
            blk.m_txs.push_back(
                pro_reg_tx(synth_script(static_cast<uint8_t>(0xd0 + i)),
                           static_cast<uint32_t>(i)));
        return blk;
    };

    // ── The replay AS IT WAS: additions only. ──────────────────────────────
    MnStateMachine before;
    before.load(anchor_set, kAnchor);
    ASSERT_EQ(before.eligible_size(), kAnchorEligible);
    {
        auto proj = before.find_expected_payee();
        ASSERT_TRUE(proj.has_value());
        const auto r = before.apply_block(
            make_block(before.entries().at(*proj).scriptPayout.m_data),
            kApplyAt);
        ASSERT_FALSE(r.payee_desync);
        EXPECT_EQ(r.registered, kAdds);
    }
    EXPECT_EQ(before.eligible_size(), kAnchorEligible + kAdds)
        << "a replay that can only ADD climbs -- the measured 2067 -> 2070";

    // ── The replay WITH the wholesale fold at the apply cursor. ────────────
    MnStateMachine after;
    after.load(anchor_set, kAnchor);
    {
        auto proj = after.find_expected_payee();
        ASSERT_TRUE(proj.has_value());
        const auto r = after.apply_block(
            make_block(after.entries().at(*proj).scriptPayout.m_data),
            kApplyAt);
        ASSERT_FALSE(r.payee_desync);
    }
    // Fold at cursor == H_sml == kApplyAt: after apply_block(kApplyAt), before
    // any later block. The three registered by that block are ALREADY in the
    // set here and are simply absent from the SML, so the fold is a no-op for
    // them (SyncFromSmlResult::sml_only is the mirror case) -- a masternode
    // cannot be retro-banned at the height it registers.
    const auto vr = after.sync_validity_from_sml(sml, kApplyAt);
    EXPECT_EQ(vr.flipped_to_invalid, kBanned);
    EXPECT_EQ(vr.flipped_to_valid, 0u);

    EXPECT_EQ(after.eligible_size(), 2059u)
        << "2068 - 12 banned + 3 registered = 2059, which is what"
           " `protx list valid false 2514874` actually returned";
    EXPECT_EQ(after.size(), kAnchorEligible + kAdds)
        << "REGISTERED is unchanged by a PoSe ban -- comparing THAT number"
           " against `protx list valid` is what hid this bug";
}

// ── CASE B6. The fail-closed message must MEASURE the divergence rather than
// list hypotheses: set size before/after, adds, removals by cause, whether the
// fold ran, the projected proTxHash and what the SML says about it.
TEST(DashMnCheckpointPoseFold, FailClosedReportsTheActualDelta)
{
    RecoveryRig r;
    SmlSource sml;
    sml.set(1519544, all_valid_except({}));   // nothing to remove
    wire_sml_snapshot(r.h.lane, sml);
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({})));

    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    r.run(blk);

    ASSERT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed);
    const std::string s = r.h.lane.status();
    EXPECT_NE(s.find("SET DELTA"), std::string::npos) << s;
    EXPECT_NE(s.find("6 at the anchor"), std::string::npos) << s;
    EXPECT_NE(s.find("ADDS: 0 registrations"), std::string::npos) << s;
    EXPECT_NE(s.find("0 PoSe (SML-attested)"), std::string::npos) << s;
    EXPECT_NE(s.find("PROJECTED PAYEE: " + uint256S(kQ1).GetHex()),
              std::string::npos)
        << "the operator must be told WHICH masternode we projected: " << s;
    EXPECT_NE(s.find("attests it VALID"), std::string::npos)
        << "...and what the SML thinks of it: " << s;
}

// ── CASE B6-TWIN (NEGATIVE). An attested ban that could not be repaired must
// read DIFFERENTLY from an attested-valid desync, or the message is not a
// measurement.
TEST(DashMnCheckpointPoseFold, FailClosedDistinguishesAnAttestedBan)
{
    RecoveryRig r;
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({kQ1})));
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), synth_script(0x5a));
    r.run(blk);

    ASSERT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed);
    const std::string s = r.h.lane.status();
    EXPECT_NE(s.find("attests it INVALID"), std::string::npos) << s;
    EXPECT_EQ(s.find("attests it VALID"), std::string::npos)
        << "the two verdicts must not be reported with the same words: " << s;
    EXPECT_NE(s.find("NO SML SNAPSHOT SEAM IS WIRED"), std::string::npos)
        << "an operator whose fold seam is unwired must be told so: " << s;
}
