// test_v36_cross_impl_refhash.cpp — Cross-implementation ref_hash + gentx_hash test.
//
// Computes V36 ref_stream → ref_hash → coinbase → gentx_hash using the same
// field values as the Python test (test_v36_cross_impl_refhash.py).
// Both must produce IDENTICAL hashes for the same inputs.
//
// Test vectors generated by: pypy p2pool/test/test_v36_cross_impl_refhash.py

#include <gtest/gtest.h>

#include <algorithm>
#include <cstdint>
#include <cstring>
#include <map>
#include <string>
#include <vector>

#include <btclibs/crypto/sha256.h>

namespace {

// --- Helpers ---

std::vector<unsigned char> hex_to_bytes(const std::string& hex)
{
    std::vector<unsigned char> bytes;
    bytes.reserve(hex.size() / 2);
    for (size_t i = 0; i + 1 < hex.size(); i += 2) {
        unsigned char hi = (hex[i] >= 'a') ? (hex[i] - 'a' + 10) : (hex[i] - '0');
        unsigned char lo = (hex[i+1] >= 'a') ? (hex[i+1] - 'a' + 10) : (hex[i+1] - '0');
        bytes.push_back((hi << 4) | lo);
    }
    return bytes;
}

std::string bytes_to_hex(const unsigned char* data, size_t len)
{
    static const char digits[] = "0123456789abcdef";
    std::string hex;
    hex.reserve(len * 2);
    for (size_t i = 0; i < len; ++i) {
        hex.push_back(digits[data[i] >> 4]);
        hex.push_back(digits[data[i] & 0xf]);
    }
    return hex;
}

// Bitcoin-style VarInt encoding
void write_varint(std::vector<unsigned char>& buf, uint64_t n)
{
    if (n < 253) {
        buf.push_back(static_cast<unsigned char>(n));
    } else if (n < 0x10000) {
        buf.push_back(253);
        buf.push_back(n & 0xff);
        buf.push_back((n >> 8) & 0xff);
    } else if (n < 0x100000000ULL) {
        buf.push_back(254);
        for (int i = 0; i < 4; ++i) buf.push_back((n >> (i * 8)) & 0xff);
    } else {
        buf.push_back(255);
        for (int i = 0; i < 8; ++i) buf.push_back((n >> (i * 8)) & 0xff);
    }
}

void write_le32(std::vector<unsigned char>& buf, uint32_t v)
{
    for (int i = 0; i < 4; ++i) buf.push_back((v >> (i * 8)) & 0xff);
}

void write_le16(std::vector<unsigned char>& buf, uint16_t v)
{
    buf.push_back(v & 0xff);
    buf.push_back((v >> 8) & 0xff);
}

void write_le64(std::vector<unsigned char>& buf, uint64_t v)
{
    for (int i = 0; i < 8; ++i) buf.push_back((v >> (i * 8)) & 0xff);
}

void write_bytes(std::vector<unsigned char>& buf, const std::vector<unsigned char>& data)
{
    buf.insert(buf.end(), data.begin(), data.end());
}

void write_varstr(std::vector<unsigned char>& buf, const std::vector<unsigned char>& data)
{
    write_varint(buf, data.size());
    write_bytes(buf, data);
}

// SHA256d (double SHA256) — standalone, no dependency on core/hash.hpp
std::vector<unsigned char> sha256d(const std::vector<unsigned char>& data)
{
    unsigned char hash1[CSHA256::OUTPUT_SIZE];
    CSHA256().Write(data.data(), data.size()).Finalize(hash1);
    unsigned char hash2[CSHA256::OUTPUT_SIZE];
    CSHA256().Write(hash1, CSHA256::OUTPUT_SIZE).Finalize(hash2);
    return std::vector<unsigned char>(hash2, hash2 + CSHA256::OUTPUT_SIZE);
}

std::vector<unsigned char> make_p2pkh_script(const std::vector<unsigned char>& hash160)
{
    std::vector<unsigned char> s = {0x76, 0xa9, 0x14};
    s.insert(s.end(), hash160.begin(), hash160.end());
    s.push_back(0x88);
    s.push_back(0xac);
    return s;
}

std::vector<unsigned char> make_p2wpkh_script(const std::vector<unsigned char>& hash160)
{
    std::vector<unsigned char> s = {0x00, 0x14};
    s.insert(s.end(), hash160.begin(), hash160.end());
    return s;
}

std::vector<unsigned char> make_p2sh_script(const std::vector<unsigned char>& hash160)
{
    std::vector<unsigned char> s = {0xa9, 0x14};
    s.insert(s.end(), hash160.begin(), hash160.end());
    s.push_back(0x87);
    return s;
}

const std::vector<unsigned char> TESTNET_IDENTIFIER = hex_to_bytes("cca5e24ec6408b1e");
const std::vector<unsigned char> COMBINED_DONATION_SCRIPT = hex_to_bytes("a9148c6272621d89e8fa526dd86acff60c7136be8e8587");

// --- Build ref_stream (V36 format) ---

std::vector<unsigned char> build_ref_stream(
    const std::vector<unsigned char>& identifier,
    const std::vector<unsigned char>& prev_hash,  // 32 bytes or empty (None → 32 zeros)
    const std::vector<unsigned char>& coinbase,
    uint32_t nonce,
    const std::vector<unsigned char>& pubkey_hash,  // 20 bytes
    uint8_t pubkey_type,
    uint64_t subsidy,
    uint16_t donation,
    uint8_t stale_info,
    uint32_t desired_version,
    const std::vector<unsigned char>& far_share_hash,  // 32 bytes or empty
    uint32_t max_bits,
    uint32_t bits,
    uint32_t timestamp,
    uint32_t absheight,
    uint64_t abswork,
    const std::vector<unsigned char>& merged_payout_hash)  // 32 bytes or empty
{
    std::vector<unsigned char> buf;
    buf.reserve(256);

    // 1. identifier (8 bytes)
    write_bytes(buf, identifier);

    // 2. prev_hash: PossiblyNoneType(0, IntType(256)) — None → 32 zeros
    if (prev_hash.empty()) {
        buf.insert(buf.end(), 32, 0x00);
    } else {
        write_bytes(buf, prev_hash);
    }

    // 3. coinbase: VarStrType
    write_varstr(buf, coinbase);

    // 4. nonce: IntType(32) LE
    write_le32(buf, nonce);

    // 5. pubkey_hash: IntType(160) — 20 bytes LE
    write_bytes(buf, pubkey_hash);

    // 6. pubkey_type: IntType(8)
    buf.push_back(pubkey_type);

    // 7. subsidy: VarIntType
    write_varint(buf, subsidy);

    // 8. donation: IntType(16) LE
    write_le16(buf, donation);

    // 9. stale_info: IntType(8)
    buf.push_back(stale_info);

    // 10. desired_version: VarIntType
    write_varint(buf, desired_version);

    // 11. segwit_data: PossiblyNoneType → default = empty branch + 0xff*32 root
    write_varint(buf, 0);  // branch list len = 0
    // index is IntType(0) — not serialized
    buf.insert(buf.end(), 32, 0xff);  // wtxid_merkle_root = 2^256-1

    // 12. merged_addresses: PossiblyNoneType([], ListType)
    write_varint(buf, 0);  // empty list

    // 13. far_share_hash: PossiblyNoneType(0, IntType(256))
    if (far_share_hash.empty()) {
        buf.insert(buf.end(), 32, 0x00);
    } else {
        write_bytes(buf, far_share_hash);
    }

    // 14. max_bits: FloatingIntegerType — 4 bytes LE
    write_le32(buf, max_bits);

    // 15. bits: FloatingIntegerType — 4 bytes LE
    write_le32(buf, bits);

    // 16. timestamp: IntType(32) LE
    write_le32(buf, timestamp);

    // 17. absheight: IntType(32) LE
    write_le32(buf, absheight);

    // 18. abswork: VarIntType
    write_varint(buf, abswork);

    // 19. merged_coinbase_info: PossiblyNoneType([], ListType)
    write_varint(buf, 0);  // empty list

    // 20. merged_payout_hash: PossiblyNoneType(0, IntType(256))
    if (merged_payout_hash.empty()) {
        buf.insert(buf.end(), 32, 0x00);
    } else {
        write_bytes(buf, merged_payout_hash);
    }

    // 21. message_data: PossiblyNoneType(b'', VarStrType)
    write_varint(buf, 0);  // empty string

    return buf;
}

// --- Build V36 coinbase transaction (non-witness for txid) ---

using ScriptAmount = std::pair<std::vector<unsigned char>, uint64_t>;

std::vector<unsigned char> build_v36_coinbase(
    const std::vector<unsigned char>& coinbase_script,
    const std::vector<ScriptAmount>& sorted_outputs,
    const std::vector<unsigned char>& donation_script,
    uint64_t donation_amount,
    const std::vector<unsigned char>& ref_hash,  // 32 bytes
    uint64_t last_txout_nonce)
{
    std::vector<unsigned char> tx;
    tx.reserve(512);

    // version = 1
    write_le32(tx, 1);

    // vin count = 1
    write_varint(tx, 1);

    // vin[0]: coinbase
    tx.insert(tx.end(), 32, 0x00);         // prev_hash = 0
    write_le32(tx, 0xffffffff);            // prev_index = -1
    write_varstr(tx, coinbase_script);     // scriptSig
    write_le32(tx, 0xffffffff);            // sequence

    // output count
    size_t n_outs = sorted_outputs.size() + 1 + 1;  // payouts + donation + OP_RETURN
    write_varint(tx, n_outs);

    // PPLNS payout outputs (sorted)
    for (const auto& [script, amount] : sorted_outputs) {
        write_le64(tx, amount);
        write_varstr(tx, script);
    }

    // donation output
    write_le64(tx, donation_amount);
    write_varstr(tx, donation_script);

    // OP_RETURN output
    std::vector<unsigned char> op_return_script;
    op_return_script.push_back(0x6a);  // OP_RETURN
    op_return_script.push_back(0x28);  // PUSH 40
    op_return_script.insert(op_return_script.end(), ref_hash.begin(), ref_hash.end());
    {
        auto* p = reinterpret_cast<const unsigned char*>(&last_txout_nonce);
        op_return_script.insert(op_return_script.end(), p, p + 8);
    }
    write_le64(tx, 0);  // value = 0
    write_varstr(tx, op_return_script);

    // locktime = 0
    write_le32(tx, 0);

    return tx;
}

// --- Compute sorted PPLNS outputs (V36) ---

struct TestResult {
    std::vector<unsigned char> ref_hash;
    std::vector<unsigned char> gentx_hash;
    std::vector<ScriptAmount> sorted_outputs;
    uint64_t donation_amount;
};

TestResult compute_test_vector(
    const std::map<std::vector<unsigned char>, uint64_t>& weights,
    uint64_t subsidy,
    const std::vector<unsigned char>& prev_hash,
    const std::vector<unsigned char>& coinbase_script,
    uint32_t nonce,
    const std::vector<unsigned char>& pubkey_hash,
    uint8_t pubkey_type,
    uint16_t donation,
    uint32_t timestamp,
    uint32_t max_bits,
    uint32_t bits,
    uint32_t absheight,
    uint64_t abswork,
    const std::vector<unsigned char>& far_share_hash,
    uint64_t last_txout_nonce)
{
    // 1. Compute amounts from weights (V36: no haircut)
    uint64_t total_weight = 0;
    for (const auto& [s, w] : weights) total_weight += w;

    std::map<std::vector<unsigned char>, uint64_t> amounts;
    for (const auto& [script, weight] : weights) {
        uint64_t amt = subsidy * weight / total_weight;
        if (amt > 0)
            amounts[script] = amt;
    }

    uint64_t sum_amounts = 0;
    for (const auto& [s, a] : amounts) sum_amounts += a;
    uint64_t donation_amount = subsidy - sum_amounts;

    // V36: donation >= 1
    // Deterministic tiebreak: (amount, script) — largest script wins when equal
    if (donation_amount < 1 && subsidy > 0 && !amounts.empty()) {
        auto largest = std::max_element(amounts.begin(), amounts.end(),
            [](const auto& a, const auto& b) {
                if (a.second != b.second) return a.second < b.second;
                return a.first < b.first;
            });
        if (largest != amounts.end() && largest->second > 0) {
            largest->second -= 1;
            sum_amounts -= 1;
            donation_amount = subsidy - sum_amounts;
        }
    }

    // 2. Sort outputs: (amount, script) ascending, exclude donation
    std::vector<ScriptAmount> sorted_outputs;
    for (const auto& [script, amt] : amounts) {
        if (script != COMBINED_DONATION_SCRIPT && amt > 0)
            sorted_outputs.push_back({script, amt});
    }
    std::sort(sorted_outputs.begin(), sorted_outputs.end(),
        [](const ScriptAmount& a, const ScriptAmount& b) {
            if (a.second != b.second) return a.second < b.second;
            return a.first < b.first;
        });

    // 3. Build ref_stream → ref_hash
    auto ref_bytes = build_ref_stream(
        TESTNET_IDENTIFIER, prev_hash, coinbase_script,
        nonce, pubkey_hash, pubkey_type, subsidy, donation,
        0 /*stale_info*/, 36 /*desired_version*/,
        far_share_hash, max_bits, bits, timestamp, absheight, abswork,
        {} /*merged_payout_hash = None*/);
    auto ref_hash = sha256d(ref_bytes);

    // 4. Build coinbase → gentx_hash
    auto coinbase_tx = build_v36_coinbase(
        coinbase_script, sorted_outputs, COMBINED_DONATION_SCRIPT,
        donation_amount, ref_hash, last_txout_nonce);
    auto gentx_hash = sha256d(coinbase_tx);

    return {ref_hash, gentx_hash, sorted_outputs, donation_amount};
}

} // namespace

// ============================================================================
// Test vectors — must produce IDENTICAL hashes to Python test
// ============================================================================

TEST(V36CrossImplRefHash, MainCase_TwoP2PKHMiners)
{
    std::map<std::vector<unsigned char>, uint64_t> weights = {
        {make_p2pkh_script(std::vector<unsigned char>(20, 0xaa)), 7000000},
        {make_p2pkh_script(std::vector<unsigned char>(20, 0xbb)), 3000000},
    };

    std::vector<unsigned char> coinbase_script(
        reinterpret_cast<const unsigned char*>("/c2pool/test/"),
        reinterpret_cast<const unsigned char*>("/c2pool/test/") + 13);

    auto result = compute_test_vector(
        weights,
        5000000000ULL,
        hex_to_bytes("1111111111111111111111111111111111111111111111111111111111111111"),
        coinbase_script,
        0,
        std::vector<unsigned char>(20, 0xaa),
        0, // P2PKH
        50,
        1700000000,
        0x1e0fffff,
        0x1e0fffff,
        100,
        12345,
        {}, // far_share_hash = None
        0x0102030405060708ULL);

    // Python-generated expected values:
    auto expected_ref_stream = hex_to_bytes(
        "cca5e24ec6408b1e"  // identifier
        "1111111111111111111111111111111111111111111111111111111111111111"  // prev_hash
        "0d2f6332706f6f6c2f746573742f"  // coinbase VarStr
        "00000000"  // nonce
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"  // pubkey_hash
        "00"  // pubkey_type
        "ff00f2052a01000000"  // subsidy VarInt
        "3200"  // donation
        "00"  // stale_info
        "24"  // desired_version VarInt(36)
        "00"  // segwit branch list len=0
        "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"  // wtxid_root sentinel
        "00"  // merged_addresses empty
        "0000000000000000000000000000000000000000000000000000000000000000"  // far_share_hash=None
        "ffff0f1e"  // max_bits
        "ffff0f1e"  // bits
        "00f15365"  // timestamp
        "64000000"  // absheight
        "fd3930"  // abswork VarInt(12345)
        "00"  // merged_coinbase_info empty
        "0000000000000000000000000000000000000000000000000000000000000000"  // merged_payout_hash=None
        "00"  // message_data empty
    );
    auto expected_ref_hash = hex_to_bytes(
        "075edc750be06ceefd2eba6c9556f277c3950c6b5a109d879dd1270994e67b6a");
    auto expected_gentx_hash = hex_to_bytes(
        "74fd7b4ee0716322cc1dc743f29ec69b7de45d854d02262f45b6a3a79457d220");

    // First compare ref_stream bytes to find any serialization divergence
    auto ref_bytes = build_ref_stream(
        TESTNET_IDENTIFIER,
        hex_to_bytes("1111111111111111111111111111111111111111111111111111111111111111"),
        coinbase_script, 0, std::vector<unsigned char>(20, 0xaa), 0,
        5000000000ULL, 50, 0, 36, {}, 0x1e0fffff, 0x1e0fffff, 1700000000, 100, 12345, {});

    ASSERT_EQ(ref_bytes.size(), expected_ref_stream.size())
        << "ref_stream length mismatch: C++=" << ref_bytes.size()
        << " Python=" << expected_ref_stream.size();

    if (ref_bytes != expected_ref_stream) {
        // Find first divergent byte
        for (size_t i = 0; i < ref_bytes.size(); ++i) {
            if (ref_bytes[i] != expected_ref_stream[i]) {
                ADD_FAILURE() << "ref_stream diverges at byte " << i
                    << ": C++=" << bytes_to_hex(&ref_bytes[i], std::min(size_t(16), ref_bytes.size()-i))
                    << " Python=" << bytes_to_hex(&expected_ref_stream[i], std::min(size_t(16), expected_ref_stream.size()-i))
                    << "\n  Full C++:    " << bytes_to_hex(ref_bytes.data(), ref_bytes.size())
                    << "\n  Full Python: " << bytes_to_hex(expected_ref_stream.data(), expected_ref_stream.size());
                break;
            }
        }
    }

    EXPECT_EQ(result.ref_hash, expected_ref_hash)
        << "ref_hash mismatch!\n  C++:    " << bytes_to_hex(result.ref_hash.data(), 32)
        << "\n  Python: " << bytes_to_hex(expected_ref_hash.data(), 32);

    EXPECT_EQ(result.gentx_hash, expected_gentx_hash)
        << "gentx_hash mismatch!\n  C++:    " << bytes_to_hex(result.gentx_hash.data(), 32)
        << "\n  Python: " << bytes_to_hex(expected_gentx_hash.data(), 32);

    // Verify output ordering
    ASSERT_EQ(result.sorted_outputs.size(), 2u);
    EXPECT_EQ(result.sorted_outputs[0].second, 1500000000u);  // bb (lower)
    EXPECT_EQ(result.sorted_outputs[1].second, 3499999999u);  // aa (higher)
    EXPECT_EQ(result.donation_amount, 1u);
}

TEST(V36CrossImplRefHash, EdgeCase_MixedTypes)
{
    auto hash160 = std::vector<unsigned char>(20, 0xdd);
    std::map<std::vector<unsigned char>, uint64_t> weights = {
        {make_p2pkh_script(hash160),  1500000},
        {make_p2wpkh_script(hash160), 1000000},
        {make_p2sh_script(hash160),   500000},
    };

    std::vector<unsigned char> coinbase_script(
        reinterpret_cast<const unsigned char*>("test"),
        reinterpret_cast<const unsigned char*>("test") + 4);

    auto result = compute_test_vector(
        weights,
        3000000000ULL,
        hex_to_bytes("2222222222222222222222222222222222222222222222222222222222222222"),
        coinbase_script,
        42,
        hash160,
        0,
        50,
        1700000001,
        0x1e0fffff,
        0x1d00ffff,
        200,
        99999,
        hex_to_bytes("3333333333333333333333333333333333333333333333333333333333333333"),
        0xdeadbeefcafe1234ULL);

    auto expected_ref_hash = hex_to_bytes(
        "8548dabfd901cd1f1e8f12d78b68e51e5c59d677b0387697b22026ddafbee834");
    auto expected_gentx_hash = hex_to_bytes(
        "9a69d10066e41c1f219b315b577d0a3473461cde87d2f91b5e4e4350479ef02d");

    EXPECT_EQ(result.ref_hash, expected_ref_hash)
        << "ref_hash mismatch!\n  C++:    " << bytes_to_hex(result.ref_hash.data(), 32)
        << "\n  Python: " << bytes_to_hex(expected_ref_hash.data(), 32);

    EXPECT_EQ(result.gentx_hash, expected_gentx_hash)
        << "gentx_hash mismatch!\n  C++:    " << bytes_to_hex(result.gentx_hash.data(), 32)
        << "\n  Python: " << bytes_to_hex(expected_gentx_hash.data(), 32);

    // 3 outputs with different amounts, unambiguous sort
    // P2SH: 500000000, P2WPKH: 1000000000, P2PKH: 1499999999
    ASSERT_EQ(result.sorted_outputs.size(), 3u);
    EXPECT_EQ(result.sorted_outputs[0].second, 500000000u);
    EXPECT_EQ(result.sorted_outputs[1].second, 1000000000u);
    EXPECT_EQ(result.sorted_outputs[2].second, 1499999999u);
    EXPECT_EQ(result.donation_amount, 1u);
}

TEST(V36CrossImplRefHash, EdgeCase_GenesisShare)
{
    std::map<std::vector<unsigned char>, uint64_t> weights = {
        {make_p2pkh_script(std::vector<unsigned char>(20, 0xff)), 5000000},
    };

    std::vector<unsigned char> coinbase_script(
        reinterpret_cast<const unsigned char*>("genesis"),
        reinterpret_cast<const unsigned char*>("genesis") + 7);

    auto result = compute_test_vector(
        weights,
        1000000000ULL,
        {},  // prev_hash = None
        coinbase_script,
        0,
        std::vector<unsigned char>(20, 0xff),
        0,
        50,
        1700000002,
        0x1e0fffff,
        0x1e0fffff,
        0,
        0,
        {},  // far_share_hash = None
        0);

    auto expected_ref_hash = hex_to_bytes(
        "d274680286aefdf8274fa79adbbd77317d314689d41abd39d1a19b2566457d03");
    auto expected_gentx_hash = hex_to_bytes(
        "5997ca9ab42a29d58419bfcb42bf0d733490ceb0eb14fab268b9a9fb7eeb59a4");

    EXPECT_EQ(result.ref_hash, expected_ref_hash)
        << "ref_hash mismatch!\n  C++:    " << bytes_to_hex(result.ref_hash.data(), 32)
        << "\n  Python: " << bytes_to_hex(expected_ref_hash.data(), 32);

    EXPECT_EQ(result.gentx_hash, expected_gentx_hash)
        << "gentx_hash mismatch!\n  C++:    " << bytes_to_hex(result.gentx_hash.data(), 32)
        << "\n  Python: " << bytes_to_hex(expected_gentx_hash.data(), 32);

    ASSERT_EQ(result.sorted_outputs.size(), 1u);
    EXPECT_EQ(result.sorted_outputs[0].second, 999999999u);
    EXPECT_EQ(result.donation_amount, 1u);
}
