// SPDX-License-Identifier: AGPL-3.0-or-later
/// E2d (#738) -- pinned masternode-set checkpoint + forward-replay bridge KAT.
///
/// THE GAP THIS CLOSES: E2c gave the payout-bearing DMN set exactly one
/// cold-start source, dashd RPC `protx list valid true`. With no RPC the arm
/// printed "seed UNAVAILABLE" and every template kept routing to the dashd
/// fallback -- the last structurally daemon-dependent input on the daemonless
/// path. mn_checkpoint.hpp + mn_checkpoint_lane.hpp replace the RPC with a
/// release-pinned anchor replayed forward through the existing block-connect
/// ingest.
///
/// The anchor is a TRUST ANCHOR (see mn_checkpoint.hpp and
/// src/impl/dash/coin/checkpoints/README.md). This suite pins the parts that
/// are NOT trusted -- every local check, and every way the load can refuse.
///
/// Pinned here, network-free, against REAL captured testnet data:
///   * the committed fixture (test/dash_mn_checkpoint_testnet_1519543.inc,
///     produced by tools/dash/gen_mn_checkpoint.py from a real
///     `protx list valid true 1519543`) parses, and the resulting MNStates are
///     FIELD-IDENTICAL to what the E2c RPC parser produces from the same
///     dashd JSON -- the checkpoint seed and the RPC seed are the same set;
///   * fail-closed on every defect class: unpinned, bad magic, unknown key,
///     network mismatch, count mismatch, DIGEST mismatch, duplicate proTxHash,
///     duplicate collateral, missing scriptPayout, negative/garbage numbers;
///   * the bridge replays the REAL accepted blocks 1519544..1519546 onto the
///     anchored set and publishes at the tip with dashd-exact lastPaidHeights;
///   * chain-position mismatch, staleness over the bridge bound, a replay gap
///     and a replay payee-desync each fail closed TERMINALLY (never publish);
///   * end-to-end: the bridge's publish flows through the REAL leg-4 event
///     (mn_list_update -> wire_mn_list_ingest -> on_mn_list_update) and, with
///     a live tip, flips populated() so select_work() takes the EMBEDDED arm;
///   * NEGATIVE CONTROL: the same end-to-end wiring with a corrupted anchor
///     leaves populated() FALSE and select_work() on the fallback.
///
/// #895 note: NOTHING in this file is #ifdef-guarded. Every TEST() below is
/// unconditionally compiled and registered, so a green tick here means the
/// bodies actually ran.

#include <gtest/gtest.h>

#include <impl/dash/coin/mn_checkpoint.hpp>       // parse_mn_checkpoint (DUT)
#include <impl/dash/coin/mn_checkpoint_lane.hpp>  // MnCheckpointLane (DUT)
#include <impl/dash/coin/mn_seed.hpp>             // parse_protx_list_seed (E2c cross-check)
#include <impl/dash/coin/node_interface.hpp>
#include <impl/dash/coin/mn_list_ingest.hpp>      // wire_mn_list_ingest (leg 4)
#include <impl/dash/coin/tip_ingest.hpp>          // wire_tip_ingest (leg 2)
#include <impl/dash/coin/coin_state_maintainer.hpp>
#include <impl/dash/coin/node_coin_state.hpp>

#include <core/pack.hpp>
#include <core/uint256.hpp>

#include <nlohmann/json.hpp>

#include <algorithm>
#include <map>
#include <optional>
#include <string>
#include <vector>

using dash::coin::MNState;
using dash::coin::MnCheckpoint;
using dash::coin::MnCheckpointLane;
using dash::coin::mn_checkpoint_digest;
using dash::coin::parse_mn_checkpoint;

namespace {

constexpr uint8_t TESTNET_PUBKEY_VER = 140;
constexpr uint8_t TESTNET_P2SH_VER   = 19;

// ── The real captured anchor ───────────────────────────────────────────────
// Generated by tools/dash/gen_mn_checkpoint.py from dashd testnet
// `protx list valid true 1519543`. Same 6 masternodes the E2c suite's
// kProtxFront6At1519543 carries; blockhash is block 1519544's hashPrevBlock.
const char* const kRealCheckpoint1519543 =
#include "dash_mn_checkpoint_testnet_1519543.inc"
    ;

// Height + hash the anchor pins, restated so a fixture regeneration that
// silently moved either is caught here rather than in the bridge.
constexpr uint32_t kAnchorHeight = 1519543;
const char* const  kAnchorHash =
    "00000048ba417fd364d4220de99d16d6e17651a565b9b529417905b99b3a541b";

// Real accepted testnet blocks 1519544..1519546. Same bodies the E2c suite
// replays; kept here so this TU is self-contained (the two suites link into
// the same target, so a shared symbol would collide).
const char* const kBlockHex1519544 =
        "000000201b543a9bb905794129b5b965a55176e1d6169de90d22d464d37f41ba4800000095d95cbd42771d55f34c46009d29"
        "27f0684b22ca85667a2c0cb1626b0952138dfcc9606a4518511d0002780e0103000500010000000000000000000000000000"
        "000000000000000000000000000000000000ffffffff1303b82f170e2f5032506f6f6c2d74444153482fffffffff05056583"
        "03000000001976a9142629e1bbb4960da4c86226c876019e55c7c0346288ac2ed5fd0300000000016af80da7060000000019"
        "76a91464f2b2b84f62d68a2cd7f7f5fb2b5aa75ef716d788acb3e60800000000001976a91420cb5c22b1e4d5947e5c112c76"
        "96b51ad9af3c6188ac00000000000000002a6a282ad8f902c1ae2fece365590e4009eda31825336f273077a41697c43a54c0"
        "835f000000000000000000000000af0300b82f17007edd5fec21fd07f7b9d44b5029884ebc71d2e2812fd3029a76690045ce"
        "5c1647eb3ef20c2f89e9b8525f21e7064a47305b867ed642db1166faa9e0461fa0ee1d01b1a377ba4ad754bcc9bc00da609a"
        "d3482ad7acc7847039a0424300c35a2e99c4ea6f3659e987f86eb9559fb88a020bf404d9fe2c33e097e13647f55fbe0d6941"
        "e306f7bf206728634bff7e52a49d9e4b1b969017abd30c32ebc08d0c623cd98bb460a399f41e0000";

const char* const kBlockHex1519545 =
        "0000002013912532ebf7d4e655abf829f99d670de25fdb46d2cbcc6d567b6f294200000070151825df25a1f90162dfc2d978"
        "8b7dfdc8a690f9a61f0f8dd3f93e43bb5a2234ca606ac3fd4c1d00358c470103000500010000000000000000000000000000"
        "000000000000000000000000000000000000ffffffff1303b92f170e2f5032506f6f6c2d74444153482fffffffff050c6583"
        "03000000001976a9142629e1bbb4960da4c86226c876019e55c7c0346288ac2ed5fd0300000000016af80da7060000000019"
        "76a914c69a0bda7daaae481be8def95e5f347a1d00a4b488acace60800000000001976a91420cb5c22b1e4d5947e5c112c76"
        "96b51ad9af3c6188ac00000000000000002a6a2863ff5a8eb9b8e769435056d98f1831c46eaee642b6d17d0e9148d9b8385e"
        "434a000000000000000000000000af0300b92f17007edd5fec21fd07f7b9d44b5029884ebc71d2e2812fd3029a76690045ce"
        "5c1647eb3ef20c2f89e9b8525f21e7064a47305b867ed642db1166faa9e0461fa0ee1d0191d1a83a98f0b7b8cfb7f7ffca11"
        "6dd416960ec91ef8a0052ca0ac2ff7f0fcddf0c38f6894765f7ba11c6fa25385ca9d1498cd5d5581b9ca2603fd2d35a16dfe"
        "24cfd3dd49326da6d0d371cf3f97921c471ab5ad2eba487f680ced98063b26a9e235a19df41e0000";

const char* const kBlockHex1519546 =
        "00000020c9497b889ffb56364da48fd35c7673dc51df02c382bc2a3876b91e5138000000a2de65097455b4ae92412e868d9a"
        "c9d71c6f79322c1c10ddcab218e0bf004ff4e2ca606a76b04b1d000441980403000500010000000000000000000000000000"
        "000000000000000000000000000000000000ffffffff1303ba2f170e2f5032506f6f6c2d74444153482fffffffff05e16483"
        "03000000001976a9142629e1bbb4960da4c86226c876019e55c7c0346288ac2ed5fd0300000000016af80da7060000000019"
        "76a914c69a0bda7daaae481be8def95e5f347a1d00a4b488acd7e60800000000001976a91420cb5c22b1e4d5947e5c112c76"
        "96b51ad9af3c6188ac00000000000000002a6a2867e657696ff842bd354401663fb597a5edb52be7d029fdbdc710894c9776"
        "3512000000000000000000000000af0300ba2f17007edd5fec21fd07f7b9d44b5029884ebc71d2e2812fd3029a76690045ce"
        "5c1647eb3ef20c2f89e9b8525f21e7064a47305b867ed642db1166faa9e0461fa0ee1d01b836c031e91cc8b43129c7b1a93b"
        "2bf2e5ce31803a848318680d8144ba28379a8d769a313882306a5e3f4a10814466a511415c388a2ab98201c312e7ec291194"
        "31693053caad6df9d98a187588145cea3eb42b741eb3959abdf9138167fe993a100b9fa1f41e000003000600000000000000"
        "fd49010100ba2f170003000148f97725a2106d1fa6c4dc099de8acdc72b5b6b601751e65201adf9512000000320000000000"
        "0000320000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "000000000000000000000000000000000000000000000000000000000000000003000600000000000000fd55010100ba2f17"
        "0003000448f97725a2106d1fa6c4dc099de8acdc72b5b6b601751e65201adf95120000006400000000000000000000000000"
        "6400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "00000000000000000000000000000000000000000000000000000000000000000000000003000600000000000000fd430101"
        "00ba2f170003000648f97725a2106d1fa6c4dc099de8acdc72b5b6b601751e65201adf951200000019000000001900000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "00000000000000000000000000000000000000000000";

dash::coin::BlockType block_from_hex(const char* hex)
{
    std::string h(hex);
    std::vector<unsigned char> raw;
    raw.reserve(h.size() / 2);
    for (size_t i = 0; i + 1 < h.size(); i += 2)
        raw.push_back(static_cast<unsigned char>(
            std::stoul(h.substr(i, 2), nullptr, 16)));
    ::PackStream ps(raw);
    dash::coin::BlockType blk;
    ps >> blk;
    return blk;
}

// Re-digest a mutated payload so a test can isolate the field it is probing
// from the digest guard (otherwise EVERY mutation would merely prove the
// digest works).
std::string reseal(std::string payload)
{
    const size_t at = payload.find("digest ");
    if (at == std::string::npos) return payload;
    const size_t eol = payload.find('\n', at);
    std::string stripped = payload.substr(0, at) + payload.substr(eol + 1);
    const std::string d = mn_checkpoint_digest(stripped);
    return payload.substr(0, at) + "digest " + d + payload.substr(eol);
}

// Replace the first occurrence of `from` with `to`, then reseal.
std::string mutate(const std::string& payload, const std::string& from,
                   const std::string& to, bool reseal_it = true)
{
    std::string p = payload;
    const size_t at = p.find(from);
    EXPECT_NE(at, std::string::npos) << "mutation anchor not found: " << from;
    if (at == std::string::npos) return p;
    p.replace(at, from.size(), to);
    return reseal_it ? reseal(p) : p;
}

// ── A driveable harness around the lane ────────────────────────────────────
// Stands in for main_dash's seams: a synthetic header chain (height -> hash),
// a block store the request seam serves from, and a capture of what the lane
// publishes.
struct BridgeHarness {
    MnCheckpointLane lane;
    std::map<uint32_t, uint256>                    headers;   // height -> hash
    std::map<uint32_t, dash::coin::BlockType>      blocks;    // height -> body
    uint32_t tip{0};
    std::vector<uint32_t> requested;
    bool     published{false};
    uint32_t published_as_of{0};
    std::vector<std::pair<uint256, MNState>> published_set;
    // When set, request_block_fn delivers the block INLINE (the ordered-stream
    // behaviour of a real peer answering getdata on one TCP connection).
    bool auto_deliver{true};

    BridgeHarness()
    {
        lane.set_tip_height_fn([this] { return tip; });
        lane.set_header_hash_at_fn(
            [this](uint32_t h) -> std::optional<uint256> {
                auto it = headers.find(h);
                if (it == headers.end()) return std::nullopt;
                return it->second;
            });
        lane.set_publish_fn(
            [this](std::vector<std::pair<uint256, MNState>> set, uint32_t as_of) {
                published = true;
                published_as_of = as_of;
                published_set = std::move(set);
            });
        lane.set_request_block_fn([this](uint32_t h) {
            requested.push_back(h);
            if (!auto_deliver) return;
            auto it = blocks.find(h);
            if (it == blocks.end()) return;
            lane.on_block_connected(it->second, h);
        });
    }
};

MnCheckpoint good_checkpoint()
{
    auto cp = parse_mn_checkpoint(kRealCheckpoint1519543, "testnet");
    EXPECT_TRUE(cp.ok) << cp.error;
    return cp;
}

} // namespace

// ═══════════════════════════════════════════════════════════════════════════
// 1. The committed anchor parses, and says what it claims to say.
// ═══════════════════════════════════════════════════════════════════════════
TEST(DashMnCheckpoint, RealCapturedAnchorParses)
{
    auto cp = parse_mn_checkpoint(kRealCheckpoint1519543, "testnet");
    ASSERT_TRUE(cp.ok) << cp.error;
    EXPECT_FALSE(cp.unpinned);
    EXPECT_EQ(cp.network, "testnet");
    EXPECT_EQ(cp.height, kAnchorHeight);
    EXPECT_EQ(cp.blockhash.GetHex(), std::string(kAnchorHash));
    EXPECT_EQ(cp.entries.size(), 6u);
    EXPECT_FALSE(cp.source.empty()) << "provenance must be recorded in-file";
    EXPECT_FALSE(cp.generated.empty());
    // Every masternode carries a payee -- the whole point of the anchor.
    for (const auto& [h, mn] : cp.entries)
        EXPECT_FALSE(mn.scriptPayout.m_data.empty()) << h.GetHex();
}

// ═══════════════════════════════════════════════════════════════════════════
// 2. Checkpoint seed == RPC seed. The generator's field mapping is the same
//    mapping mn_seed.hpp makes from the same dashd JSON, so an operator who
//    switches between the two arms gets a byte-identical masternode set.
// ═══════════════════════════════════════════════════════════════════════════
TEST(DashMnCheckpoint, CheckpointSetIsFieldIdenticalToRpcSeed)
{
    // The SAME six masternodes as dashd reported them, reduced to the fields
    // the E2c parser consumes. (The full captured JSON lives in
    // test_dash_mn_seed.cpp; restating the payee-relevant subset here keeps the
    // two suites independent while still cross-checking the mapping.)
    const char* kJson = R"([
      {"type":"Regular","proTxHash":"dc2e02ac95ce4ccc9843c38de7bdaf32f2a1d5966c054127a3f4ca4f4bbd5991",
       "collateralHash":"4ee3ff5074723d995f4cb957a954587c6c637a42655ada8f4054037b28d1e7a8","collateralIndex":34,
       "operatorReward":0,"state":{"version":1,"registeredHeight":838365,"lastPaidHeight":1519459,
       "consecutivePayments":0,"PoSeRevivedHeight":1367840,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yVXDAM73Tg6A44Bm3qduXsMCYxzuqBCT48"}},
      {"type":"Evo","proTxHash":"9b653e767b978c10346d938c08dc8c5acd03c495f9d913e6fc652bfcae11a348",
       "collateralHash":"75fe9d8d90619576ef11deb8550d023366bf9d85e686dc6d5afba0aca8827e21","collateralIndex":2,
       "operatorReward":0,"state":{"version":2,"registeredHeight":1427623,"lastPaidHeight":1519460,
       "consecutivePayments":0,"PoSeRevivedHeight":1446613,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yeRZBWYfeNE4yVUHV4ZLs83Ppn9aMRH57A"}},
      {"type":"Evo","proTxHash":"91bbce94c34ebde0d099c0a2cb7635c0c31425ebabcec644f4f1a0854bfa605d",
       "collateralHash":"6ce8545e25d4f03aba1527062d9583ae01827c65b234bd979aca5954c6ae3a59","collateralIndex":30,
       "operatorReward":0,"state":{"version":2,"registeredHeight":850334,"lastPaidHeight":1519461,
       "consecutivePayments":0,"PoSeRevivedHeight":1368973,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yeRZBWYfeNE4yVUHV4ZLs83Ppn9aMRH57A"}},
      {"type":"Regular","proTxHash":"72ee70fa75262781a17d1eb69a6c3e97328208be98b59d5530164f31e481d3aa",
       "collateralHash":"4ee3ff5074723d995f4cb957a954587c6c637a42655ada8f4054037b28d1e7a8","collateralIndex":96,
       "operatorReward":0,"state":{"version":1,"registeredHeight":838365,"lastPaidHeight":1519462,
       "consecutivePayments":0,"PoSeRevivedHeight":1367330,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yVXDAM73Tg6A44Bm3qduXsMCYxzuqBCT48"}},
      {"type":"Regular","proTxHash":"c87218fb9d031f4926c22430c69b4edf1f0fb80c331c1a79e3b1b3873407c0ac",
       "collateralHash":"4ee3ff5074723d995f4cb957a954587c6c637a42655ada8f4054037b28d1e7a8","collateralIndex":62,
       "operatorReward":0,"state":{"version":1,"registeredHeight":838365,"lastPaidHeight":1519463,
       "consecutivePayments":0,"PoSeRevivedHeight":1367840,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yVXDAM73Tg6A44Bm3qduXsMCYxzuqBCT48"}},
      {"type":"Regular","proTxHash":"ecebeb952f56a61abaccd7bda7f4df5eccbd5f87a91bc4a8969535df1058158e",
       "collateralHash":"f329c4c9d194159e81597e50144ce41a40e2b40860c7813a85eabb0454700a3d","collateralIndex":1,
       "operatorReward":0,"state":{"version":2,"registeredHeight":1491043,"lastPaidHeight":1519464,
       "consecutivePayments":0,"PoSeRevivedHeight":1507780,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yjTpMw9buZfv4jNkf87AHpDj95YSAFuDiX"}}
    ])";

    dash::coin::MnSeedStats st;
    auto rpc_seed = dash::coin::parse_protx_list_seed(
        nlohmann::json::parse(kJson), TESTNET_PUBKEY_VER, TESTNET_P2SH_VER, &st);
    ASSERT_EQ(rpc_seed.size(), 6u);

    auto cp = good_checkpoint();
    ASSERT_EQ(cp.entries.size(), rpc_seed.size());

    std::map<uint256, MNState> from_ckpt(cp.entries.begin(), cp.entries.end());
    for (const auto& [h, rpc_mn] : rpc_seed) {
        auto it = from_ckpt.find(h);
        ASSERT_NE(it, from_ckpt.end())
            << "checkpoint is missing masternode " << h.GetHex();
        const MNState& ck = it->second;
        EXPECT_EQ(ck.scriptPayout.m_data, rpc_mn.scriptPayout.m_data)
            << "PAYEE MISMATCH for " << h.GetHex()
            << " -- the checkpoint would mint a different coinbase than the"
               " RPC seed";
        EXPECT_EQ(ck.nLastPaidHeight, rpc_mn.nLastPaidHeight);
        EXPECT_EQ(ck.nRegisteredHeight, rpc_mn.nRegisteredHeight);
        EXPECT_EQ(ck.nPoSeRevivedHeight, rpc_mn.nPoSeRevivedHeight);
        EXPECT_EQ(ck.nPoSeBanHeight, rpc_mn.nPoSeBanHeight);
        EXPECT_EQ(ck.nType, rpc_mn.nType);
        EXPECT_EQ(ck.nVersion, rpc_mn.nVersion);
        EXPECT_EQ(ck.isValid, rpc_mn.isValid);
        EXPECT_EQ(ck.collateralOutpoint.hash, rpc_mn.collateralOutpoint.hash);
        EXPECT_EQ(ck.collateralOutpoint.index, rpc_mn.collateralOutpoint.index);
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// 3. Fail-closed: every defect class refuses the WHOLE checkpoint.
// ═══════════════════════════════════════════════════════════════════════════
TEST(DashMnCheckpoint, UnpinnedPayloadIsReportedDistinctly)
{
    // What a fresh checkout ships: a comment-only .inc.
    auto cp = parse_mn_checkpoint("", "mainnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_TRUE(cp.unpinned) << "an absent anchor must not look like corruption";
    EXPECT_NE(cp.error.find("UNPINNED"), std::string::npos);

    auto cp2 = parse_mn_checkpoint("# nothing here\n\n# still nothing\n", "mainnet");
    EXPECT_FALSE(cp2.ok);
    EXPECT_TRUE(cp2.unpinned);
}

TEST(DashMnCheckpoint, DigestMismatchRefusesEverything)
{
    // Flip ONE masternode's lastPaidHeight without resealing: exactly the shape
    // of a hand edit or a half-applied merge.
    std::string tampered = mutate(kRealCheckpoint1519543,
                                  "1519459", "1519999", /*reseal_it=*/false);
    auto cp = parse_mn_checkpoint(tampered, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_FALSE(cp.unpinned);
    EXPECT_NE(cp.error.find("DIGEST MISMATCH"), std::string::npos) << cp.error;
    EXPECT_TRUE(cp.entries.empty()) << "no partial set may survive a refusal";
}

TEST(DashMnCheckpoint, NetworkMismatchRefuses)
{
    auto cp = parse_mn_checkpoint(kRealCheckpoint1519543, "mainnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("network mismatch"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, BadMagicRefuses)
{
    std::string p = mutate(kRealCheckpoint1519543,
                           "c2pool-dash-mn-checkpoint/1",
                           "c2pool-dash-mn-checkpoint/2");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("bad magic"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, UnknownKeyRefusesRatherThanIgnoring)
{
    // A future format could add a load-bearing key; silently skipping it would
    // load a set we do not actually understand.
    std::string p = mutate(kRealCheckpoint1519543,
                           "count 6", "quorumhint 42\ncount 6");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("unknown key"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, CountMismatchRefuses)
{
    std::string p = mutate(kRealCheckpoint1519543, "count 6", "count 5");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("count mismatch"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, MissingPayoutScriptRefuses)
{
    std::string p = mutate(
        kRealCheckpoint1519543,
        "76a91464f2b2b84f62d68a2cd7f7f5fb2b5aa75ef716d788ac", "-");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("scriptPayout"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, DuplicateProTxHashRefuses)
{
    // Duplicate the first mn line verbatim (and bump count so this test probes
    // the duplicate guard, not the count guard).
    std::string p(kRealCheckpoint1519543);
    const size_t at = p.find("mn 72ee70fa");
    ASSERT_NE(at, std::string::npos);
    const size_t eol = p.find('\n', at);
    const std::string line = p.substr(at, eol - at + 1);
    p.insert(eol + 1, line);
    p = mutate(p, "count 6", "count 7");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("duplicate proTxHash"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, NegativeAndGarbageNumbersRefuse)
{
    // strtoul would silently wrap "-1" to UINT32_MAX -- the exact sentinel bug
    // class that froze the projected payee. And "12abc" would parse as 12.
    for (const char* bad : {"-1", "12abc", "999999999999999999999", ""}) {
        std::string p = mutate(kRealCheckpoint1519543,
                               " 838365 1519462 ",
                               std::string(" ") + bad + " 1519462 ");
        auto cp = parse_mn_checkpoint(p, "testnet");
        EXPECT_FALSE(cp.ok) << "accepted registeredHeight '" << bad << "'";
        EXPECT_TRUE(cp.entries.empty());
    }
}

TEST(DashMnCheckpoint, ZeroBlockhashRefuses)
{
    std::string p = mutate(kRealCheckpoint1519543, kAnchorHash,
                           std::string(64, '0'));
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("all-zero"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, DigestRuleIgnoresCommentsAndBlankLines)
{
    // Comments must be free to add (the .inc header block is comments), so the
    // digest domain must exclude them -- but must NOT exclude anything else.
    std::string p = std::string("# a comment\n\n")
                  + kRealCheckpoint1519543 + "\n# trailing comment\n";
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_TRUE(cp.ok) << cp.error;
    EXPECT_EQ(cp.entries.size(), 6u);
}

// ═══════════════════════════════════════════════════════════════════════════
// 4. The bridge: real anchor + real blocks -> published set.
// ═══════════════════════════════════════════════════════════════════════════
TEST(DashMnCheckpointBridge, ReplaysRealBlocksAndPublishesAtTip)
{
    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.blocks[1519544] = block_from_hex(kBlockHex1519544);
    h.blocks[1519545] = block_from_hex(kBlockHex1519545);
    h.blocks[1519546] = block_from_hex(kBlockHex1519546);
    h.tip = 1519546;

    h.lane.arm(good_checkpoint());
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Waiting);

    h.lane.pump();

    ASSERT_TRUE(h.published) << "bridge status: " << h.lane.status();
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Published);
    EXPECT_EQ(h.published_as_of, 1519546u)
        << "the published snapshot must be labelled with the height it bridged"
           " to, or the maintainer's apply cursor starts wrong";
    EXPECT_EQ(h.published_set.size(), 6u);

    // dashd's actual payment schedule over those three blocks (the same
    // attribution the E2c suite pins against the RPC seed).
    std::map<uint256, MNState> out(h.published_set.begin(), h.published_set.end());
    EXPECT_EQ(out.at(uint256S("dc2e02ac95ce4ccc9843c38de7bdaf32f2a1d5966c05412"
                              "7a3f4ca4f4bbd5991")).nLastPaidHeight, 1519544u);
    EXPECT_EQ(out.at(uint256S("9b653e767b978c10346d938c08dc8c5acd03c495f9d913e"
                              "6fc652bfcae11a348")).nLastPaidHeight, 1519545u);
    EXPECT_EQ(out.at(uint256S("91bbce94c34ebde0d099c0a2cb7635c0c31425ebabcec64"
                              "4f4f1a0854bfa605d")).nLastPaidHeight, 1519546u);

    // The blocks were requested in ascending order from the cursor.
    ASSERT_FALSE(h.requested.empty());
    EXPECT_EQ(h.requested.front(), 1519544u);
    EXPECT_TRUE(std::is_sorted(h.requested.begin(), h.requested.end()));
}

TEST(DashMnCheckpointBridge, IgnoresLiveTipBlocksArrivingMidBridge)
{
    // The cold-start race: the new_block inv leg delivers a block at the CURRENT
    // tip while the bridge is still replaying history. Folding it would advance
    // a stale cursor -- the E4-soak bad-cb-payee shape.
    BridgeHarness h;
    h.auto_deliver = false;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.tip = 1519546;
    h.lane.arm(good_checkpoint());
    h.lane.pump();
    ASSERT_EQ(h.lane.state(), MnCheckpointLane::State::Bridging);

    // A far-future block arrives first. It must be ignored, NOT folded.
    h.lane.on_block_connected(block_from_hex(kBlockHex1519546), 1519546);
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Bridging)
        << "an out-of-order live block must not fail or advance the bridge";
    EXPECT_EQ(h.lane.cursor_height(), kAnchorHeight);
    EXPECT_FALSE(h.published);

    // Now the ordered replay proceeds normally.
    h.lane.on_block_connected(block_from_hex(kBlockHex1519544), 1519544);
    h.lane.on_block_connected(block_from_hex(kBlockHex1519545), 1519545);
    h.lane.on_block_connected(block_from_hex(kBlockHex1519546), 1519546);
    EXPECT_TRUE(h.published) << h.lane.status();
    EXPECT_EQ(h.published_as_of, 1519546u);
}

TEST(DashMnCheckpointBridge, ChainPositionMismatchFailsClosed)
{
    // The anchor names a block our PoW-validated header chain does not hold at
    // that height: wrong chain, wrong fork, or a fabricated anchor.
    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(
        "00000000000000000000000000000000000000000000000000000000deadbeef");
    h.tip = 1519546;
    h.lane.arm(good_checkpoint());
    h.lane.pump();

    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed);
    EXPECT_NE(h.lane.status().find("CHAIN-POSITION MISMATCH"), std::string::npos)
        << h.lane.status();
    EXPECT_FALSE(h.published);
    // Terminal: further drives must not resurrect it.
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.lane.pump();
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed);
    EXPECT_FALSE(h.published);
}

TEST(DashMnCheckpointBridge, StaleAnchorBeyondBridgeBoundFailsClosed)
{
    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.tip = kAnchorHeight + 5000;
    h.lane.set_max_bridge_blocks(100);
    h.lane.arm(good_checkpoint());
    h.lane.pump();

    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed);
    EXPECT_NE(h.lane.status().find("STALE"), std::string::npos) << h.lane.status();
    EXPECT_FALSE(h.published);
    EXPECT_TRUE(h.requested.empty())
        << "a refused anchor must not start pulling block bodies";
}

TEST(DashMnCheckpointBridge, ReplayGapFailsClosed)
{
    // Blocks skipped mid-replay: dashd advanced its payment queue at heights we
    // never folded, so ours is silently behind. Never publish.
    BridgeHarness h;
    h.auto_deliver = false;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.tip = 1519546;
    h.lane.arm(good_checkpoint());
    h.lane.pump();
    ASSERT_EQ(h.lane.state(), MnCheckpointLane::State::Bridging);

    h.lane.on_block_connected(block_from_hex(kBlockHex1519544), 1519544);
    EXPECT_EQ(h.lane.cursor_height(), 1519544u);
    // 1519545 never arrives; the lane is waiting for it, so 1519546 is simply
    // ignored and the bridge NEVER publishes.
    h.lane.on_block_connected(block_from_hex(kBlockHex1519546), 1519546);
    EXPECT_FALSE(h.published);
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Bridging);
    EXPECT_EQ(h.lane.cursor_height(), 1519544u);
}

TEST(DashMnCheckpointBridge, PayeeDesyncOnWrongAnchorFailsClosed)
{
    // THE anchor falsification test. Corrupt the anchor so it projects the
    // wrong payee, then replay a real block. The block's real coinbase does not
    // pay what we project -> the anchor is proven wrong -> terminal refusal.
    // This is what stops a bad trust anchor from ever reaching a template.
    //
    // 1519459 is dc2e02ac's lastPaidHeight, the LOWEST in the set, which is why
    // dashd paid it at 1519544. Pushing it to the top of the queue makes some
    // OTHER masternode our projected payee.
    std::string p = mutate(kRealCheckpoint1519543, " 838365 1519459 ",
                           " 838365 1519543 ");
    auto bad = parse_mn_checkpoint(p, "testnet");
    ASSERT_TRUE(bad.ok) << bad.error;  // structurally valid, semantically wrong

    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.blocks[1519544] = block_from_hex(kBlockHex1519544);
    h.tip = 1519544;
    h.lane.arm(bad);
    h.lane.pump();

    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << h.lane.status();
    EXPECT_NE(h.lane.status().find("PAYEE DESYNC"), std::string::npos)
        << h.lane.status();
    EXPECT_FALSE(h.published)
        << "a falsified anchor must NEVER reach the maintainer";
}

TEST(DashMnCheckpointBridge, RefusedCheckpointArmsTerminallyFailedClosed)
{
    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.tip = 1519546;
    h.lane.arm(parse_mn_checkpoint("", "mainnet"));   // UNPINNED
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed);
    h.lane.pump();
    EXPECT_FALSE(h.published);
    EXPECT_TRUE(h.requested.empty());
}

TEST(DashMnCheckpointBridge, WaitsQuietlyUntilHeadersReachTheAnchor)
{
    // Cold start: headers are still syncing. Not an error, and MUST NOT publish.
    BridgeHarness h;
    h.tip = 1000;
    h.lane.arm(good_checkpoint());
    h.lane.pump();
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Waiting);
    EXPECT_FALSE(h.published);
    EXPECT_TRUE(h.requested.empty());
}

// ═══════════════════════════════════════════════════════════════════════════
// 5. End-to-end through the REAL leg-4 event, plus the negative control.
// ═══════════════════════════════════════════════════════════════════════════
namespace {

// Mirrors main_dash's wiring: the lane publishes into Node::mn_list_update,
// leg 4 carries it to the maintainer, leg 2 supplies the tip.
struct E2eRig {
    dash::interfaces::Node                        node;
    dash::coin::NodeCoinState                     state;
    dash::coin::CoinStateMaintainer               maint{state};
    std::vector<std::shared_ptr<EventDisposable>> subs;
    BridgeHarness                                 h;

    E2eRig()
    {
        // The anti-mint latch main_dash enables for the embedded arm.
        maint.set_require_seeded_mn_set(true);
        subs.push_back(c2pool::dash::wire_mn_list_ingest(node, maint));
        subs.push_back(c2pool::dash::wire_tip_ingest(node, maint));
        h.lane.set_publish_fn(
            [this](std::vector<std::pair<uint256, MNState>> set, uint32_t as_of) {
                dash::interfaces::MnListUpdate up;
                up.mnstates     = std::move(set);
                up.as_of_height = as_of;
                node.mn_list_update.happened(up);
            });
        h.headers[kAnchorHeight] = uint256S(kAnchorHash);
        h.blocks[1519544] = block_from_hex(kBlockHex1519544);
        h.blocks[1519545] = block_from_hex(kBlockHex1519545);
        h.blocks[1519546] = block_from_hex(kBlockHex1519546);
        h.tip = 1519546;
    }

    void fire_tip()
    {
        dash::interfaces::TipAdvance ta;
        ta.prev_height           = 1519546;
        ta.prev_hash             = uint256S(kAnchorHash);
        ta.bits_for_next         = 0x1d00ffff;
        ta.mtp_at_tip            = 1751000000;
        ta.address_version       = TESTNET_PUBKEY_VER;
        ta.address_p2sh_version  = TESTNET_P2SH_VER;
        node.new_tip.happened(ta);
    }
};

} // namespace

TEST(DashMnCheckpointE2e, BridgePublishFlipsPopulatedThroughTheRealLeg4Event)
{
    E2eRig r;
    EXPECT_FALSE(r.state.populated()) << "cold start must not be populated";

    r.h.lane.arm(good_checkpoint());
    r.h.lane.pump();
    ASSERT_EQ(r.h.lane.state(), MnCheckpointLane::State::Published)
        << r.h.lane.status();

    r.fire_tip();

    EXPECT_TRUE(r.state.populated())
        << "the bridged masternode set + a live tip must flip the embedded arm";
}

// NEGATIVE CONTROL. Identical wiring; the ONLY difference is a corrupted
// anchor. If this ever passes populated()==true, the fail-closed path is
// decorative.
TEST(DashMnCheckpointE2e, NegativeControlCorruptAnchorLeavesArmUnpopulated)
{
    E2eRig r;
    std::string tampered = mutate(kRealCheckpoint1519543,
                                  "1519459", "1519999", /*reseal_it=*/false);
    auto bad = parse_mn_checkpoint(tampered, "testnet");
    ASSERT_FALSE(bad.ok);

    r.h.lane.arm(bad);
    r.h.lane.pump();
    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed);

    r.fire_tip();

    EXPECT_FALSE(r.state.populated())
        << "a refused anchor must leave the embedded arm unarmed -- templates"
           " keep routing to the dashd fallback";
}

// Second negative control, one layer down: prove the anti-mint latch main_dash
// enables actually blocks the "one accidental ProRegTx arms the queue" path.
TEST(DashMnCheckpointE2e, NegativeControlAntiMintLatchBlocksUnseededArming)
{
    dash::coin::NodeCoinState state;
    dash::coin::CoinStateMaintainer maint{state};
    maint.set_require_seeded_mn_set(true);

    // A non-empty masternode set with NO height stamp: what an unauthoritative
    // source (or a block-connect registration) would produce.
    auto cp = good_checkpoint();
    maint.on_mn_list_update(cp.entries, /*as_of_height=*/0);

    auto fire_tip = [&maint] {
        maint.on_new_tip(/*prev_height=*/1519546, uint256S(kAnchorHash),
                         /*bits_for_next=*/0x1d00ffff,
                         /*mtp_at_tip=*/1751000000,
                         TESTNET_PUBKEY_VER, TESTNET_P2SH_VER);
    };
    fire_tip();

    EXPECT_FALSE(state.populated())
        << "an unheighted masternode set must never arm the embedded arm";

    // Positive control on the same object: the SAME set WITH its height arms it.
    maint.on_mn_list_update(cp.entries, kAnchorHeight);
    fire_tip();
    EXPECT_TRUE(state.populated())
        << "a height-stamped authoritative snapshot must still arm normally";
}
