// SPDX-License-Identifier: AGPL-3.0-or-later
/// E2d (#738) -- pinned masternode-set checkpoint + forward-replay bridge KAT.
///
/// THE GAP THIS CLOSES: E2c gave the payout-bearing DMN set exactly one
/// cold-start source, dashd RPC `protx list valid true`. With no RPC the arm
/// printed "seed UNAVAILABLE" and every template kept routing to the dashd
/// fallback -- the last structurally daemon-dependent input on the daemonless
/// path. mn_checkpoint.hpp + mn_checkpoint_lane.hpp replace the RPC with a
/// release-pinned anchor replayed forward through the existing block-connect
/// ingest.
///
/// The anchor is a TRUST ANCHOR (see mn_checkpoint.hpp and
/// src/impl/dash/coin/checkpoints/README.md). This suite pins the parts that
/// are NOT trusted -- every local check, and every way the load can refuse.
///
/// Pinned here, network-free, against REAL captured testnet data:
///   * the committed fixture (test/dash_mn_checkpoint_testnet_1519543.inc,
///     produced by tools/dash/gen_mn_checkpoint.py from a real
///     `protx list valid true 1519543`) parses, and the resulting MNStates are
///     FIELD-IDENTICAL to what the E2c RPC parser produces from the same
///     dashd JSON -- the checkpoint seed and the RPC seed are the same set;
///   * fail-closed on every defect class: unpinned, bad magic, unknown key,
///     network mismatch, count mismatch, DIGEST mismatch, duplicate proTxHash,
///     duplicate collateral, missing scriptPayout, negative/garbage numbers;
///   * the bridge replays the REAL accepted blocks 1519544..1519546 onto the
///     anchored set and publishes at the tip with dashd-exact lastPaidHeights;
///   * chain-position mismatch, staleness over the bridge bound, a replay gap
///     and a replay payee-desync each fail closed TERMINALLY (never publish);
///   * end-to-end: the bridge's publish flows through the REAL leg-4 event
///     (mn_list_update -> wire_mn_list_ingest -> on_mn_list_update) and, with
///     a live tip, flips populated() so select_work() takes the EMBEDDED arm;
///   * NEGATIVE CONTROL: the same end-to-end wiring with a corrupted anchor
///     leaves populated() FALSE and select_work() on the fallback.
///
/// #895 note: NOTHING in this file is #ifdef-guarded. Every TEST() below is
/// unconditionally compiled and registered, so a green tick here means the
/// bodies actually ran.

#include <gtest/gtest.h>

#include <impl/dash/coin/mn_checkpoint.hpp>       // parse_mn_checkpoint (DUT)
#include <impl/dash/coin/mn_checkpoint_lane.hpp>  // MnCheckpointLane (DUT)
#include <impl/dash/coin/vendor/providertx.hpp>   // CProUpServTx (revival leg)
#include <impl/dash/coin/vendor/simplifiedmns.hpp>// CSimplifiedMNList (attestation source)
#include <impl/dash/coin/mn_seed.hpp>             // parse_protx_list_seed (E2c cross-check)
#include <impl/dash/coin/node_interface.hpp>
#include <impl/dash/coin/mn_list_ingest.hpp>      // wire_mn_list_ingest (leg 4)
#include <impl/dash/coin/tip_ingest.hpp>          // wire_tip_ingest (leg 2)
#include <impl/dash/coin/coin_state_maintainer.hpp>
#include <impl/dash/coin/node_coin_state.hpp>

#include <core/hash.hpp>
#include <core/pack.hpp>
#include <core/uint256.hpp>

#include <nlohmann/json.hpp>

#include <algorithm>
#include <functional>
#include <map>
#include <span>
#include <optional>
#include <string>
#include <utility>
#include <vector>

using dash::coin::MNState;
using dash::coin::MnCheckpoint;
using dash::coin::MnCheckpointLane;
using dash::coin::mn_checkpoint_digest;
using dash::coin::parse_mn_checkpoint;

namespace {

constexpr uint8_t TESTNET_PUBKEY_VER = 140;
constexpr uint8_t TESTNET_P2SH_VER   = 19;

// ── The real captured anchor ───────────────────────────────────────────────
// Generated by tools/dash/gen_mn_checkpoint.py from dashd testnet
// `protx list valid true 1519543`. Same 6 masternodes the E2c suite's
// kProtxFront6At1519543 carries; blockhash is block 1519544's hashPrevBlock.
const char* const kRealCheckpoint1519543 =
#include "dash_mn_checkpoint_testnet_1519543.inc"
    ;

// Height + hash the anchor pins, restated so a fixture regeneration that
// silently moved either is caught here rather than in the bridge.
constexpr uint32_t kAnchorHeight = 1519543;
const char* const  kAnchorHash =
    "00000048ba417fd364d4220de99d16d6e17651a565b9b529417905b99b3a541b";

// Real accepted testnet blocks 1519544..1519546. Same bodies the E2c suite
// replays; kept here so this TU is self-contained (the two suites link into
// the same target, so a shared symbol would collide).
const char* const kBlockHex1519544 =
        "000000201b543a9bb905794129b5b965a55176e1d6169de90d22d464d37f41ba4800000095d95cbd42771d55f34c46009d29"
        "27f0684b22ca85667a2c0cb1626b0952138dfcc9606a4518511d0002780e0103000500010000000000000000000000000000"
        "000000000000000000000000000000000000ffffffff1303b82f170e2f5032506f6f6c2d74444153482fffffffff05056583"
        "03000000001976a9142629e1bbb4960da4c86226c876019e55c7c0346288ac2ed5fd0300000000016af80da7060000000019"
        "76a91464f2b2b84f62d68a2cd7f7f5fb2b5aa75ef716d788acb3e60800000000001976a91420cb5c22b1e4d5947e5c112c76"
        "96b51ad9af3c6188ac00000000000000002a6a282ad8f902c1ae2fece365590e4009eda31825336f273077a41697c43a54c0"
        "835f000000000000000000000000af0300b82f17007edd5fec21fd07f7b9d44b5029884ebc71d2e2812fd3029a76690045ce"
        "5c1647eb3ef20c2f89e9b8525f21e7064a47305b867ed642db1166faa9e0461fa0ee1d01b1a377ba4ad754bcc9bc00da609a"
        "d3482ad7acc7847039a0424300c35a2e99c4ea6f3659e987f86eb9559fb88a020bf404d9fe2c33e097e13647f55fbe0d6941"
        "e306f7bf206728634bff7e52a49d9e4b1b969017abd30c32ebc08d0c623cd98bb460a399f41e0000";

const char* const kBlockHex1519545 =
        "0000002013912532ebf7d4e655abf829f99d670de25fdb46d2cbcc6d567b6f294200000070151825df25a1f90162dfc2d978"
        "8b7dfdc8a690f9a61f0f8dd3f93e43bb5a2234ca606ac3fd4c1d00358c470103000500010000000000000000000000000000"
        "000000000000000000000000000000000000ffffffff1303b92f170e2f5032506f6f6c2d74444153482fffffffff050c6583"
        "03000000001976a9142629e1bbb4960da4c86226c876019e55c7c0346288ac2ed5fd0300000000016af80da7060000000019"
        "76a914c69a0bda7daaae481be8def95e5f347a1d00a4b488acace60800000000001976a91420cb5c22b1e4d5947e5c112c76"
        "96b51ad9af3c6188ac00000000000000002a6a2863ff5a8eb9b8e769435056d98f1831c46eaee642b6d17d0e9148d9b8385e"
        "434a000000000000000000000000af0300b92f17007edd5fec21fd07f7b9d44b5029884ebc71d2e2812fd3029a76690045ce"
        "5c1647eb3ef20c2f89e9b8525f21e7064a47305b867ed642db1166faa9e0461fa0ee1d0191d1a83a98f0b7b8cfb7f7ffca11"
        "6dd416960ec91ef8a0052ca0ac2ff7f0fcddf0c38f6894765f7ba11c6fa25385ca9d1498cd5d5581b9ca2603fd2d35a16dfe"
        "24cfd3dd49326da6d0d371cf3f97921c471ab5ad2eba487f680ced98063b26a9e235a19df41e0000";

const char* const kBlockHex1519546 =
        "00000020c9497b889ffb56364da48fd35c7673dc51df02c382bc2a3876b91e5138000000a2de65097455b4ae92412e868d9a"
        "c9d71c6f79322c1c10ddcab218e0bf004ff4e2ca606a76b04b1d000441980403000500010000000000000000000000000000"
        "000000000000000000000000000000000000ffffffff1303ba2f170e2f5032506f6f6c2d74444153482fffffffff05e16483"
        "03000000001976a9142629e1bbb4960da4c86226c876019e55c7c0346288ac2ed5fd0300000000016af80da7060000000019"
        "76a914c69a0bda7daaae481be8def95e5f347a1d00a4b488acd7e60800000000001976a91420cb5c22b1e4d5947e5c112c76"
        "96b51ad9af3c6188ac00000000000000002a6a2867e657696ff842bd354401663fb597a5edb52be7d029fdbdc710894c9776"
        "3512000000000000000000000000af0300ba2f17007edd5fec21fd07f7b9d44b5029884ebc71d2e2812fd3029a76690045ce"
        "5c1647eb3ef20c2f89e9b8525f21e7064a47305b867ed642db1166faa9e0461fa0ee1d01b836c031e91cc8b43129c7b1a93b"
        "2bf2e5ce31803a848318680d8144ba28379a8d769a313882306a5e3f4a10814466a511415c388a2ab98201c312e7ec291194"
        "31693053caad6df9d98a187588145cea3eb42b741eb3959abdf9138167fe993a100b9fa1f41e000003000600000000000000"
        "fd49010100ba2f170003000148f97725a2106d1fa6c4dc099de8acdc72b5b6b601751e65201adf9512000000320000000000"
        "0000320000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "000000000000000000000000000000000000000000000000000000000000000003000600000000000000fd55010100ba2f17"
        "0003000448f97725a2106d1fa6c4dc099de8acdc72b5b6b601751e65201adf95120000006400000000000000000000000000"
        "6400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "00000000000000000000000000000000000000000000000000000000000000000000000003000600000000000000fd430101"
        "00ba2f170003000648f97725a2106d1fa6c4dc099de8acdc72b5b6b601751e65201adf951200000019000000001900000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        "00000000000000000000000000000000000000000000";

dash::coin::BlockType block_from_hex(const char* hex)
{
    std::string h(hex);
    std::vector<unsigned char> raw;
    raw.reserve(h.size() / 2);
    for (size_t i = 0; i + 1 < h.size(); i += 2)
        raw.push_back(static_cast<unsigned char>(
            std::stoul(h.substr(i, 2), nullptr, 16)));
    ::PackStream ps(raw);
    dash::coin::BlockType blk;
    ps >> blk;
    return blk;
}

// Re-digest a mutated payload so a test can isolate the field it is probing
// from the digest guard (otherwise EVERY mutation would merely prove the
// digest works).
std::string reseal(std::string payload)
{
    const size_t at = payload.find("digest ");
    if (at == std::string::npos) return payload;
    const size_t eol = payload.find('\n', at);
    std::string stripped = payload.substr(0, at) + payload.substr(eol + 1);
    const std::string d = mn_checkpoint_digest(stripped);
    return payload.substr(0, at) + "digest " + d + payload.substr(eol);
}

// Replace the first occurrence of `from` with `to`, then reseal.
std::string mutate(const std::string& payload, const std::string& from,
                   const std::string& to, bool reseal_it = true)
{
    std::string p = payload;
    const size_t at = p.find(from);
    EXPECT_NE(at, std::string::npos) << "mutation anchor not found: " << from;
    if (at == std::string::npos) return p;
    p.replace(at, from.size(), to);
    return reseal_it ? reseal(p) : p;
}

// ── A driveable harness around the lane ────────────────────────────────────
// Stands in for main_dash's seams: a synthetic header chain (height -> hash),
// a block store the request seam serves from, and a capture of what the lane
// publishes.
struct BridgeHarness {
    MnCheckpointLane lane;
    std::map<uint32_t, uint256>                    headers;   // height -> hash
    std::map<uint32_t, dash::coin::BlockType>      blocks;    // height -> body
    uint32_t tip{0};
    std::vector<uint32_t> requested;
    bool     published{false};
    uint32_t published_as_of{0};
    std::vector<std::pair<uint256, MNState>> published_set;
    // When set, request_block_fn delivers the block INLINE (the ordered-stream
    // behaviour of a real peer answering getdata on one TCP connection).
    bool auto_deliver{true};

    BridgeHarness()
    {
        lane.set_tip_height_fn([this] { return tip; });
        lane.set_header_hash_at_fn(
            [this](uint32_t h) -> std::optional<uint256> {
                auto it = headers.find(h);
                if (it == headers.end()) return std::nullopt;
                return it->second;
            });
        lane.set_publish_fn(
            [this](std::vector<std::pair<uint256, MNState>> set, uint32_t as_of) {
                published = true;
                published_as_of = as_of;
                published_set = std::move(set);
            });
        lane.set_request_block_fn([this](uint32_t h) {
            requested.push_back(h);
            if (!auto_deliver) return;
            auto it = blocks.find(h);
            if (it == blocks.end()) return;
            lane.on_block_connected(it->second, h);
        });
    }
};

MnCheckpoint good_checkpoint()
{
    auto cp = parse_mn_checkpoint(kRealCheckpoint1519543, "testnet");
    EXPECT_TRUE(cp.ok) << cp.error;
    return cp;
}

} // namespace

// ═══════════════════════════════════════════════════════════════════════════
// 1. The committed anchor parses, and says what it claims to say.
// ═══════════════════════════════════════════════════════════════════════════
TEST(DashMnCheckpoint, RealCapturedAnchorParses)
{
    auto cp = parse_mn_checkpoint(kRealCheckpoint1519543, "testnet");
    ASSERT_TRUE(cp.ok) << cp.error;
    EXPECT_FALSE(cp.unpinned);
    EXPECT_EQ(cp.network, "testnet");
    EXPECT_EQ(cp.height, kAnchorHeight);
    EXPECT_EQ(cp.blockhash.GetHex(), std::string(kAnchorHash));
    EXPECT_EQ(cp.entries.size(), 6u);
    EXPECT_FALSE(cp.source.empty()) << "provenance must be recorded in-file";
    EXPECT_FALSE(cp.generated.empty());
    // Every masternode carries a payee -- the whole point of the anchor.
    for (const auto& [h, mn] : cp.entries)
        EXPECT_FALSE(mn.scriptPayout.m_data.empty()) << h.GetHex();
}

// ═══════════════════════════════════════════════════════════════════════════
// 2. Checkpoint seed == RPC seed. The generator's field mapping is the same
//    mapping mn_seed.hpp makes from the same dashd JSON, so an operator who
//    switches between the two arms gets a byte-identical masternode set.
// ═══════════════════════════════════════════════════════════════════════════
TEST(DashMnCheckpoint, CheckpointSetIsFieldIdenticalToRpcSeed)
{
    // The SAME six masternodes as dashd reported them, reduced to the fields
    // the E2c parser consumes. (The full captured JSON lives in
    // test_dash_mn_seed.cpp; restating the payee-relevant subset here keeps the
    // two suites independent while still cross-checking the mapping.)
    const char* kJson = R"([
      {"type":"Regular","proTxHash":"dc2e02ac95ce4ccc9843c38de7bdaf32f2a1d5966c054127a3f4ca4f4bbd5991",
       "collateralHash":"4ee3ff5074723d995f4cb957a954587c6c637a42655ada8f4054037b28d1e7a8","collateralIndex":34,
       "operatorReward":0,"state":{"version":1,"registeredHeight":838365,"lastPaidHeight":1519459,
       "consecutivePayments":0,"PoSeRevivedHeight":1367840,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yVXDAM73Tg6A44Bm3qduXsMCYxzuqBCT48"}},
      {"type":"Evo","proTxHash":"9b653e767b978c10346d938c08dc8c5acd03c495f9d913e6fc652bfcae11a348",
       "collateralHash":"75fe9d8d90619576ef11deb8550d023366bf9d85e686dc6d5afba0aca8827e21","collateralIndex":2,
       "operatorReward":0,"state":{"version":2,"registeredHeight":1427623,"lastPaidHeight":1519460,
       "consecutivePayments":0,"PoSeRevivedHeight":1446613,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yeRZBWYfeNE4yVUHV4ZLs83Ppn9aMRH57A"}},
      {"type":"Evo","proTxHash":"91bbce94c34ebde0d099c0a2cb7635c0c31425ebabcec644f4f1a0854bfa605d",
       "collateralHash":"6ce8545e25d4f03aba1527062d9583ae01827c65b234bd979aca5954c6ae3a59","collateralIndex":30,
       "operatorReward":0,"state":{"version":2,"registeredHeight":850334,"lastPaidHeight":1519461,
       "consecutivePayments":0,"PoSeRevivedHeight":1368973,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yeRZBWYfeNE4yVUHV4ZLs83Ppn9aMRH57A"}},
      {"type":"Regular","proTxHash":"72ee70fa75262781a17d1eb69a6c3e97328208be98b59d5530164f31e481d3aa",
       "collateralHash":"4ee3ff5074723d995f4cb957a954587c6c637a42655ada8f4054037b28d1e7a8","collateralIndex":96,
       "operatorReward":0,"state":{"version":1,"registeredHeight":838365,"lastPaidHeight":1519462,
       "consecutivePayments":0,"PoSeRevivedHeight":1367330,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yVXDAM73Tg6A44Bm3qduXsMCYxzuqBCT48"}},
      {"type":"Regular","proTxHash":"c87218fb9d031f4926c22430c69b4edf1f0fb80c331c1a79e3b1b3873407c0ac",
       "collateralHash":"4ee3ff5074723d995f4cb957a954587c6c637a42655ada8f4054037b28d1e7a8","collateralIndex":62,
       "operatorReward":0,"state":{"version":1,"registeredHeight":838365,"lastPaidHeight":1519463,
       "consecutivePayments":0,"PoSeRevivedHeight":1367840,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yVXDAM73Tg6A44Bm3qduXsMCYxzuqBCT48"}},
      {"type":"Regular","proTxHash":"ecebeb952f56a61abaccd7bda7f4df5eccbd5f87a91bc4a8969535df1058158e",
       "collateralHash":"f329c4c9d194159e81597e50144ce41a40e2b40860c7813a85eabb0454700a3d","collateralIndex":1,
       "operatorReward":0,"state":{"version":2,"registeredHeight":1491043,"lastPaidHeight":1519464,
       "consecutivePayments":0,"PoSeRevivedHeight":1507780,"PoSeBanHeight":-1,"revocationReason":0,
       "payoutAddress":"yjTpMw9buZfv4jNkf87AHpDj95YSAFuDiX"}}
    ])";

    dash::coin::MnSeedStats st;
    auto rpc_seed = dash::coin::parse_protx_list_seed(
        nlohmann::json::parse(kJson), TESTNET_PUBKEY_VER, TESTNET_P2SH_VER, &st);
    ASSERT_EQ(rpc_seed.size(), 6u);

    auto cp = good_checkpoint();
    ASSERT_EQ(cp.entries.size(), rpc_seed.size());

    std::map<uint256, MNState> from_ckpt(cp.entries.begin(), cp.entries.end());
    for (const auto& [h, rpc_mn] : rpc_seed) {
        auto it = from_ckpt.find(h);
        ASSERT_NE(it, from_ckpt.end())
            << "checkpoint is missing masternode " << h.GetHex();
        const MNState& ck = it->second;
        EXPECT_EQ(ck.scriptPayout.m_data, rpc_mn.scriptPayout.m_data)
            << "PAYEE MISMATCH for " << h.GetHex()
            << " -- the checkpoint would mint a different coinbase than the"
               " RPC seed";
        EXPECT_EQ(ck.nLastPaidHeight, rpc_mn.nLastPaidHeight);
        EXPECT_EQ(ck.nRegisteredHeight, rpc_mn.nRegisteredHeight);
        EXPECT_EQ(ck.nPoSeRevivedHeight, rpc_mn.nPoSeRevivedHeight);
        EXPECT_EQ(ck.nPoSeBanHeight, rpc_mn.nPoSeBanHeight);
        EXPECT_EQ(ck.nType, rpc_mn.nType);
        EXPECT_EQ(ck.nVersion, rpc_mn.nVersion);
        EXPECT_EQ(ck.isValid, rpc_mn.isValid);
        EXPECT_EQ(ck.collateralOutpoint.hash, rpc_mn.collateralOutpoint.hash);
        EXPECT_EQ(ck.collateralOutpoint.index, rpc_mn.collateralOutpoint.index);
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// 3. Fail-closed: every defect class refuses the WHOLE checkpoint.
// ═══════════════════════════════════════════════════════════════════════════
TEST(DashMnCheckpoint, UnpinnedPayloadIsReportedDistinctly)
{
    // What a fresh checkout ships: a comment-only .inc.
    auto cp = parse_mn_checkpoint("", "mainnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_TRUE(cp.unpinned) << "an absent anchor must not look like corruption";
    EXPECT_NE(cp.error.find("UNPINNED"), std::string::npos);

    auto cp2 = parse_mn_checkpoint("# nothing here\n\n# still nothing\n", "mainnet");
    EXPECT_FALSE(cp2.ok);
    EXPECT_TRUE(cp2.unpinned);
}

TEST(DashMnCheckpoint, DigestMismatchRefusesEverything)
{
    // Flip ONE masternode's lastPaidHeight without resealing: exactly the shape
    // of a hand edit or a half-applied merge.
    std::string tampered = mutate(kRealCheckpoint1519543,
                                  "1519459", "1519999", /*reseal_it=*/false);
    auto cp = parse_mn_checkpoint(tampered, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_FALSE(cp.unpinned);
    EXPECT_NE(cp.error.find("DIGEST MISMATCH"), std::string::npos) << cp.error;
    EXPECT_TRUE(cp.entries.empty()) << "no partial set may survive a refusal";
}

TEST(DashMnCheckpoint, NetworkMismatchRefuses)
{
    auto cp = parse_mn_checkpoint(kRealCheckpoint1519543, "mainnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("network mismatch"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, BadMagicRefuses)
{
    std::string p = mutate(kRealCheckpoint1519543,
                           "c2pool-dash-mn-checkpoint/1",
                           "c2pool-dash-mn-checkpoint/2");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("bad magic"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, UnknownKeyRefusesRatherThanIgnoring)
{
    // A future format could add a load-bearing key; silently skipping it would
    // load a set we do not actually understand.
    std::string p = mutate(kRealCheckpoint1519543,
                           "count 6", "quorumhint 42\ncount 6");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("unknown key"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, CountMismatchRefuses)
{
    std::string p = mutate(kRealCheckpoint1519543, "count 6", "count 5");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("count mismatch"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, MissingPayoutScriptRefuses)
{
    std::string p = mutate(
        kRealCheckpoint1519543,
        "76a91464f2b2b84f62d68a2cd7f7f5fb2b5aa75ef716d788ac", "-");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("scriptPayout"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, DuplicateProTxHashRefuses)
{
    // Duplicate the first mn line verbatim (and bump count so this test probes
    // the duplicate guard, not the count guard).
    std::string p(kRealCheckpoint1519543);
    const size_t at = p.find("mn 72ee70fa");
    ASSERT_NE(at, std::string::npos);
    const size_t eol = p.find('\n', at);
    const std::string line = p.substr(at, eol - at + 1);
    p.insert(eol + 1, line);
    p = mutate(p, "count 6", "count 7");
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("duplicate proTxHash"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, NegativeAndGarbageNumbersRefuse)
{
    // strtoul would silently wrap "-1" to UINT32_MAX -- the exact sentinel bug
    // class that froze the projected payee. And "12abc" would parse as 12.
    for (const char* bad : {"-1", "12abc", "999999999999999999999", ""}) {
        std::string p = mutate(kRealCheckpoint1519543,
                               " 838365 1519462 ",
                               std::string(" ") + bad + " 1519462 ");
        auto cp = parse_mn_checkpoint(p, "testnet");
        EXPECT_FALSE(cp.ok) << "accepted registeredHeight '" << bad << "'";
        EXPECT_TRUE(cp.entries.empty());
    }
}

TEST(DashMnCheckpoint, ZeroBlockhashRefuses)
{
    std::string p = mutate(kRealCheckpoint1519543, kAnchorHash,
                           std::string(64, '0'));
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_FALSE(cp.ok);
    EXPECT_NE(cp.error.find("all-zero"), std::string::npos) << cp.error;
}

TEST(DashMnCheckpoint, DigestRuleIgnoresCommentsAndBlankLines)
{
    // Comments must be free to add (the .inc header block is comments), so the
    // digest domain must exclude them -- but must NOT exclude anything else.
    std::string p = std::string("# a comment\n\n")
                  + kRealCheckpoint1519543 + "\n# trailing comment\n";
    auto cp = parse_mn_checkpoint(p, "testnet");
    EXPECT_TRUE(cp.ok) << cp.error;
    EXPECT_EQ(cp.entries.size(), 6u);
}

// ═══════════════════════════════════════════════════════════════════════════
// 4. The bridge: real anchor + real blocks -> published set.
// ═══════════════════════════════════════════════════════════════════════════
TEST(DashMnCheckpointBridge, ReplaysRealBlocksAndPublishesAtTip)
{
    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.blocks[1519544] = block_from_hex(kBlockHex1519544);
    h.blocks[1519545] = block_from_hex(kBlockHex1519545);
    h.blocks[1519546] = block_from_hex(kBlockHex1519546);
    h.tip = 1519546;

    h.lane.arm(good_checkpoint());
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Waiting);

    h.lane.pump();

    ASSERT_TRUE(h.published) << "bridge status: " << h.lane.status();
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Published);
    EXPECT_EQ(h.published_as_of, 1519546u)
        << "the published snapshot must be labelled with the height it bridged"
           " to, or the maintainer's apply cursor starts wrong";
    EXPECT_EQ(h.published_set.size(), 6u);

    // dashd's actual payment schedule over those three blocks (the same
    // attribution the E2c suite pins against the RPC seed).
    std::map<uint256, MNState> out(h.published_set.begin(), h.published_set.end());
    EXPECT_EQ(out.at(uint256S("dc2e02ac95ce4ccc9843c38de7bdaf32f2a1d5966c05412"
                              "7a3f4ca4f4bbd5991")).nLastPaidHeight, 1519544u);
    EXPECT_EQ(out.at(uint256S("9b653e767b978c10346d938c08dc8c5acd03c495f9d913e"
                              "6fc652bfcae11a348")).nLastPaidHeight, 1519545u);
    EXPECT_EQ(out.at(uint256S("91bbce94c34ebde0d099c0a2cb7635c0c31425ebabcec64"
                              "4f4f1a0854bfa605d")).nLastPaidHeight, 1519546u);

    // The blocks were requested in ascending order from the cursor.
    ASSERT_FALSE(h.requested.empty());
    EXPECT_EQ(h.requested.front(), 1519544u);
    EXPECT_TRUE(std::is_sorted(h.requested.begin(), h.requested.end()));
}

TEST(DashMnCheckpointBridge, IgnoresLiveTipBlocksArrivingMidBridge)
{
    // The cold-start race: the new_block inv leg delivers a block at the CURRENT
    // tip while the bridge is still replaying history. Folding it would advance
    // a stale cursor -- the E4-soak bad-cb-payee shape.
    BridgeHarness h;
    h.auto_deliver = false;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.tip = 1519546;
    h.lane.arm(good_checkpoint());
    h.lane.pump();
    ASSERT_EQ(h.lane.state(), MnCheckpointLane::State::Bridging);

    // A far-future block arrives first. It must be ignored, NOT folded.
    h.lane.on_block_connected(block_from_hex(kBlockHex1519546), 1519546);
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Bridging)
        << "an out-of-order live block must not fail or advance the bridge";
    EXPECT_EQ(h.lane.cursor_height(), kAnchorHeight);
    EXPECT_FALSE(h.published);

    // Now the ordered replay proceeds normally.
    h.lane.on_block_connected(block_from_hex(kBlockHex1519544), 1519544);
    h.lane.on_block_connected(block_from_hex(kBlockHex1519545), 1519545);
    h.lane.on_block_connected(block_from_hex(kBlockHex1519546), 1519546);
    EXPECT_TRUE(h.published) << h.lane.status();
    EXPECT_EQ(h.published_as_of, 1519546u);
}

TEST(DashMnCheckpointBridge, ChainPositionMismatchFailsClosed)
{
    // The anchor names a block our PoW-validated header chain does not hold at
    // that height: wrong chain, wrong fork, or a fabricated anchor.
    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(
        "00000000000000000000000000000000000000000000000000000000deadbeef");
    h.tip = 1519546;
    h.lane.arm(good_checkpoint());
    h.lane.pump();

    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed);
    EXPECT_NE(h.lane.status().find("CHAIN-POSITION MISMATCH"), std::string::npos)
        << h.lane.status();
    EXPECT_FALSE(h.published);
    // Terminal: further drives must not resurrect it.
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.lane.pump();
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed);
    EXPECT_FALSE(h.published);
}

TEST(DashMnCheckpointBridge, StaleAnchorBeyondBridgeBoundFailsClosed)
{
    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.tip = kAnchorHeight + 5000;
    h.lane.set_max_bridge_blocks(100);
    h.lane.arm(good_checkpoint());
    h.lane.pump();

    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed);
    EXPECT_NE(h.lane.status().find("STALE"), std::string::npos) << h.lane.status();
    EXPECT_FALSE(h.published);
    EXPECT_TRUE(h.requested.empty())
        << "a refused anchor must not start pulling block bodies";
}

TEST(DashMnCheckpointBridge, ReplayGapFailsClosed)
{
    // Blocks skipped mid-replay: dashd advanced its payment queue at heights we
    // never folded, so ours is silently behind. Never publish.
    BridgeHarness h;
    h.auto_deliver = false;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.tip = 1519546;
    h.lane.arm(good_checkpoint());
    h.lane.pump();
    ASSERT_EQ(h.lane.state(), MnCheckpointLane::State::Bridging);

    h.lane.on_block_connected(block_from_hex(kBlockHex1519544), 1519544);
    EXPECT_EQ(h.lane.cursor_height(), 1519544u);
    // 1519545 never arrives; the lane is waiting for it, so 1519546 is simply
    // ignored and the bridge NEVER publishes.
    h.lane.on_block_connected(block_from_hex(kBlockHex1519546), 1519546);
    EXPECT_FALSE(h.published);
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Bridging);
    EXPECT_EQ(h.lane.cursor_height(), 1519544u);
}

TEST(DashMnCheckpointBridge, PayeeDesyncOnWrongAnchorFailsClosed)
{
    // THE anchor falsification test. Corrupt the anchor so it projects the
    // wrong payee, then replay a real block. The block's real coinbase does not
    // pay what we project -> the anchor is proven wrong -> terminal refusal.
    // This is what stops a bad trust anchor from ever reaching a template.
    //
    // 1519459 is dc2e02ac's lastPaidHeight, the LOWEST in the set, which is why
    // dashd paid it at 1519544. Pushing it to the top of the queue makes some
    // OTHER masternode our projected payee.
    std::string p = mutate(kRealCheckpoint1519543, " 838365 1519459 ",
                           " 838365 1519543 ");
    auto bad = parse_mn_checkpoint(p, "testnet");
    ASSERT_TRUE(bad.ok) << bad.error;  // structurally valid, semantically wrong

    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.blocks[1519544] = block_from_hex(kBlockHex1519544);
    h.tip = 1519544;
    h.lane.arm(bad);
    h.lane.pump();

    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << h.lane.status();
    EXPECT_NE(h.lane.status().find("PAYEE DESYNC"), std::string::npos)
        << h.lane.status();
    EXPECT_FALSE(h.published)
        << "a falsified anchor must NEVER reach the maintainer";
}

TEST(DashMnCheckpointBridge, RefusedCheckpointArmsTerminallyFailedClosed)
{
    BridgeHarness h;
    h.headers[kAnchorHeight] = uint256S(kAnchorHash);
    h.tip = 1519546;
    h.lane.arm(parse_mn_checkpoint("", "mainnet"));   // UNPINNED
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::FailedClosed);
    h.lane.pump();
    EXPECT_FALSE(h.published);
    EXPECT_TRUE(h.requested.empty());
}

TEST(DashMnCheckpointBridge, WaitsQuietlyUntilHeadersReachTheAnchor)
{
    // Cold start: headers are still syncing. Not an error, and MUST NOT publish.
    BridgeHarness h;
    h.tip = 1000;
    h.lane.arm(good_checkpoint());
    h.lane.pump();
    EXPECT_EQ(h.lane.state(), MnCheckpointLane::State::Waiting);
    EXPECT_FALSE(h.published);
    EXPECT_TRUE(h.requested.empty());
}

// ═══════════════════════════════════════════════════════════════════════════
// 5. End-to-end through the REAL leg-4 event, plus the negative control.
// ═══════════════════════════════════════════════════════════════════════════
namespace {

// Mirrors main_dash's wiring: the lane publishes into Node::mn_list_update,
// leg 4 carries it to the maintainer, leg 2 supplies the tip.
struct E2eRig {
    dash::interfaces::Node                        node;
    dash::coin::NodeCoinState                     state;
    dash::coin::CoinStateMaintainer               maint{state};
    std::vector<std::shared_ptr<EventDisposable>> subs;
    BridgeHarness                                 h;

    E2eRig()
    {
        // The anti-mint latch main_dash enables for the embedded arm.
        maint.set_require_seeded_mn_set(true);
        subs.push_back(c2pool::dash::wire_mn_list_ingest(node, maint));
        subs.push_back(c2pool::dash::wire_tip_ingest(node, maint));
        h.lane.set_publish_fn(
            [this](std::vector<std::pair<uint256, MNState>> set, uint32_t as_of) {
                dash::interfaces::MnListUpdate up;
                up.mnstates     = std::move(set);
                up.as_of_height = as_of;
                node.mn_list_update.happened(up);
            });
        h.headers[kAnchorHeight] = uint256S(kAnchorHash);
        h.blocks[1519544] = block_from_hex(kBlockHex1519544);
        h.blocks[1519545] = block_from_hex(kBlockHex1519545);
        h.blocks[1519546] = block_from_hex(kBlockHex1519546);
        h.tip = 1519546;
    }

    void fire_tip()
    {
        dash::interfaces::TipAdvance ta;
        ta.prev_height           = 1519546;
        ta.prev_hash             = uint256S(kAnchorHash);
        ta.bits_for_next         = 0x1d00ffff;
        ta.mtp_at_tip            = 1751000000;
        ta.address_version       = TESTNET_PUBKEY_VER;
        ta.address_p2sh_version  = TESTNET_P2SH_VER;
        node.new_tip.happened(ta);
    }
};

} // namespace

TEST(DashMnCheckpointE2e, BridgePublishFlipsPopulatedThroughTheRealLeg4Event)
{
    E2eRig r;
    EXPECT_FALSE(r.state.populated()) << "cold start must not be populated";

    r.h.lane.arm(good_checkpoint());
    r.h.lane.pump();
    ASSERT_EQ(r.h.lane.state(), MnCheckpointLane::State::Published)
        << r.h.lane.status();

    r.fire_tip();

    EXPECT_TRUE(r.state.populated())
        << "the bridged masternode set + a live tip must flip the embedded arm";
}

// NEGATIVE CONTROL. Identical wiring; the ONLY difference is a corrupted
// anchor. If this ever passes populated()==true, the fail-closed path is
// decorative.
TEST(DashMnCheckpointE2e, NegativeControlCorruptAnchorLeavesArmUnpopulated)
{
    E2eRig r;
    std::string tampered = mutate(kRealCheckpoint1519543,
                                  "1519459", "1519999", /*reseal_it=*/false);
    auto bad = parse_mn_checkpoint(tampered, "testnet");
    ASSERT_FALSE(bad.ok);

    r.h.lane.arm(bad);
    r.h.lane.pump();
    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed);

    r.fire_tip();

    EXPECT_FALSE(r.state.populated())
        << "a refused anchor must leave the embedded arm unarmed -- templates"
           " keep routing to the dashd fallback";
}

// Second negative control, one layer down: prove the anti-mint latch main_dash
// enables actually blocks the "one accidental ProRegTx arms the queue" path.
TEST(DashMnCheckpointE2e, NegativeControlAntiMintLatchBlocksUnseededArming)
{
    dash::coin::NodeCoinState state;
    dash::coin::CoinStateMaintainer maint{state};
    maint.set_require_seeded_mn_set(true);

    // A non-empty masternode set with NO height stamp: what an unauthoritative
    // source (or a block-connect registration) would produce.
    auto cp = good_checkpoint();
    maint.on_mn_list_update(cp.entries, /*as_of_height=*/0);

    auto fire_tip = [&maint] {
        maint.on_new_tip(/*prev_height=*/1519546, uint256S(kAnchorHash),
                         /*bits_for_next=*/0x1d00ffff,
                         /*mtp_at_tip=*/1751000000,
                         TESTNET_PUBKEY_VER, TESTNET_P2SH_VER);
    };
    fire_tip();

    EXPECT_FALSE(state.populated())
        << "an unheighted masternode set must never arm the embedded arm";

    // Positive control on the same object: the SAME set WITH its height arms it.
    maint.on_mn_list_update(cp.entries, kAnchorHeight);
    fire_tip();
    EXPECT_TRUE(state.populated())
        << "a height-stamped authoritative snapshot must still arm normally";
}

// ═══════════════════════════════════════════════════════════════════════════
// 6. POST-ANCHOR PoSe BANS — the SML-attested recovery walk.
//
// A PoSe ban is applied by dashd from CONSENSUS (accumulated
// MAX_PoSe_PENALTY); it never appears as a special transaction in any block.
// MnStateMachine::apply_block walks special txs, so it is STRUCTURALLY unable
// to observe one. A masternode banned after the anchor height therefore stays
// isValid=true through the whole replay, holds the head of our payment queue,
// and is projected as the payee for a block dashd paid to somebody else. The
// bridge cross-check fires, and here that is TERMINAL — so ONE post-anchor ban
// anywhere in the window means the daemonless arm never publishes a masternode
// set at all, and every template keeps routing to dashd.
//
// The SML is the only carrier of that ban. These cases drive the recovery
// through the PRODUCTION SEAMS ONLY: a real MnCheckpointLane, armed with the
// real fixture checkpoint, all four existing seams wired plus a
// fixture-SML-backed validity fn built the same way main_dash builds it, then
// pump()/on_block_connected() with blocks whose non-payee bytes are the REAL
// accepted testnet blocks. The lane was missed by the original suite precisely
// because nothing entered it this way.
// ═══════════════════════════════════════════════════════════════════════════
namespace {

using dash::coin::MutableTransaction;
using dash::coin::vendor::CProUpServTx;
using dash::coin::vendor::CSimplifiedMNList;
using dash::coin::vendor::CSimplifiedMNListEntry;

// The six anchored masternodes in DIP-3 queue order at h=1519543 (ascending
// nLastPaidHeight 1519459..1519464, which is the CompareByLastPaid key for all
// six). The payout-address groups matter: Q1/Q4/Q5 share yVXDA…, Q2/Q3 share
// yeRZB…, Q6 is alone on yjTpMw… — which is why a demotion from Q1 lands on Q2
// (different script, cross-checkable) and why reaching Q6 costs five.
const char* const kQ1 = "dc2e02ac95ce4ccc9843c38de7bdaf32f2a1d5966c054127a3f4ca4f4bbd5991";
const char* const kQ2 = "9b653e767b978c10346d938c08dc8c5acd03c495f9d913e6fc652bfcae11a348";
const char* const kQ3 = "91bbce94c34ebde0d099c0a2cb7635c0c31425ebabcec644f4f1a0854bfa605d";
const char* const kQ4 = "72ee70fa75262781a17d1eb69a6c3e97328208be98b59d5530164f31e481d3aa";
const char* const kQ5 = "c87218fb9d031f4926c22430c69b4edf1f0fb80c331c1a79e3b1b3873407c0ac";
const char* const kQ6 = "ecebeb952f56a61abaccd7bda7f4df5eccbd5f87a91bc4a8969535df1058158e";

// Take the payout script from the ANCHOR rather than hardcoding hex, so a
// fixture regeneration cannot leave these tests quietly probing a script no
// masternode owns any more.
std::vector<unsigned char> payout_of(const MnCheckpoint& cp, const char* protx)
{
    const uint256 want = uint256S(protx);
    for (const auto& [h, st] : cp.entries)
        if (h == want) return st.scriptPayout.m_data;
    ADD_FAILURE() << "the anchor carries no masternode " << protx;
    return {};
}

// Rewrite the coinbase output paying `from` so it pays `to`. This synthesises
// "dashd skipped our projected payee and paid a later queue slot" on top of a
// REAL accepted block: every byte except that one output script — header,
// CbTx payload, the rest of the outputs — stays exactly as the network
// produced it.
dash::coin::BlockType repay_coinbase(dash::coin::BlockType blk,
                                     const std::vector<unsigned char>& from,
                                     const std::vector<unsigned char>& to)
{
    EXPECT_FALSE(blk.m_txs.empty());
    bool hit = false;
    for (auto& o : blk.m_txs[0].vout) {
        if (o.scriptPubKey.m_data == from) {
            o.scriptPubKey.m_data = to;
            hit = true;
        }
    }
    EXPECT_TRUE(hit) << "template block does not pay the script being replaced";
    return blk;
}

// A fixture SML plus the EXACT lambda shape main_dash wires around
// NodeCoinState::sml(): linear scan, three-state, std::nullopt when the
// masternode is absent. Captured BY VALUE so the hook cannot outlive its data.
MnCheckpointLane::SmlValidityFn sml_fn(
    const std::vector<std::pair<const char*, bool>>& entries)
{
    std::vector<CSimplifiedMNListEntry> v;
    v.reserve(entries.size());
    for (const auto& [hex, valid] : entries) {
        CSimplifiedMNListEntry e;
        e.proRegTxHash = uint256S(hex);
        e.isValid      = valid;
        v.push_back(e);
    }
    CSimplifiedMNList sml(std::move(v));
    return [sml](const uint256& h) -> std::optional<bool> {
        for (const auto& e : sml.mnList)
            if (e.proRegTxHash == h) return e.isValid;
        return std::nullopt;
    };
}

// Every masternode attested VALID except the listed ones.
std::vector<std::pair<const char*, bool>> all_valid_except(
    std::initializer_list<const char*> banned)
{
    std::vector<std::pair<const char*, bool>> out;
    for (const char* q : {kQ1, kQ2, kQ3, kQ4, kQ5, kQ6}) {
        bool is_banned = false;
        for (const char* b : banned) if (std::string(b) == q) is_banned = true;
        out.emplace_back(q, !is_banned);
    }
    return out;
}

// A one-block bridge over the real anchor: arm, then let pump() pull and fold
// the single block through the real request/deliver path.
struct RecoveryRig {
    MnCheckpoint  cp{good_checkpoint()};
    BridgeHarness h;

    void run(const dash::coin::BlockType& blk, uint32_t tip = 1519544)
    {
        h.headers[kAnchorHeight] = uint256S(kAnchorHash);
        h.blocks[1519544] = blk;
        h.tip = tip;
        h.lane.arm(cp);
        h.lane.pump();
    }
};

std::vector<unsigned char> protx_payload_bytes(const CProUpServTx& p)
{
    auto ps = ::pack(p);
    auto sp = ps.get_span();
    return std::vector<unsigned char>(
        reinterpret_cast<const unsigned char*>(sp.data()),
        reinterpret_cast<const unsigned char*>(sp.data()) + sp.size());
}

// A ProUpServTx reviving `protx`. dashcore's revival branch — which
// MnStateMachine mirrors — is gated on nPoSeBanHeight != 0, so this tx is a
// NO-OP unless something recorded a ban height for that masternode first.
MutableTransaction pro_up_serv_tx(const char* protx)
{
    CProUpServTx p;
    p.nVersion  = dash::coin::vendor::ProTxVersion::BASIC_BLS;
    p.nType     = dash::coin::vendor::MnType::REGULAR;
    p.proTxHash = uint256S(protx);
    p.netInfo.port_be = 0x2334;

    MutableTransaction tx;
    tx.type          = CProUpServTx::SPECIALTX_TYPE;
    tx.extra_payload = protx_payload_bytes(p);
    bitcoin_family::coin::TxIn in;
    in.prevout.hash  = uint256{};
    in.prevout.index = 0xFFFFFFFF;
    in.sequence      = 0xFFFFFFFF;
    tx.vin.push_back(in);
    return tx;
}

} // namespace

// CASE 1. The bug this whole change exists for. dashd banned our queue head
// after the anchor was cut, so the block pays queue slot 2. Today that is a
// terminal payee_desync and the arm never arms. With the SML attesting the
// ban, the bridge COMPLETES — and the published set carries the exclusion
// permanently, because a one-shot skip would desync again at that masternode's
// next queue turn (~|set| blocks later).
TEST(DashMnCheckpointSmlRecovery, PostAnchorBanAttestedBySmlCompletesTheBridge)
{
    RecoveryRig r;
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({kQ1})));
    r.run(blk);

    ASSERT_TRUE(r.h.published) << "lane status: " << r.h.lane.status();
    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::Published);
    EXPECT_EQ(r.h.lane.sml_recovered(), 1u);
    EXPECT_NE(r.h.lane.status().find("1 SML-recovered exclusions"),
              std::string::npos)
        << "the recovery count must be on the published status, not only in"
           " scrollback: " << r.h.lane.status();

    std::map<uint256, MNState> out(r.h.published_set.begin(),
                                   r.h.published_set.end());
    const MNState& demoted = out.at(uint256S(kQ1));
    EXPECT_FALSE(demoted.isValid) << "the exclusion must be PERMANENT";
    EXPECT_EQ(demoted.nPoSeBanHeight, 1519544u)
        << "a nonzero ban height is what makes the ProUpServTx revival gate"
           " functional for this masternode";
    EXPECT_EQ(demoted.nLastPaidHeight, 1519459u)
        << "the demoted masternode must NOT be credited with the payment";
    EXPECT_EQ(out.at(uint256S(kQ2)).nLastPaidHeight, 1519544u)
        << "the accepted candidate is the one whose script the coinbase pays";
}

// CASE 2. Same desync, but the SML says the projected payee is LIVE. Then the
// mismatch is a real desync (bad anchor, missed block, corrupt seed) and the
// only correct answer is the old one. Attested-valid is COUNTER-evidence, and
// this is the case that stops the walk from excusing anything it likes.
TEST(DashMnCheckpointSmlRecovery, SmlAttestingProjectedPayeeValidStillFailsClosed)
{
    RecoveryRig r;
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({})));
    r.run(blk);

    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << r.h.lane.status();
    EXPECT_NE(r.h.lane.status().find("PAYEE DESYNC"), std::string::npos)
        << r.h.lane.status();
    EXPECT_FALSE(r.h.published);
    EXPECT_EQ(r.h.lane.sml_recovered(), 0u);
}

// CASE 3. No hook at all — the pre-change wiring. Behaviour must be exactly
// what it was: terminal.
TEST(DashMnCheckpointSmlRecovery, NoSmlSeamWiredKeepsTheTerminalFailClosed)
{
    RecoveryRig r;
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    r.run(blk);   // deliberately no set_sml_validity_fn

    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << r.h.lane.status();
    EXPECT_FALSE(r.h.published);
    EXPECT_EQ(r.h.lane.sml_recovered(), 0u);
    EXPECT_NE(r.h.lane.status().find("no SML validity seam is wired"),
              std::string::npos)
        << "the operator must be told WHICH input was missing: "
        << r.h.lane.status();
}

// CASE 3b. A hook that has no opinion. Absent-from-SML is not evidence of a
// ban; collapsing nullopt into "banned" would turn every SML gap into a
// licence to re-attribute payments.
TEST(DashMnCheckpointSmlRecovery, SmlWithoutTheMasternodeIsNotEvidence)
{
    RecoveryRig r;
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    // An SML that carries only OTHER masternodes: the projected payee is
    // simply absent, so the hook answers std::nullopt for it.
    r.h.lane.set_sml_validity_fn(sml_fn({{kQ3, true}, {kQ4, true}}));
    r.run(blk);

    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << r.h.lane.status();
    EXPECT_FALSE(r.h.published);
    EXPECT_EQ(r.h.lane.sml_recovered(), 0u);
}

// CASE 4. The demotion is licensed, but the re-projection ALSO does not match
// the coinbase, and the next candidate down is attested live. Acceptance
// requires an EXACT coinbase script match at some licensed step; there is
// none, so nothing is attributed and nothing is excluded.
TEST(DashMnCheckpointSmlRecovery, ReProjectionThatAlsoMismatchesFailsClosed)
{
    RecoveryRig r;
    // Pay Q6's script. Q2 (the first demotion target) is on a different
    // script, so the walk stalls immediately after one licensed demotion.
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ6));
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({kQ1})));
    r.run(blk);

    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << r.h.lane.status();
    EXPECT_NE(r.h.lane.status().find("PAYEE DESYNC"), std::string::npos)
        << r.h.lane.status();
    EXPECT_FALSE(r.h.published);
    EXPECT_EQ(r.h.lane.sml_recovered(), 0u)
        << "a refused walk must not leave a partial exclusion behind";
}

// CASE 5. The budget. The lane sizes it at 4 + replay_distance/1000, so a
// one-block bridge allows 4. Reaching Q6 costs FIVE demotions (Q1..Q5), and
// every one of them is attested — the walk would otherwise succeed. Past the
// cap this stops being a repair of a few known-banned nodes and becomes a
// wholesale override of the projection, so it fails closed instead.
TEST(DashMnCheckpointSmlRecovery, ExclusionsPastThePerBridgeCapFailClosed)
{
    RecoveryRig r;
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ6));
    r.h.lane.set_sml_validity_fn(
        sml_fn(all_valid_except({kQ1, kQ2, kQ3, kQ4, kQ5})));
    r.run(blk);

    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << r.h.lane.status();
    EXPECT_FALSE(r.h.published);
    EXPECT_EQ(r.h.lane.sml_recovered(), 0u);
}

// CASE 6. The permanence pays off. The excluded masternode is later revived by
// a real ProUpServTx inside the same replay window. dashcore's revival branch
// is gated on nPoSeBanHeight != 0 — so it fires ONLY because the recovery
// recorded a ban height. Without that (the one-shot-skip design), this
// masternode's revivedHeight would stay at its stale anchor value of 1367840
// and it would sit at the wrong queue position for the rest of the bridge.
TEST(DashMnCheckpointSmlRecovery, RevivalTxLaterInWindowFiresOffTheRecoveredBan)
{
    RecoveryRig r;
    auto b44 = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    auto b45 = block_from_hex(kBlockHex1519545);
    b45.m_txs.push_back(pro_up_serv_tx(kQ1));

    r.h.blocks[1519545] = b45;
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({kQ1})));
    r.run(b44, /*tip=*/1519545);

    ASSERT_TRUE(r.h.published) << "lane status: " << r.h.lane.status();
    EXPECT_EQ(r.h.published_as_of, 1519545u);
    EXPECT_EQ(r.h.lane.sml_recovered(), 1u);

    std::map<uint256, MNState> out(r.h.published_set.begin(),
                                   r.h.published_set.end());
    const MNState& revived = out.at(uint256S(kQ1));
    EXPECT_TRUE(revived.isValid) << "the ProUpServTx must bring it back";
    EXPECT_EQ(revived.nPoSeBanHeight, 0u);
    EXPECT_EQ(revived.nPoSeRevivedHeight, 1519545u)
        << "revivedHeight still at the anchor's 1367840 means the revival"
           " branch never fired -- i.e. the exclusion did not record a ban"
           " height and the queue position is now wrong";
    // 1519545's own payee is unaffected: pass 0 projects from the PRE-block
    // list, where kQ1 is still excluded, so queue slot 3 was paid.
    EXPECT_EQ(out.at(uint256S(kQ3)).nLastPaidHeight, 1519545u);
}

// ═══════════════════════════════════════════════════════════════════════════
// 7. PoSe REMOVALS — the replay must SUBTRACT, not only ADD.
// ═══════════════════════════════════════════════════════════════════════════
//
// MEASURED, mainnet, hotel dashd 23.1.7, 2026-08-02:
//
//     protx list valid false 2513000  -> 2068 entries   (the anchor)
//     protx list valid false 2514874  -> 2059 entries   the chain FELL by 9
//     the bridge's replayed set        2067 -> 2070      we CLIMBED by 3
//
// A block replay can only ADD: a PoSe ban is derived by dashd from consensus
// (accumulated MAX_PoSe_PENALTY) and never appears as a special transaction,
// so apply_block is structurally unable to see one. The SML carries it, we
// already persist it, and MnStateMachine::reconcile_pose_from_sml() is the
// pass that applies it — BEFORE each replayed block is folded, for the
// ordering reasons written out at that function.
//
// Every positive case below has a negative twin that must go red if the
// removal path is deleted.
// ═══════════════════════════════════════════════════════════════════════════
namespace {

using dash::coin::MnStateMachine;
using dash::coin::vendor::CProRegTx;

// An SML the test can REFRESH between replayed heights. The mnlistdiff feed
// keeps running for the whole life of a multi-hour bridge, so "banned at
// h=N, valid again at h=N+1" is a real sequence, not a contrivance. Keyed by
// height; the newest entry at or below the queried height wins.
struct RefreshingSml {
    std::map<uint32_t, CSimplifiedMNList> by_height;

    void set(uint32_t h, const std::vector<std::pair<const char*, bool>>& es)
    {
        std::vector<CSimplifiedMNListEntry> v;
        v.reserve(es.size());
        for (const auto& [hex, valid] : es) {
            CSimplifiedMNListEntry e;
            e.proRegTxHash = uint256S(hex);
            e.isValid      = valid;
            v.push_back(e);
        }
        by_height.insert_or_assign(h, CSimplifiedMNList(std::move(v)));
    }
    void set_hashes(uint32_t h,
                    const std::vector<std::pair<uint256, bool>>& es)
    {
        std::vector<CSimplifiedMNListEntry> v;
        v.reserve(es.size());
        for (const auto& [hash, valid] : es) {
            CSimplifiedMNListEntry e;
            e.proRegTxHash = hash;
            e.isValid      = valid;
            v.push_back(e);
        }
        by_height.insert_or_assign(h, CSimplifiedMNList(std::move(v)));
    }
    const CSimplifiedMNList* at(uint32_t h) const
    {
        if (by_height.empty()) return nullptr;
        auto it = by_height.upper_bound(h);
        if (it == by_height.begin()) return nullptr;
        --it;
        return &it->second;
    }
};

// Wire the production snapshot seam. reconcile_pose() runs while the lane's
// cursor still points at the PREVIOUS height, so cursor_height()+1 is exactly
// the height being reconciled.
void wire_sml_snapshot(MnCheckpointLane& lane, const RefreshingSml& src)
{
    lane.set_sml_snapshot_fn([&lane, &src]() -> const CSimplifiedMNList* {
        return src.at(lane.cursor_height() + 1);
    });
}

uint256 synth_tx_hash(const MutableTransaction& tx)
{
    ::PackStream s;
    s << tx;
    auto sp = s.get_span();
    uint256 h;
    CHash256()
        .Write(std::span<const unsigned char>(
            reinterpret_cast<const unsigned char*>(sp.data()), sp.size()))
        .Finalize(std::span<unsigned char>(h.data(), 32));
    return h;
}

// A ProRegTx registering a brand-new masternode with `payout` as its
// scriptPayout. Its proTxHash is the tx hash, so tests compute it with
// synth_tx_hash() and can name it in the SML.
MutableTransaction pro_reg_tx(const std::vector<unsigned char>& payout,
                              uint32_t nonce)
{
    CProRegTx p;
    p.nVersion = dash::coin::vendor::ProTxVersion::BASIC_BLS;
    p.nType    = dash::coin::vendor::MnType::REGULAR;
    p.collateralOutpoint.hash  = uint256{};   // "this tx's own output N"
    p.collateralOutpoint.index = nonce;
    p.netInfo.port_be          = 0x2334;
    p.scriptPayout.m_data      = payout;

    MutableTransaction tx;
    tx.type = CProRegTx::SPECIALTX_TYPE;
    {
        auto ps = ::pack(p);
        auto sp = ps.get_span();
        tx.extra_payload.assign(
            reinterpret_cast<const unsigned char*>(sp.data()),
            reinterpret_cast<const unsigned char*>(sp.data()) + sp.size());
    }
    bitcoin_family::coin::TxIn in;
    in.prevout.hash  = uint256{};
    in.prevout.index = 0xFFFF0000u | nonce;   // never a known collateral
    in.sequence      = 0xFFFFFFFF;
    tx.vin.push_back(in);
    return tx;
}

// A distinctive P2PKH-shaped script no fixture masternode owns.
std::vector<unsigned char> synth_script(uint8_t tag)
{
    std::vector<unsigned char> s{0x76, 0xa9, 0x14};
    for (int i = 0; i < 20; ++i) s.push_back(static_cast<unsigned char>(tag));
    s.push_back(0x88);
    s.push_back(0xac);
    return s;
}

} // namespace

// ── CASE R1 (POSITIVE). A masternode valid at the anchor and PoSe-banned
// inside the window is REMOVED from the payee-eligible set, so it is never
// projected. The bridge completes with NO help from the reactive demotion
// walk — the per-hash validity seam is deliberately left unwired here, so the
// only thing that can produce this result is the removal pass.
TEST(DashMnCheckpointPoseRemoval, BannedMidWindowIsRemovedFromTheEligibleSet)
{
    RecoveryRig r;
    RefreshingSml sml;
    sml.set(1519544, all_valid_except({kQ1}));
    wire_sml_snapshot(r.h.lane, sml);

    // dashd skipped the banned Q1 and paid queue slot 2.
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    r.run(blk);

    ASSERT_TRUE(r.h.published) << "lane status: " << r.h.lane.status();
    EXPECT_EQ(r.h.lane.pose_removed(), 1u)
        << "the SML removal pass is what has to fire here";
    EXPECT_EQ(r.h.lane.sml_recovered(), 0u)
        << "the reactive demotion walk must NOT be needed once the removal"
           " pass runs -- it is the capped second line of defence";
    EXPECT_EQ(r.h.lane.anchor_eligible(), 6u);
    EXPECT_EQ(r.h.lane.eligible_size(), 5u)
        << "the payee-eligible set must FALL, which is exactly what the"
           " measured 2068->2059 vs 2067->2070 divergence says it never did";

    std::map<uint256, MNState> out(r.h.published_set.begin(),
                                   r.h.published_set.end());
    const MNState& banned = out.at(uint256S(kQ1));
    EXPECT_FALSE(banned.isValid);
    EXPECT_EQ(banned.nPoSeBanHeight, 1519544u);
    EXPECT_EQ(banned.nLastPaidHeight, 1519459u)
        << "a removed masternode must not be credited with the payment";
    EXPECT_EQ(out.at(uint256S(kQ2)).nLastPaidHeight, 1519544u);
}

// ── CASE R1-TWIN (NEGATIVE). The identical scenario with the removal seam
// unwired -- i.e. the code as it stood when the bridge fail-closed at
// h=2514874. The replay can only ADD, the banned masternode keeps the head of
// the queue, and the bridge refuses. If deleting the removal path did not
// change behaviour, R1 above would be proving nothing.
TEST(DashMnCheckpointPoseRemoval, TwinNoRemovalSeamStillFailsClosed)
{
    RecoveryRig r;
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    r.run(blk);   // no snapshot seam, no validity seam

    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << r.h.lane.status();
    EXPECT_FALSE(r.h.published);
    EXPECT_EQ(r.h.lane.pose_removed(), 0u);
    EXPECT_EQ(r.h.lane.eligible_size(), 6u)
        << "with no removal pass the eligible set can only stay flat or climb";
}

// ── CASE R2. The fail-closed message must MEASURE the divergence, not list
// hypotheses. An operator has to be able to tell "the anchor is wrong" from
// "the replay is incomplete" from "a PoSe ban could not be attested" out of
// the log alone.
TEST(DashMnCheckpointPoseRemoval, FailClosedReportsTheActualDelta)
{
    RecoveryRig r;
    RefreshingSml sml;
    // The SML attests every masternode VALID, so the removal pass has nothing
    // to remove and the mismatch is a REAL desync.
    sml.set(1519544, all_valid_except({}));
    wire_sml_snapshot(r.h.lane, sml);
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({})));

    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    r.run(blk);

    ASSERT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed);
    const std::string s = r.h.lane.status();
    EXPECT_NE(s.find("SET DELTA"), std::string::npos) << s;
    EXPECT_NE(s.find("6 at the anchor"), std::string::npos)
        << "set size before must be stated: " << s;
    EXPECT_NE(s.find("ADDS: 0 registrations"), std::string::npos) << s;
    EXPECT_NE(s.find("0 PoSe (SML-attested)"), std::string::npos)
        << "the removal count must be stated even when it is zero: " << s;
    EXPECT_NE(s.find("PROJECTED PAYEE: " + uint256S(kQ1).GetHex()),
              std::string::npos)
        << "the operator must be told WHICH masternode we projected: " << s;
    EXPECT_NE(s.find("attests it VALID"), std::string::npos)
        << "...and what the SML thinks of it: " << s;
}

// ── CASE R2-TWIN (NEGATIVE). Same shape, but the SML DOES attest the
// projected payee invalid and no candidate below it matches the coinbase.
// The report must say something DIFFERENT, or it is not a measurement.
TEST(DashMnCheckpointPoseRemoval, FailClosedDistinguishesAnAttestedBan)
{
    RecoveryRig r;
    // Pay a script no masternode below Q1 owns, so nothing can be repaired.
    r.h.lane.set_sml_validity_fn(sml_fn(all_valid_except({kQ1})));
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), synth_script(0x5a));
    r.run(blk);

    ASSERT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed);
    const std::string s = r.h.lane.status();
    EXPECT_NE(s.find("attests it INVALID"), std::string::npos) << s;
    EXPECT_EQ(s.find("attests it VALID"), std::string::npos)
        << "the two verdicts must not be reported with the same words: " << s;
    EXPECT_NE(s.find("NO SML SNAPSHOT SEAM IS WIRED"), std::string::npos)
        << "an operator whose removal pass is not wired must be told so: " << s;
}

// ── CASE R3. Banned AND revived inside the replay window must end VALID.
// The SML refreshes during the bridge (mnlistdiffs keep arriving for its whole
// duration), so h=1519544 sees the ban and h=1519545 sees the revival. Only a
// bridge-owned exclusion may be lifted this way.
TEST(DashMnCheckpointPoseRemoval, BannedThenRevivedInsideTheWindowEndsValid)
{
    RecoveryRig r;
    RefreshingSml sml;
    sml.set(1519544, all_valid_except({kQ1}));   // banned
    sml.set(1519545, all_valid_except({}));      // revived
    wire_sml_snapshot(r.h.lane, sml);

    auto b44 = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
    r.h.blocks[1519545] = block_from_hex(kBlockHex1519545);
    r.run(b44, /*tip=*/1519545);

    ASSERT_TRUE(r.h.published) << "lane status: " << r.h.lane.status();
    EXPECT_EQ(r.h.published_as_of, 1519545u);
    EXPECT_EQ(r.h.lane.pose_removed(), 1u);
    EXPECT_EQ(r.h.lane.pose_reinstated(), 1u);
    EXPECT_EQ(r.h.lane.eligible_size(), 6u)
        << "the set must be back to full strength once the ban is lifted";

    std::map<uint256, MNState> out(r.h.published_set.begin(),
                                   r.h.published_set.end());
    const MNState& revived = out.at(uint256S(kQ1));
    EXPECT_TRUE(revived.isValid) << "a ban+revive inside the window ends VALID";
    EXPECT_EQ(revived.nPoSeBanHeight, 0u);
    EXPECT_EQ(revived.nPoSeRevivedHeight, 1519545u);
}

// ── CASE R3-TWIN (NEGATIVE). The reinstatement is OWNERSHIP-bounded: a
// tx-driven ban (ProUpRevTx, or the operator-key-change ProUpRegTx) is
// consensus-exact at a known height and must NEVER be undone by an SML that
// merely shows the masternode live at the TIP -- that only means it will be
// revived by a ProUpServTx we have not folded yet, and lifting it early puts
// it back in the queue ahead of dashd's. Driven at the state machine, which
// is where the ownership rule lives.
TEST(DashMnCheckpointPoseRemoval, TwinTxDrivenBanIsNotReinstatedBySml)
{
    MnStateMachine m;
    std::vector<std::pair<uint256, MNState>> seed;
    MNState st;
    st.isValid           = false;          // banned by a ProUpRevTx at 1519500
    st.nPoSeBanHeight    = 1519500;
    st.nRegisteredHeight = 1000000;
    st.scriptPayout.m_data = synth_script(0x11);
    seed.emplace_back(uint256S(kQ1), st);
    m.load(std::move(seed), 1519543);

    std::vector<CSimplifiedMNListEntry> v(1);
    v[0].proRegTxHash = uint256S(kQ1);
    v[0].isValid      = true;              // the SML shows it live AT THE TIP
    CSimplifiedMNList sml(std::move(v));

    const auto pr = m.reconcile_pose_from_sml(sml, 1519544);
    EXPECT_EQ(pr.reinstated, 0u)
        << "only exclusions this bridge created may be lifted";
    EXPECT_EQ(m.pose_reinstated_total(), 0u);
    EXPECT_FALSE(m.entries().at(uint256S(kQ1)).isValid);
    EXPECT_EQ(m.entries().at(uint256S(kQ1)).nPoSeBanHeight, 1519500u)
        << "the exact tx-observed ban height must survive untouched";
}

// ── CASE R4. Set-size accounting, on a fixture modelled directly on the real
// mainnet delta: 2068 payee-eligible masternodes at the anchor, 12 PoSe-banned
// and 3 registered inside the window. The chain's number is 2068 -> 2059; a
// replay that only ADDS reports 2068 -> 2071 (climbs by 3 -- the measured
// +3). Both machines below are driven identically except for the removal pass.
TEST(DashMnCheckpointPoseRemoval, SetSizeAccountingMatchesTheMainnetDelta)
{
    constexpr uint32_t kAnchor  = 2513000;
    constexpr uint32_t kApplyAt = 2513001;
    constexpr size_t   kAnchorEligible = 2068;
    constexpr size_t   kBanned = 12;
    constexpr size_t   kAdds   = 3;

    auto seed_set = [&] {
        std::vector<std::pair<uint256, MNState>> out;
        out.reserve(kAnchorEligible);
        for (size_t i = 0; i < kAnchorEligible; ++i) {
            MNState st;
            st.isValid             = true;
            st.nRegisteredHeight   = 2000000;
            st.nLastPaidHeight     = static_cast<uint32_t>(kAnchor - 2100 + i);
            st.scriptPayout.m_data = synth_script(0)  ;
            // Unique 20-byte hash160 body per masternode so no two share a
            // payout script (a shared script would hide a wrong attribution).
            st.scriptPayout.m_data[3] = static_cast<unsigned char>(i & 0xff);
            st.scriptPayout.m_data[4] = static_cast<unsigned char>(i >> 8);
            st.collateralOutpoint.hash  = uint256S(kQ1);
            st.collateralOutpoint.index = static_cast<uint32_t>(i);
            uint256 h = uint256S(kQ2);
            h.data()[0] = static_cast<unsigned char>(i & 0xff);
            h.data()[1] = static_cast<unsigned char>(i >> 8);
            out.emplace_back(h, st);
        }
        return out;
    };

    // The 12 the SML attests banned: masternodes 3, 6, 9, ... — deliberately
    // NOT the head of the queue, so the removal has to be proactive rather
    // than something the coinbase cross-check could have stumbled into.
    auto sml_marking_banned = [&](const std::vector<std::pair<uint256, MNState>>& set) {
        std::vector<CSimplifiedMNListEntry> v;
        v.reserve(set.size());
        for (size_t i = 0; i < set.size(); ++i) {
            CSimplifiedMNListEntry e;
            e.proRegTxHash = set[i].first;
            e.isValid      = !((i % 3 == 0) && (i / 3) < kBanned);
            v.push_back(e);
        }
        return CSimplifiedMNList(std::move(v));
    };

    const auto anchor_set = seed_set();
    const CSimplifiedMNList sml = sml_marking_banned(anchor_set);

    // Three registrations, folded from a real accepted block body whose
    // coinbase is rewritten to pay whichever masternode the machine projects.
    auto make_block = [&](const std::vector<unsigned char>& pay_to) {
        auto blk = block_from_hex(kBlockHex1519544);
        blk.m_txs[0].vout[1].scriptPubKey.m_data = pay_to;
        for (size_t i = 0; i < kAdds; ++i)
            blk.m_txs.push_back(
                pro_reg_tx(synth_script(static_cast<uint8_t>(0xd0 + i)),
                           static_cast<uint32_t>(i)));
        return blk;
    };

    // ── The replay AS IT WAS: additions only. ──────────────────────────────
    MnStateMachine before;
    before.load(anchor_set, kAnchor);
    ASSERT_EQ(before.eligible_size(), kAnchorEligible);
    {
        auto proj = before.find_expected_payee();
        ASSERT_TRUE(proj.has_value());
        const auto r =
            before.apply_block(make_block(before.entries().at(*proj)
                                              .scriptPayout.m_data), kApplyAt);
        ASSERT_FALSE(r.payee_desync);
        EXPECT_EQ(r.registered, kAdds);
    }
    EXPECT_EQ(before.eligible_size(), kAnchorEligible + kAdds)
        << "a replay that can only ADD climbs -- the measured 2067 -> 2070";

    // ── The replay WITH the removal pass. ──────────────────────────────────
    MnStateMachine after;
    after.load(anchor_set, kAnchor);
    const auto pr = after.reconcile_pose_from_sml(sml, kApplyAt);
    EXPECT_EQ(pr.eligible_before, kAnchorEligible);
    EXPECT_EQ(pr.removed, kBanned);
    EXPECT_EQ(pr.eligible_after, kAnchorEligible - kBanned);
    {
        auto proj = after.find_expected_payee();
        ASSERT_TRUE(proj.has_value());
        const auto r =
            after.apply_block(make_block(after.entries().at(*proj)
                                             .scriptPayout.m_data), kApplyAt);
        ASSERT_FALSE(r.payee_desync);
        EXPECT_EQ(r.registered, kAdds);
    }
    EXPECT_EQ(after.eligible_size(), 2059u)
        << "2068 - 12 banned + 3 registered = 2059, which is what"
           " `protx list valid false 2514874` actually returned";
    EXPECT_EQ(after.size(), kAnchorEligible + kAdds)
        << "REGISTERED is unchanged by a PoSe ban -- comparing that number"
           " against `protx list valid` is what hid this bug";
    EXPECT_EQ(after.pose_removed_total(), kBanned);
}

// ── CASE R5. A registration and a removal in the SAME block, in the
// documented order. reconcile runs PRE-block, so:
//   * the masternode registered BY this block is not in the set yet and
//     cannot be removed at its own registration height -- which is right,
//     because it was not in dashd's H-1 list either and a ProRegTx
//     masternode enters with zero penalty;
//   * an existing masternode IS removed before pass 0 ranks candidates.
// The newcomer becomes removable at H+1, the first height at which it could
// ever be projected.
TEST(DashMnCheckpointPoseRemoval, RegistrationAndRemovalInOneBlockApplyInOrder)
{
    const auto newcomer_script = synth_script(0xc7);
    const MutableTransaction reg = pro_reg_tx(newcomer_script, 7);
    const uint256 newcomer = synth_tx_hash(reg);

    // ---- H only: the newcomer must survive its own registration height ----
    {
        RecoveryRig r;
        RefreshingSml sml;
        auto es = all_valid_except({kQ1});
        std::vector<std::pair<uint256, bool>> hs;
        for (auto& [hex, v] : es) hs.emplace_back(uint256S(hex), v);
        hs.emplace_back(newcomer, false);   // the SML wants it gone TOO
        sml.set_hashes(1519544, hs);
        wire_sml_snapshot(r.h.lane, sml);

        auto b44 = repay_coinbase(block_from_hex(kBlockHex1519544),
                                  payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
        b44.m_txs.push_back(reg);
        r.run(b44);

        ASSERT_TRUE(r.h.published) << r.h.lane.status();
        EXPECT_EQ(r.h.lane.pose_removed(), 1u)
            << "exactly ONE removal at h=1519544: the pre-existing kQ1."
               " Removing the newcomer too would mean the reconcile ran"
               " AFTER the block and retro-banned a masternode at its own"
               " registration height";
        EXPECT_EQ(r.h.lane.replay_registered(), 1u);

        std::map<uint256, MNState> out(r.h.published_set.begin(),
                                       r.h.published_set.end());
        ASSERT_EQ(out.count(newcomer), 1u)
            << "the ProRegTx must have registered the newcomer";
        EXPECT_TRUE(out.at(newcomer).isValid)
            << "a masternode cannot be PoSe-banned at the height it registers";
        EXPECT_FALSE(out.at(uint256S(kQ1)).isValid);
        EXPECT_EQ(r.h.lane.eligible_size(), 6u)   // 6 - 1 banned + 1 new
            << "one out, one in";
    }

    // ---- H and H+1: at the NEXT height the newcomer is removable ----------
    {
        RecoveryRig r;
        RefreshingSml sml;
        auto es = all_valid_except({kQ1});
        std::vector<std::pair<uint256, bool>> hs;
        for (auto& [hex, v] : es) hs.emplace_back(uint256S(hex), v);
        hs.emplace_back(newcomer, false);
        sml.set_hashes(1519544, hs);
        wire_sml_snapshot(r.h.lane, sml);

        auto b44 = repay_coinbase(block_from_hex(kBlockHex1519544),
                                  payout_of(r.cp, kQ1), payout_of(r.cp, kQ2));
        b44.m_txs.push_back(reg);
        r.h.blocks[1519545] = block_from_hex(kBlockHex1519545);
        r.run(b44, /*tip=*/1519545);

        ASSERT_TRUE(r.h.published) << r.h.lane.status();
        EXPECT_EQ(r.h.lane.pose_removed(), 2u)
            << "kQ1 at h=1519544, the newcomer at h=1519545";
        std::map<uint256, MNState> out(r.h.published_set.begin(),
                                       r.h.published_set.end());
        EXPECT_FALSE(out.at(newcomer).isValid);
        EXPECT_EQ(out.at(newcomer).nPoSeBanHeight, 1519545u)
            << "removed at the FIRST height it could have been projected,"
               " not at the height it registered";
        EXPECT_EQ(r.h.lane.eligible_size(), 5u);
    }
}

// ── CASE R6. The SML is a snapshot of NOW, so a removal can be EARLY: the ban
// may have fallen after the block being replayed, and dashd paid the
// masternode normally right up to it. Here block 1519544 is the REAL,
// unmodified accepted block -- it pays kQ1, which the tip SML says is banned.
// The repair attributes the payment (the DIP-3 queue cursor has to stay
// dashd-identical) and KEEPS the exclusion.
TEST(DashMnCheckpointPoseRemoval, EarlyRemovalIsRepairedByTheRealCoinbase)
{
    RecoveryRig r;
    RefreshingSml sml;
    sml.set(1519544, all_valid_except({kQ1}));
    wire_sml_snapshot(r.h.lane, sml);
    r.run(block_from_hex(kBlockHex1519544));   // untouched real block

    ASSERT_TRUE(r.h.published) << r.h.lane.status();
    EXPECT_EQ(r.h.lane.pose_removed(), 1u);
    EXPECT_EQ(r.h.lane.pose_premature(), 1u)
        << "the block pays a masternode we had already excluded -- that is"
           " proof its ban had not taken effect yet at this height";

    std::map<uint256, MNState> out(r.h.published_set.begin(),
                                   r.h.published_set.end());
    EXPECT_EQ(out.at(uint256S(kQ1)).nLastPaidHeight, 1519544u)
        << "the payment must be attributed or every later projection is one"
           " queue slot off";
    EXPECT_FALSE(out.at(uint256S(kQ1)).isValid)
        << "the exclusion is KEPT: it really is banned by the time we publish";
    EXPECT_EQ(out.at(uint256S(kQ2)).nLastPaidHeight, 1519460u)
        << "queue slot 2 must NOT have been credited";
}

// ── CASE R6-TWIN (NEGATIVE). The repair is rank-gated. An excluded masternode
// that sorts AFTER our projection cannot explain the coinbase -- dashd would
// have paid the projection first -- so the repair must refuse and the bridge
// must fail closed. Without that gate, any excluded masternode whose script
// happens to appear in a coinbase would license a re-attribution.
TEST(DashMnCheckpointPoseRemoval, TwinExcludedButLowerRankedDoesNotRepair)
{
    RecoveryRig r;
    RefreshingSml sml;
    sml.set(1519544, all_valid_except({kQ6}));   // kQ6 is LAST in the queue
    wire_sml_snapshot(r.h.lane, sml);

    // The block pays kQ6's script; our projection is still kQ1 (untouched).
    auto blk = repay_coinbase(block_from_hex(kBlockHex1519544),
                              payout_of(r.cp, kQ1), payout_of(r.cp, kQ6));
    r.run(blk);

    EXPECT_EQ(r.h.lane.state(), MnCheckpointLane::State::FailedClosed)
        << r.h.lane.status();
    EXPECT_FALSE(r.h.published);
    EXPECT_EQ(r.h.lane.pose_removed(), 1u);
    EXPECT_EQ(r.h.lane.pose_premature(), 0u)
        << "a lower-ranked exclusion must never be accepted as the payee";
}
