// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by gen_fixtures.cpp — do not edit. Expected values are the
// literal fixture inputs (chosen scalars) and a published BIP32 vector.
#pragma once
#include <string>
namespace fx {
inline const std::string electrum_master_xprv = "xprv9s21ZrQH143K3QTDL4LXw2F7HEK3wJUD2nW2nRk4stbPy6cq3jPPqjiChkVvvNKmPGJxWUtg6LnF5kejMRNNU3TGtRBeJgk33yuGBxrMPHi";
inline const std::string password = "c2pool-test-pass";
inline const std::string walletdat_scalar1_hex = "1111111111111111111111111111111111111111111111111111111111111111";
inline const std::string walletdat_scalar2_hex = "2222222222222222222222222222222222222222222222222222222222222222";
inline const std::string walletdat_pub1_hex = "034f355bdcb7cc0af728ef3cceb9615d90684bb5b2ca5f859ab0f0b704075871aa";
inline const std::string walletdat_pub2_hex = "02466d7fcae563e5cb09a0d1870bb580344804617879a14949cf22285f1bae3f27";
}
