#pragma once
// GENERATED by gen_subthreshold_canonical.py — do not edit by hand.
// Frozen golden vector for v37_subthreshold_estimator_test.cpp.
#include <array>
#include <cstdint>
#include <string>
namespace c2pool::v37::subthreshold::golden {
inline constexpr const char* STAMP = "6634ba0b40c6f1127938c053eeea499939c5e2e32ace8514988c06bbfe0f4a29";
inline constexpr const char* JSON_FILE = "subthreshold_estimator_golden_v1.json";
struct EstRow { unsigned K; const char* h_K_hex; const char* Hhat_dec; };
inline const EstRow ESTIMATE[] = {
  {3, "00003254e6e221c8a7a41e57d9dba908a265f0f5a1016ce789e774eebf65dbfc", "666666"},
  {4, "0000431bde82d7b634dad31fcd24e160d887ebf22c01e68a0d349be8ff327aa6", "749999"},
  {8, "00008637bd05af6c69b5a63f9a49c2c1b10fd7e45803cd141a6937d1fe64f54d", "874999"},
  {16, "00010c6f7a0b5ed8d36b4c7f34938583621fafc8b0079a2834d26fa3fcc9ea9a", "937499"},
  {32, "000218def416bdb1a6d698fe69270b06c43f5f91600f345069a4df47f993d534", "968749"},
};
struct CombRow { unsigned long long S; unsigned K; const char* h_K_hex; const char* Hcomb_dec; };
inline const CombRow COMBINED[] = {
  {0ULL, 4, "0000431bde82d7b634dad31fcd24e160d887ebf22c01e68a0d349be8ff327aa6", "749999"},
  {1ULL, 4, "0000431bde82d7b634dad31fcd24e160d887ebf22c01e68a0d349be8ff327aa6", "999999"},
  {5ULL, 4, "0000431bde82d7b634dad31fcd24e160d887ebf22c01e68a0d349be8ff327aa6", "1999999"},
  {50ULL, 4, "0000431bde82d7b634dad31fcd24e160d887ebf22c01e68a0d349be8ff327aa6", "13249999"},
  {0ULL, 8, "00008637bd05af6c69b5a63f9a49c2c1b10fd7e45803cd141a6937d1fe64f54d", "874999"},
  {1ULL, 8, "00008637bd05af6c69b5a63f9a49c2c1b10fd7e45803cd141a6937d1fe64f54d", "999999"},
  {5ULL, 8, "00008637bd05af6c69b5a63f9a49c2c1b10fd7e45803cd141a6937d1fe64f54d", "1499999"},
  {50ULL, 8, "00008637bd05af6c69b5a63f9a49c2c1b10fd7e45803cd141a6937d1fe64f54d", "7124999"},
};
struct CensRow { unsigned K; const char* h_K_hex; const char* h_T_hex; const char* corrected_dec; };
inline const CensRow CENSORING[] = {
  {3, "00003254e6e221c8a7a41e57d9dba908a265f0f5a1016ce789e774eebf65dbfc", "000008637bd05af6c69b5a63f9a49c2c1b10fd7e45803cd141a6937d1fe64f54", "799999"},
  {4, "0000431bde82d7b634dad31fcd24e160d887ebf22c01e68a0d349be8ff327aa6", "000008637bd05af6c69b5a63f9a49c2c1b10fd7e45803cd141a6937d1fe64f54", "857142"},
  {8, "00008637bd05af6c69b5a63f9a49c2c1b10fd7e45803cd141a6937d1fe64f54d", "000008637bd05af6c69b5a63f9a49c2c1b10fd7e45803cd141a6937d1fe64f54", "933333"},
  {16, "00010c6f7a0b5ed8d36b4c7f34938583621fafc8b0079a2834d26fa3fcc9ea9a", "000008637bd05af6c69b5a63f9a49c2c1b10fd7e45803cd141a6937d1fe64f54", "967741"},
  {32, "000218def416bdb1a6d698fe69270b06c43f5f91600f345069a4df47f993d534", "000008637bd05af6c69b5a63f9a49c2c1b10fd7e45803cd141a6937d1fe64f54", "984126"},
};
struct StrRow { unsigned K; unsigned long long num; unsigned long long den; };
inline const StrRow STRADDLE[] = {
  {3, 7ULL, 5ULL},
  {4, 10ULL, 7ULL},
  {8, 22ULL, 15ULL},
};
struct ClampRef { unsigned K; unsigned long long S; const char* h_K_hex; const char* h_T_hex;
                  const char* clamp_broken_dec; const char* combined_dec; const char* estimate_dec; };
inline const ClampRef CLAMP_NEG = {4, 500000ULL, "0000431bde82d7b634dad31fcd24e160d887ebf22c01e68a0d349be8ff327aa6", "000008637bd05af6c69b5a63f9a49c2c1b10fd7e45803cd141a6937d1fe64f54", "1000000000000", "125000749999", "749999"};
inline constexpr const char* PAYEEB_CREDIT_LOW63_DEC = "874999";
inline constexpr const char* OWED_DIGEST_GATE_OFF_HEX = "8bbcd5bda9d5b167d2ddddfdea379ee858464b43313763744cdb704a1ec54c00";
inline constexpr const char* OWED_DIGEST_GATE_ON_HEX  = "86c9c810203c0bf605b007ecafc1d32bb9f61752b9338ac7e743402e464bc7c4";
}  // namespace
