#include "ConfigSerializer.hpp"
#include "PageLaunch.hpp"

#include <QFile>
#include <QSettings>
#include <QTextStream>

// ─────────────────────────────────────────────────────────────────────────────
// YAML parser (flat subset)
// ─────────────────────────────────────────────────────────────────────────────

ConfigSerializer::ConfigMap ConfigSerializer::loadYaml(const QString& filePath)
{
    ConfigMap map;
    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return map;

    QTextStream in(&file);
    QString currentKey;
    QStringList currentList;
    bool inList = false;

    while (!in.atEnd()) {
        QString line = in.readLine();

        // Strip comments (but not inside quoted strings -- simple approach)
        const int hashPos = line.indexOf('#');
        if (hashPos >= 0 && (hashPos == 0 || line[hashPos - 1] == ' '))
            line = line.left(hashPos);

        const QString trimmed = line.trimmed();
        if (trimmed.isEmpty())
            continue;

        // List item: "  - value"
        if (trimmed.startsWith("- ") && inList) {
            currentList << trimmed.mid(2).trimmed();
            continue;
        }

        // If we were collecting a list, save it
        if (inList) {
            map[currentKey] = QVariant(currentList);
            currentList.clear();
            inList = false;
        }

        // Key: value pair
        const int colonPos = trimmed.indexOf(':');
        if (colonPos < 0)
            continue;

        const QString key = trimmed.left(colonPos).trimmed();
        const QString val = trimmed.mid(colonPos + 1).trimmed();

        if (val.isEmpty()) {
            // Might be start of a list
            currentKey = key;
            inList = true;
            continue;
        }

        // Parse value types
        if (val == "true" || val == "True" || val == "TRUE")
            map[key] = true;
        else if (val == "false" || val == "False" || val == "FALSE")
            map[key] = false;
        else {
            bool okInt = false;
            const int intVal = val.toInt(&okInt);
            if (okInt) {
                map[key] = intVal;
            } else {
                bool okDouble = false;
                const double dblVal = val.toDouble(&okDouble);
                if (okDouble && val.contains('.'))
                    map[key] = dblVal;
                else
                    map[key] = val;  // String
            }
        }
    }

    // Flush last list
    if (inList && !currentKey.isEmpty())
        map[currentKey] = QVariant(currentList);

    return map;
}

// ─────────────────────────────────────────────────────────────────────────────
// YAML emitter (flat subset)
// ─────────────────────────────────────────────────────────────────────────────

bool ConfigSerializer::saveYaml(const ConfigMap& config, const QString& filePath)
{
    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate))
        return false;

    QTextStream out(&file);
    out << "# c2pool configuration (generated by c2pool-qt)\n\n";

    for (auto it = config.constBegin(); it != config.constEnd(); ++it) {
        const QString& key = it.key();
        const QVariant& val = it.value();

        if (val.typeId() == QMetaType::QStringList) {
            const auto list = val.toStringList();
            if (list.isEmpty())
                continue;
            out << key << ":\n";
            for (const auto& item : list)
                out << "  - " << item << "\n";
        } else if (val.typeId() == QMetaType::Bool) {
            out << key << ": " << (val.toBool() ? "true" : "false") << "\n";
        } else if (val.typeId() == QMetaType::Double) {
            out << key << ": " << QString::number(val.toDouble(), 'f', 4) << "\n";
        } else if (val.typeId() == QMetaType::Int) {
            out << key << ": " << val.toInt() << "\n";
        } else {
            const QString str = val.toString();
            if (!str.isEmpty())
                out << key << ": " << str << "\n";
        }
    }

    return true;
}

// ─────────────────────────────────────────────────────────────────────────────
// PageLaunch bridge
// ─────────────────────────────────────────────────────────────────────────────

ConfigSerializer::ConfigMap ConfigSerializer::fromPageLaunch(const PageLaunch* page)
{
    // Build the command to get all the values, then parse them back.
    // Alternatively, we use the buildCommand() to get the effective config
    // and transform it. For now, use buildCommand's display string as a
    // serialized form. The proper approach is to expose getters from PageLaunch,
    // but that requires adding many accessor methods.
    //
    // Since PageLaunch already serializes to QSettings, we read from QSettings.
    ConfigMap map;
    QSettings s;
    s.beginGroup("launch");
    const auto keys = s.childKeys();
    for (const auto& key : keys) {
        map[key] = s.value(key);
    }
    s.endGroup();
    return map;
}

void ConfigSerializer::toPageLaunch(const ConfigMap& config, PageLaunch* page)
{
    // Write the config map into QSettings "launch/" group, then call loadSettings.
    QSettings s;
    s.beginGroup("launch");
    for (auto it = config.constBegin(); it != config.constEnd(); ++it) {
        s.setValue(it.key(), it.value());
    }
    s.endGroup();
    page->loadSettings();
}
