// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026, The c2pool developers (frstrtr/c2pool)
//
// This file is part of c2pool and is distributed under the terms of the GNU
// Affero General Public License, version 3 or (at your option) any later
// version. See COPYING in the repository root.
//
// ---------------------------------------------------------------------------
// src/impl/xmr/test/cross-impl-goldens/gen_xmr_goldens.cpp
//   XMR-lane (Family B) golden-vector GENERATOR — the analogue of
//   tools/gen_decay_canonical.py. A one-shot developer tool (NOT a CI target):
//   it recomputes every captured XMR-lane output through the merged consensus
//   primitives (xmr_goldens_compute.hpp) and emits the frozen golden artifacts:
//
//       ./gen_xmr_goldens          -> prints xmr_lane_goldens_golden.hpp to stdout
//       ./gen_xmr_goldens --json   -> prints the xmr_lane_goldens.json manifest
//
//   Regenerate ONLY after a deliberate, reviewed change to a captured output;
//   the load-bearing gate is xmr_goldens_kat, which compares the live recompute
//   to the emitted header.
// ---------------------------------------------------------------------------
#include <cstdio>
#include <cstring>
#include <string>

#include "xmr_goldens_compute.hpp"

using namespace xmr_goldens;

// Emit the (long) carrier byte string wrapped at a fixed hex-pair boundary so
// the checked-in header stays diff-friendly (adjacent literals concatenate).
static void emit_wrapped(const std::string& hexstr) {
    const std::size_t per = 76; // even
    std::size_t i = 0;
    while (i < hexstr.size()) {
        std::size_t n = (hexstr.size() - i < per) ? (hexstr.size() - i) : per;
        std::printf("    \"%.*s\"\n", (int)n, hexstr.data() + i);
        i += n;
    }
}

static void emit_header(const XmrGoldens& g) {
    std::printf(
"// SPDX-License-Identifier: AGPL-3.0-or-later\n"
"// Copyright (c) 2026, The c2pool developers (frstrtr/c2pool)\n"
"//\n"
"// This file is part of c2pool and is distributed under the terms of the GNU\n"
"// Affero General Public License, version 3 or (at your option) any later\n"
"// version. See COPYING in the repository root.\n"
"//\n"
"// ---------------------------------------------------------------------------\n"
"// src/impl/xmr/test/cross-impl-goldens/xmr_lane_goldens_golden.hpp\n"
"//   FROZEN golden vectors for the XMR/RandomX v37 lane (Family B) -- the\n"
"//   Family-B analogue of proto/refimpl/golden/decay_table_canonical_golden_v1.\n"
"//   GENERATED by gen_xmr_goldens.cpp; do not hand-edit. LOAD-BEARING: the\n"
"//   xmr_goldens_kat recomputes each value live and byte-compares it here, so a\n"
"//   code change that shifts any captured XMR-lane output turns the KAT red.\n"
"//   Cross-anchors: G2_D == monero tests/crypto/tests.txt vector 1; G1 bits ==\n"
"//   the hand-verified accept/reject column of xmr_difficulty_kat.\n"
"// ---------------------------------------------------------------------------\n"
"#pragma once\n"
"\n"
"#include <cstddef>\n"
"#include <cstdint>\n"
"\n"
"namespace xmr_goldens {\n"
"namespace golden {\n"
"\n");
    std::printf("inline constexpr char G1_DIFFICULTY_BITS[] = \"%s\";\n\n", g.g1_bits.c_str());
    std::printf("inline constexpr char        G2_D[]   = \"%s\";\n", g.g2_D.c_str());
    std::printf("inline constexpr char        G2_P0[]  = \"%s\";\n", g.g2_P0.c_str());
    std::printf("inline constexpr std::uint8_t G2_VT0  = 0x%02x;\n\n", g.g2_vt0);
    std::printf("inline constexpr char G3_R[]       = \"%s\";\n", g.g3_r.c_str());
    std::printf("inline constexpr char G3_R_PUB[]   = \"%s\";\n", g.g3_R.c_str());
    std::printf("inline constexpr char G3_MM_ROOT[] = \"%s\";\n", g.g3_mm_root.c_str());
    std::printf("inline constexpr char G3_PCB0[]    = \"%s\";\n\n", g.g3_Pcb.c_str());
    std::printf("inline constexpr char        G4_CHEAP_ID[]    = \"%s\";\n", g.g4_cheap_id.c_str());
    std::printf("inline constexpr std::size_t G4_WIRE_SIZE     = %zu;\n", g.g4_wire_size);
    std::printf("inline constexpr char        G4_INFO_DIGEST[] = \"%s\";\n\n", g.g4_info_digest.c_str());
    std::printf("inline constexpr std::size_t G5_LEN      = %zu;\n", g.g5_len);
    std::printf("inline constexpr char        G5_DIGEST[] = \"%s\";\n", g.g5_digest.c_str());
    std::printf("inline constexpr char        G5_BYTES[]  =\n");
    emit_wrapped(g.g5_bytes);
    std::printf("    ;\n\n");
    std::printf("} // namespace golden\n} // namespace xmr_goldens\n");
}

static void emit_json(const XmrGoldens& g) {
    std::printf("{\n");
    std::printf("  \"_provenance\": \"XMR-lane (Family B) golden vectors; regenerated by gen_xmr_goldens.cpp\",\n");
    std::printf("  \"g1_difficulty_bits\": \"%s\",\n", g.g1_bits.c_str());
    std::printf("  \"g2_stealth\": { \"D\": \"%s\", \"P0\": \"%s\", \"view_tag0\": \"%02x\" },\n",
                g.g2_D.c_str(), g.g2_P0.c_str(), g.g2_vt0);
    std::printf("  \"g3_coinbase\": { \"r\": \"%s\", \"R\": \"%s\", \"mm_root\": \"%s\", \"P_cb0\": \"%s\" },\n",
                g.g3_r.c_str(), g.g3_R.c_str(), g.g3_mm_root.c_str(), g.g3_Pcb.c_str());
    std::printf("  \"g4_receipt\": { \"cheap_id_A\": \"%s\", \"wire_size_A\": %zu, \"info_digest_A\": \"%s\" },\n",
                g.g4_cheap_id.c_str(), g.g4_wire_size, g.g4_info_digest.c_str());
    std::printf("  \"g5_carrier\": { \"len\": %zu, \"digest\": \"%s\", \"bytes\": \"%s\" }\n",
                g.g5_len, g.g5_digest.c_str(), g.g5_bytes.c_str());
    std::printf("}\n");
}

int main(int argc, char** argv) {
    XmrGoldens g = compute_xmr_goldens();
    if (argc > 1 && std::strcmp(argv[1], "--json") == 0) emit_json(g);
    else emit_header(g);
    return 0;
}
