// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026, The c2pool developers (frstrtr/c2pool)
//
// This file is part of c2pool and is distributed under the terms of the GNU
// Affero General Public License, version 3 or (at your option) any later
// version. See COPYING in the repository root.
//
// ---------------------------------------------------------------------------
// src/impl/xmr/test/cross-impl-goldens/xmr_lane_goldens_golden.hpp
//   FROZEN golden vectors for the XMR/RandomX v37 lane (Family B) -- the
//   Family-B analogue of proto/refimpl/golden/decay_table_canonical_golden_v1.
//   GENERATED by gen_xmr_goldens.cpp; do not hand-edit. LOAD-BEARING: the
//   xmr_goldens_kat recomputes each value live and byte-compares it here, so a
//   code change that shifts any captured XMR-lane output turns the KAT red.
//   Cross-anchors: G2_D == monero tests/crypto/tests.txt vector 1; G1 bits ==
//   the hand-verified accept/reject column of xmr_difficulty_kat.
// ---------------------------------------------------------------------------
#pragma once

#include <cstddef>
#include <cstdint>

namespace xmr_goldens {
namespace golden {

inline constexpr char G1_DIFFICULTY_BITS[] = "11010110110";

inline constexpr char        G2_D[]   = "4e0bd2c41325a1b89a9f7413d4d05e0a5a4936f241dccc3c7d0c539ffe00ef67";
inline constexpr char        G2_P0[]  = "5bcf24e93e1516509c8754ec674d926532e3f8ccf75642df68edabc298920144";
inline constexpr std::uint8_t G2_VT0  = 0xb6;

inline constexpr char G3_R[]       = "c1b573ecf87010e212c61c98c1b439d4e856acf5fa3a222d012e473b23184a0a";
inline constexpr char G3_R_PUB[]   = "0a4ea2c0487075d5245befe1c0934996831c6494657152a3c02c78453b2fd8fa";
inline constexpr char G3_MM_ROOT[] = "42ddbd091639cf33c8a3907a2662c0a9388d24a85f63e7fde8ab45b90426e4f2";
inline constexpr char G3_PCB0[]    = "92e8c5614c84c918543d75ec637ec3224ad365ce1ac2b4ea6471ab574e04b038";

inline constexpr char        G4_CHEAP_ID[]    = "105ca31eb53822f8bcb6ec640d9f86184f97f9c9376d11d3a909b4d04f60869e";
inline constexpr std::size_t G4_WIRE_SIZE     = 417;
inline constexpr char        G4_INFO_DIGEST[] = "fb0e90af35739d697114e46169df1e4260a3e6b2eb19ee632e01abc1791168bc";

inline constexpr std::size_t G5_LEN      = 835;
inline constexpr char        G5_DIGEST[] = "cea3dba7b52e81f53c7fc53d5ec89ea06d0d5ec3e1e9790a36285ed79633b8b6";
inline constexpr char        G5_BYTES[]  =
    "524d58374c101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f30"
    "3132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f50515253545556"
    "5758595a5b00303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f"
    "505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475"
    "767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f909192939495969798999a9b"
    "9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1"
    "c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7"
    "e8e9eaebecedeeeff0f1f2f3f4f5f6f705deadbeef1021010a4ea2c0487075d5245befe1c093"
    "4996831c6494657152a3c02c78453b2fd8fa0211705a512e6a895da089ea55a81fb127b87794"
    "fd4c3fa6a906ac2dd976005d8cc7a25af6995b2cab7275f2cf622641407d56a8983f4567b8d5"
    "cf71b89f2ee16afb0e90af35739d697114e46169df1e4260a3e6b2eb19ee632e01abc1791168"
    "bc014c404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162"
    "636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838485868788"
    "898a8b00c0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1"
    "e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff0001020304050607"
    "08090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d"
    "2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f50515253"
    "5455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f70717273747576777879"
    "7a7b7c7d7e7f808182838485868705deadbeef4021010a4ea2c0487075d5245befe1c0934996"
    "831c6494657152a3c02c78453b2fd8fa0211705a512e6a895da089ea55a81fb127b87794fd4c"
    "3fa6a906ac2dd976005d8cc7a25af6995b2cab7275f2cf622641407d56a8983f4567b8d5cf71"
    "b89f2ee16a2623eb940b0d2ecb852ab6b9b913bbd9a2272edf11cf9403e0d3e94486dcb8f3"
    ;

} // namespace golden
} // namespace xmr_goldens
