// SPDX-License-Identifier: AGPL-3.0-or-later
#pragma once

// Build-time version header (generated by the c2pool_version_header CMake
// target). Guarded so a manual compile without the generated include dir still
// builds; the existing C2POOL_VERSION #ifdef guard below then applies.
#if __has_include(<c2pool_build_version.h>)
#include <c2pool_build_version.h>
#endif

// BCH pool run-loop ENTRYPOINT standup -- broadcaster-gate leg C, pool side
// (integrator 2026-06-18: "NodeImpl + EmbeddedDaemon constructed,
// bch::wire_won_block_sink called live").
//
// This is the single production call site the c2pool-bch binary main invokes to
// bring the pool node up WITH its embedded coin daemon and the won-block sink
// already bound. It owns both objects for the lifetime of the run-loop (they
// outlive io_context.run(), so the wire_won_block_sink lambda -- which captures
// the daemon by reference -- never dangles) and enforces the structural half of
// broadcaster-gate criterion C: the won-block sink MUST be live before the
// run-loop accepts shares, or a verified block-meeting share would fire
// m_on_block_found into a null sink and the win would be silently dropped.
//
// G3-slice-b (integrator 2026-06-27): this entrypoint now also stands up the
// miner-facing IWorkSource + Stratum front-end, closing the M5 "no BCH
// IWorkSource served" gap. BCHWorkSource bridges the coin-agnostic
// core::StratumServer to BCH work generation off the embedded daemon's
// HeaderChain + Mempool, and routes a mainnet-hit (share-author) block down the
// SAME dual-path broadcaster the won-block sink uses (embedded P2P primary +
// BCHN submitblock fallback). So the coinbase a genuine share assembles is what
// reaches the network -- not a synthetic solo-cb leg-C block (the slice-a
// caveat). standup_pool_run is the production caller the work_source.hpp Stage-a
// TODO names ("wire StratumServer into standup_pool_run + main_bch.cpp --pool").
//
// Construction + wiring order (matches EmbeddedDaemon::run() contract):
//   1. EmbeddedDaemon(ctx, config, anchor) -- cold-start floor-anchored ABLA.
//   2. daemon.run() -- external BCHN-RPC fallback (init_rpc) + assemble() +
//      ABLA loop + operator-approved cold-start anchor pin. Embedded-primary
//      work source live, external fallback retained (external_fallback law).
//   3. NodeImpl(ctx, config) -- the pool node (sharechain, storage, P2P).
//   4. wire_won_block_sink(node, daemon) -- bind tracker().m_on_block_found ->
//      daemon.broadcast_won_block (dual path: embedded P2P PRIMARY + external
//      BCHN submitblock FALLBACK).
//   5. ASSERT node.has_block_broadcaster() -- the sink is LIVE. This is the
//      structural criterion-C check; throwing here is correct (a missing sink
//      at the production entrypoint is a wiring bug, not a runtime condition).
//   6. BCHWorkSource + core::StratumServer -- miner-facing front-end; a hit
//      block routes through the SAME daemon.broadcast_won_block dual path.
//
// The sink being live is NECESSARY but NOT SUFFICIENT to declare BCH
// block-viable: reconstruct_won_block() still gates on full gentx (coinbase)
// reconstruction, and the dual paths must be proven to FIRE+ACCEPT against a
// live BCHN peer -- the behavioural half of criterion C, a separate e2e slice
// (code-exists != fires).
//
// PER-COIN ISOLATION: src/impl/bch only. p2pool-merged-v36 surface: NONE
// (block dispatch + run-loop bring-up, not share/PPLNS/coinbase/AuxPoW bytes).
// BCH = SHA256d standalone parent.

#include "node.hpp"
#include "pool_standup.hpp"
#include "coin/embedded_daemon.hpp"
#include "stratum/work_source.hpp"
#include "config_pool.hpp"      // bch::PoolConfig::get_donation_script
#include "share_check.hpp"      // bch::create_local_share (transitive via node.hpp)
#include "share_types.hpp"      // bch::StaleInfo
#include "coin/block.hpp"       // bch::coin::SmallBlockHeaderType
#include "coin/block_confirm.hpp" // #995 BCH arm: found-block confirm/orphan resolver

#include <core/pack_types.hpp>    // BaseScript

#include <core/log.hpp>
#include <core/stratum_server.hpp>
#include <core/web_server.hpp>       // H-STATS.944: operator dashboard + graph_db persist
#include <core/config_endpoint.hpp>  // M1 control-plane READ-ONLY endpoints
#include <core/filesystem.hpp>      // config_path() for the graph_db location
#include <functional>
#include <ctime>       // std::time (found-block record timestamp)
#include <limits>       // std::numeric_limits (RPC-fallback sentinel)
#include <optional>     // std::optional (winner_at oracle)

#include <btclibs/util/strencodings.h>   // HexStr

#include <boost/asio/io_context.hpp>
#include <boost/asio/steady_timer.hpp>   // H-STATS.944: periodic save_stat_log timer

#include <chrono>
#include <cstdint>
#include <cstring>
#include <cstdlib>   // std::getenv (BCH_DEMO_SHARE_BITS demo floor)
#include <shared_mutex>
#include <type_traits>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

namespace bch
{

// Stand up the BCH pool node + embedded coin daemon on a shared io_context,
// bind the won-block sink, assert it is live, stand up the miner-facing
// IWorkSource + Stratum front-end, then drive the run-loop.
// `config` and `ioc` outlive this call (owned by the binary entrypoint); the
// daemon, node, work source and stratum server are owned here for the run-loop
// lifetime. `anchor_height` is the cold-start ABLA floor anchor (operator-
// approved VM300 record, floor-equivalent). `stratum_addr`/`stratum_port` are
// the miner-facing bind (port 0 == stratum disabled); `is_testnet` selects the
// BCH network params the work source stamps onto generated work.
// `http_addr`/`http_port` are the operator-facing dashboard bind (port 0 ==
// web disabled); a non-zero port stands up core::WebServer + MiningInterface
// with graph_db stats persistence (H-STATS.944, Option A: built here, not
// inline in main_bch). Returns when the io_context stops.
inline void standup_pool_run(boost::asio::io_context& ioc,
                             Config& config,
                             uint32_t anchor_height,
                             const std::string& stratum_addr = "0.0.0.0",
                             uint16_t stratum_port = 0,
                             bool is_testnet = false,
                             bool is_regtest = false,
                             const std::string& http_addr = "0.0.0.0",
                             uint16_t http_port = 0,
                             size_t explicit_sharechain_peers = 0)
{
    // 1+2: embedded daemon up first -- it owns the work source + RPC fallback
    // the pool node consumes, and is the broadcast sink the node wires into.
    coin::EmbeddedDaemon<Config> daemon(&ioc, &config, anchor_height, is_regtest);
    daemon.run();

    // 3: the pool node (sharechain, LevelDB, P2P, Stratum).
    Node node(&ioc, &config);  // concrete NodeBridge<NodeImpl,Legacy,Actual> -- NodeImpl alone is abstract (ICommunicator::handle lives in NodeBridge)

    // 4: bind the in-operation won-block fire path to the dual-path broadcaster.
    wire_won_block_sink(node, daemon);

    // 5: structural criterion-C gate -- refuse to run shares without a live sink.
    if (!node.has_block_broadcaster()) {
        LOG_FATAL << "[BCH-POOL] won-block sink NOT live after wire_won_block_sink"
                  << " -- refusing to start run-loop (a won block would be dropped).";
        throw std::runtime_error("bch::standup_pool_run: won-block broadcaster sink not wired");
    }

    LOG_INFO << "[BCH-POOL] pool run-loop standup complete: embedded daemon up,"
             << " won-block sink LIVE (dual-path: embedded P2P primary + BCHN"
             << " submitblock fallback). Structural broadcaster-gate criterion-C"
             << " satisfied; live VM300 e2e is the behavioural half.";

    // 5b: SHARECHAIN LISTENER + OUTBOUND DIAL (contabo BCH revival FIX).
    // Until now this entrypoint stood up NO sharechain listener and NEVER called
    // start_outbound_connections(), so the node had 0 sharechain peers forever
    // (no :9349 LISTEN, addrs never dialed). Bind the pool P2P listener on
    // P2P_PORT (9349) and start the outbound dial loop that consumes the addr
    // store seeded from m_bootstrap_addrs (run_pool). node inherits
    // core::Server via BaseNode : core::Factory<core::Server, core::Client>
    // (src/pool/node.hpp), so node.core::Server::listen(...) resolves exactly as
    // in main_dgb.cpp:678 / main_btc.cpp:1638. When explicit --sharechain-addnode
    // peers were pinned, raise the outbound target to at least that count so all
    // pins are dialed (default m_target_outbound_peers = 8 otherwise).
    if (explicit_sharechain_peers)
        node.set_target_outbound_peers(std::max<size_t>(1, explicit_sharechain_peers));
    node.core::Server::listen(PoolConfig::P2P_PORT);
    LOG_INFO << "[BCH-POOL] sharechain listening :" << PoolConfig::P2P_PORT
             << " proto adv=" << PoolConfig::ADVERTISED_PROTOCOL_VERSION
             << " min=" << PoolConfig::MINIMUM_PROTOCOL_VERSION
             << " prefix=" << PoolConfig::prefix_hex();
    node.start_outbound_connections();
    LOG_INFO << "[BCH-POOL] outbound sharechain dialing started ("
             << config.pool()->m_bootstrap_addrs.size() << " bootstrap addr(s))";

    // 6: miner-facing IWorkSource + Stratum front-end. BCHWorkSource generates
    // work off the embedded daemon's HeaderChain + Mempool (SHA256d, no-segwit,
    // CashTokens transparent-carry), and routes a mainnet-hit block through the
    // SAME dual-path broadcaster (embedded P2P primary + BCHN submitblock
    // fallback) the won-block sink uses -- so the share-author coinbase reaches
    // the network down both legs. Held here so the shared_ptr + server outlive
    // ioc.run() alongside the daemon they reference.
    auto work_source = std::make_shared<stratum::BCHWorkSource>(
        daemon.chain(),
        daemon.mempool(),
        is_testnet,
        [&daemon](const std::vector<unsigned char>& block_bytes,
                  uint32_t /*height*/) -> bool {
            // Genuine share-author block -> dual-path broadcaster. block_hex for
            // the BCHN submitblock fallback is HexStr(block_bytes). True iff at
            // least one sink accepted (embedded P2P relay OR external RPC).
            coin::BlockBroadcast r =
                daemon.broadcast_won_block(block_bytes, HexStr(block_bytes));
            return r.any();
        });

    // ── Sharechain WRITE path: local-share author wiring ─────────────────
    // Without these callbacks BCHWorkSource accepts miner submissions that
    // clear the sharechain target but DROPS them ("accepted (no-tracker)",
    // work_source.cpp:686) because create_share_fn_ is null -- c2pool-bch runs
    // as a bare stratum proxy and Stored shares stay stuck at 0. This block
    // closes that gap (mirrors main_btc.cpp:863/1118), wiring the three
    // callbacks the local-author path needs:
    //   - best_share_hash_fn : new-job prev_share = our sharechain tip
    //   - donation_script    : version-gated coinbase residual recipient
    //   - create_share_fn    : mining_submit -> bch::create_local_share ->
    //                          tracker.add -> broadcast_share + notify_local_share
    // BCH is a STANDALONE SHA256d parent: no segwit, no merged/aux dimension
    // (merged_addrs = {}, segwit_active=false, witness_* empty). ref_hash_fn /
    // pplns_fn are a FOLLOW-UP slice -- they gate peer-verifiable ref_hash +
    // PPLNS payout distribution, NOT local Stored accumulation; until wired,
    // build_connection_coinbase falls back to a single-output coinbase and
    // create_local_share computes its own share target via
    // tracker.compute_share_target (has_frozen=false).
    work_source->set_best_share_hash_fn(
        [&node]() -> uint256 { return node.best_share_hash(); });

    // Work-source donation MUST match the authored share version, and both must
    // match the LIVE jtoomim-BCH net -- BCH is a CROSSING coin. Shares author at
    // CROSSING_FLOOR_VERSION (what the live net mints), and the donation served
    // in the miner-hashed template is the floor script (sub-36 -> forrestv P2PK).
    // generate_share_transaction rebuilds the coinbase donation under the SAME
    // authored version, so template-donation and verify-rebuild are byte-identical
    // -- closing the byte-offset-104 recompute/GENTX divergence WITHOUT forking
    // off the live net (authoring v36 from genesis would). The 60%-by-work auto-
    // ratchet (#326/#577) advances author + donation together once the tip>=36.
    work_source->set_donation_script(PoolConfig::get_donation_script(PoolConfig::CROSSING_FLOOR_VERSION));

    // -- ref_hash_fn: peer-verifiable share commitment (G2 conform) --------
    // Without this the local-author coinbase carries NO p2pool OP_RETURN
    // ref_hash (build_connection_coinbase gates the OP_RETURN on ref_hash_fn
    // being set) and create_local_share runs has_frozen=false -- so every
    // share we author is systematically non-peer-verifiable: the recomputed
    // ref_hash never equals the stored one (100% verify_share mismatch).
    // This lambda produces the ref_hash AND the chain-walked snapshot
    // (bits/max_bits from compute_share_target, absheight/abswork/
    // far_share_hash off the prev walk, clipped timestamp) that populates
    // snap.frozen_ref; mining_submit threads it back into create_local_share
    // (has_frozen=true) so the create-side reconstruction is byte-exact.
    // Mirrors main_btc.cpp:920 and the chain-position math of
    // create_local_share_v35 (share_check.hpp:2724); BCH is standalone
    // SHA256d -- no segwit, no merged dimension.
    work_source->set_ref_hash_fn(
        [&node](const uint256& prev_share_hash,
                const std::vector<unsigned char>& scriptSig,
                const std::vector<unsigned char>& payout_script,
                uint64_t subsidy, uint32_t block_bits, uint32_t timestamp)
        -> core::stratum::RefHashResult
        {
            core::stratum::RefHashResult result;
            result.share_version   = PoolConfig::CROSSING_FLOOR_VERSION;   // crossing-floor SSOT (ratchet-current genesis default)
            result.desired_version = core::version_gate::V36_ACTIVATION_VERSION;   // vote to ratchet toward v36

            bch::RefHashParams p;
            p.share_version      = PoolConfig::CROSSING_FLOOR_VERSION;   // crossing-floor author version (SSOT)
            p.prev_share         = prev_share_hash;
            p.coinbase_scriptSig = scriptSig;
            p.share_nonce        = 0;
            p.subsidy            = subsidy;
            p.donation           = 50;      // 0.5% finder fee (matches create side)
            p.stale_info         = 0;
            p.desired_version    = core::version_gate::V36_ACTIVATION_VERSION;   // vote to ratchet toward v36
            p.has_segwit         = false;   // BCH: never segwit
            p.timestamp          = timestamp;

            // Pubkey extract mirrors create_local_share_v35 (share_check.hpp
            // ~2600): P2PKH / P2SH / P2WPKH, so p.pubkey_hash + p.pubkey_type
            // feed the ref-stream identically on both sides.
            if (payout_script.size() == 25 && payout_script[0] == 0x76 &&
                payout_script[1] == 0xa9 && payout_script[2] == 0x14 &&
                payout_script[23] == 0x88 && payout_script[24] == 0xac) {
                std::memcpy(p.pubkey_hash.begin(), payout_script.data() + 3, 20);
                p.pubkey_type = 0;
            } else if (payout_script.size() == 23 && payout_script[0] == 0xa9 &&
                       payout_script[1] == 0x14 && payout_script[22] == 0x87) {
                std::memcpy(p.pubkey_hash.begin(), payout_script.data() + 2, 20);
                p.pubkey_type = 2;
            } else if (payout_script.size() == 22 && payout_script[0] == 0x00 &&
                       payout_script[1] == 0x14) {
                std::memcpy(p.pubkey_hash.begin(), payout_script.data() + 2, 20);
                p.pubkey_type = 1;
            }

            auto block_bits_fallback = [&] {
                p.bits = block_bits;  p.max_bits = block_bits;
            };

            // Read-only chain walk (shared lock; the compute thread holds the
            // exclusive lock and never runs on this stratum thread).
            {
                std::shared_lock<std::shared_mutex> lk(node.tracker_mutex());
                auto& tracker = node.tracker();

                const bool have_prev = !prev_share_hash.IsNull() &&
                                       tracker.chain.contains(prev_share_hash);

                // share_version off the prev tip (matches create_ver); cold
                // start stays v35 voting v36.
                if (have_prev) {
                    tracker.chain.get(prev_share_hash).share.invoke([&](auto* s) {
                        using ST = std::remove_pointer_t<decltype(s)>;
                        p.share_version = ST::version;
                    });
                }

                // absheight + clipped timestamp off prev.
                if (have_prev) {
                    tracker.chain.get(prev_share_hash).share.invoke([&](auto* prev) {
                        p.absheight = prev->m_absheight + 1;
                        if (p.timestamp <= prev->m_timestamp)
                            p.timestamp = prev->m_timestamp + 1;
                    });
                } else {
                    p.absheight = 1;   // genesis
                }

                // share_target with the clipped timestamp (same call
                // create_local_share_v35 makes).
                try {
                    auto st = tracker.compute_share_target(
                        prev_share_hash, p.timestamp,
                        chain::bits_to_target(block_bits));
                    p.bits = st.bits;  p.max_bits = st.max_bits;
                } catch (const std::exception&) {
                    block_bits_fallback();
                }
                // Cold start: compute_share_target's genesis branch yields
                // bits==0 while max_bits carries the MAX_TARGET floor. Pin
                // p.bits to the floor so the ref_hash, the frozen field, and
                // share_bits_ all agree (else recomputed != stored).
                if (p.bits == 0 && p.max_bits != 0)
                    p.bits = p.max_bits;

                // [ISOLATED-NET DEMO / G2] Mirror work_source's
                // BCH_DEMO_SHARE_BITS floor here so the ref_hash, the frozen
                // field, and the core pool_difficulty gate all read ONE share
                // target on a CPU-grind isolated net. Without it ref_hash_fn
                // reports compute_share_target's ~diff-1 floor -- unclearable
                // by a CPU grinder -- so no submission is ever promoted to a
                // STORED share and recomputed==stored can't be observed.
                // OFF unless the env var is set; never active on normal or
                // mainnet runs. BCH-local (fenced to the BCH tree).
                if (const char* e = std::getenv("BCH_DEMO_SHARE_BITS"); e && *e) {
                    uint32_t demo = static_cast<uint32_t>(std::strtoul(e, nullptr, 16));
                    if (demo) { p.bits = demo; p.max_bits = demo; }
                }

                // abswork = prev_abswork + attempts(this share's bits).
                {
                    auto att = chain::target_to_average_attempts(
                        chain::bits_to_target(p.bits));
                    if (have_prev) {
                        uint128 prev_abswork;
                        tracker.chain.get(prev_share_hash).share.invoke(
                            [&](auto* prev) { prev_abswork = prev->m_abswork; });
                        p.abswork = prev_abswork + uint128(att.GetLow64());
                    } else {
                        p.abswork = uint128(att.GetLow64());
                    }
                }

                // far_share_hash: 99th ancestor, mirroring create_local_share
                // _v35's get_height_and_last rule exactly.
                if (have_prev) {
                    auto [prev_height, last] =
                        tracker.chain.get_height_and_last(prev_share_hash);
                    if (last.IsNull() && prev_height < 99) {
                        p.far_share_hash = uint256();
                    } else {
                        try {
                            p.far_share_hash =
                                tracker.chain.get_nth_parent_key(prev_share_hash, 99);
                        } catch (const std::exception&) {
                            // Bootstrap short chain: degrade to far=None instead of
                            // throwing out of ref_hash_fn (which would zero frozen_ref
                            // and force the create-side into its own unguarded walk).
                            p.far_share_hash = uint256();
                        }
                    }
                } else {
                    p.far_share_hash = uint256();
                }
            }

            // Mirror the walked values into the result for snap.frozen_ref.
            result.share_version   = p.share_version;
            result.desired_version = p.desired_version;
            result.bits            = p.bits;
            result.max_bits        = p.max_bits;
            result.timestamp       = p.timestamp;
            result.absheight       = p.absheight;
            result.abswork         = p.abswork;
            result.far_share_hash  = p.far_share_hash;

            try {
                auto [rh, nn] = bch::compute_ref_hash_for_work(p);
                result.ref_hash         = rh;
                result.last_txout_nonce = nn;
            } catch (const std::exception& e) {
                LOG_WARNING << "[BCH-STRATUM] compute_ref_hash_for_work threw: "
                            << e.what() << " -- coinbase will lack OP_RETURN";
            }
            return result;
        });

    LOG_INFO << "[BCH-STRATUM] ref_hash_fn wired (walks share tracker for"
             << " share_target/absheight/abswork/far_share; emits p2pool"
             << " OP_RETURN ref_hash + freezes the snapshot for byte-exact"
             << " create-side reconstruction).";

    // Local-share -> stratum work-refresh bridge (BCH-side wiring; the refresh
    // mechanism itself lives unchanged in core StratumServer::notify_all(),
    // which re-polls best_share_hash_fn and pushes a clean mining.notify with
    // the NEW sharechain tip as prev_share). Without ringing it after each
    // authored share, every miner keeps grinding the job frozen at pool start
    // (prev=genesis), so shares bootstrap off 0000... as orphan siblings and
    // the chain never links past height 1.
    auto stratum_notify = std::make_shared<std::function<void()>>();

    // --- Version-aware PPLNS payout + author-version wiring (finder-fee gate) ---
    // The height-2 verified-tip stall was a share-version vs coinbase-author
    // mismatch: shares stamp at the tip version (35 through a short grind, the
    // ratchet never flips) while the coinbase author produced a v36-pure,
    // finder-fee-less gentx -- so generate_share_transaction (v35 verify path)
    // rejected every non-genesis share. Fix: select the PPLNS shape at the tip
    // version and (in build_connection_coinbase) apply the sub-36 finder fee.
    // The v35 walk (flat weights, grandparent start, 199/200) and the v36 walk
    // (decayed, exponential window, pure) yield DIFFERENT integer amounts
    // (division order), so shape must be chosen at weight->amount time, never
    // haircut afterward. Ref: share_check.hpp use_v36_pplns.
    auto derive_author_version = [&node]() -> int64_t {
        int64_t ver = 35;
        uint256 tip = node.best_share_hash();
        std::shared_lock<std::shared_mutex> lk(node.tracker_mutex());
        if (!tip.IsNull() && node.tracker().chain.contains(tip)) {
            node.tracker().chain.get_share(tip).invoke(
                [&](auto* s) {
                    using ST = std::remove_pointer_t<decltype(s)>;
                    ver = ST::version;
                });
        }
        return ver;
    };
    work_source->set_author_version_fn(derive_author_version);

    work_source->set_pplns_fn(
        [&node](const uint256& best_share_hash,
                const uint256& block_target,
                uint64_t subsidy,
                const std::vector<unsigned char>& donation_script)
            -> std::map<std::vector<unsigned char>, double>
        {
            // Single read guard: derive the tip version AND walk under the same
            // lock (do NOT call derive_author_version here -- that would take a
            // second shared_lock on the same thread == UB under a waiting writer).
            std::shared_lock<std::shared_mutex> lk(node.tracker_mutex());
            int64_t ver = 35;
            uint256 tip = node.best_share_hash();
            if (!tip.IsNull() && node.tracker().chain.contains(tip)) {
                node.tracker().chain.get_share(tip).invoke(
                    [&](auto* s) {
                        using ST = std::remove_pointer_t<decltype(s)>;
                        ver = ST::version;
                    });
            }
            if (ver < 36)
                return node.tracker().get_v35_expected_payouts(
                    best_share_hash, block_target, subsidy, donation_script);
            return node.tracker().get_expected_payouts(
                best_share_hash, block_target, subsidy, donation_script);
        });

    work_source->set_create_share_fn(
        [&node, stratum_notify](const std::vector<unsigned char>& full_coinbase,
                const std::vector<uint8_t>&        header_80b,
                const core::stratum::JobSnapshot&  job,
                const std::vector<unsigned char>& payout_script) -> uint256
        {
            if (header_80b.size() != 80) {
                LOG_WARNING << "[BCH-CREATE-SHARE] bad header size=" << header_80b.size();
                return uint256::ZERO;
            }

            // Parse the 80-byte BCH block header -> SmallBlockHeaderType. The
            // merkle_root (bytes 36..67) is reconstructible from coinbase +
            // frozen branches, so it is not stored in min_header.
            auto read_le32 = [](const uint8_t* p) -> uint32_t {
                return uint32_t(p[0]) | (uint32_t(p[1]) << 8)
                     | (uint32_t(p[2]) << 16) | (uint32_t(p[3]) << 24);
            };
            coin::SmallBlockHeaderType min_header;
            min_header.m_version = read_le32(header_80b.data() + 0);
            std::memcpy(min_header.m_previous_block.data(), header_80b.data() + 4, 32);
            min_header.m_timestamp = read_le32(header_80b.data() + 68);
            min_header.m_bits      = read_le32(header_80b.data() + 72);
            min_header.m_nonce     = read_le32(header_80b.data() + 76);

            // full_coinbase is the fully serialized coinbase TRANSACTION, but a
            // share's m_coinbase field must be ONLY the coinbase INPUT scriptSig
            // (BIP34 height + pool marker) -- share_init_verify enforces the
            // consensus 2..100 byte bound. Feeding the whole tx tripped
            // "bad coinbase size" and left every G2 share unverified. Extract the
            // input scriptSig here; the full tx still rides via actual_coinbase_bytes
            // for gentx byte-parity (extranonce lives in an OP_RETURN output, not
            // the scriptSig, so this slice is complete on its own).
            std::vector<unsigned char> coinbase_scriptSig;
            {
                size_t p = 0;
                bool ok = true;
                auto need = [&](size_t n) { return p + n <= full_coinbase.size(); };
                auto rd_varint = [&](uint64_t& out) -> bool {
                    if (!need(1)) return false;
                    uint8_t ch = full_coinbase[p++];
                    if (ch < 253) { out = ch; return true; }
                    size_t n = (ch == 253) ? 2 : (ch == 254) ? 4 : 8;
                    if (!need(n)) return false;
                    out = 0;
                    for (size_t i = 0; i < n; ++i)
                        out |= uint64_t(full_coinbase[p++]) << (8 * i);
                    return true;
                };
                uint64_t vin = 0, slen = 0;
                if (need(4)) p += 4; else ok = false;            // version
                ok = ok && rd_varint(vin) && vin >= 1;           // tx_in count
                if (ok && need(36)) p += 36; else ok = false;    // prevout (32+4)
                ok = ok && rd_varint(slen);                      // scriptSig length
                if (ok && need(slen)) {
                    coinbase_scriptSig.assign(full_coinbase.begin() + p,
                                              full_coinbase.begin() + p + slen);
                } else {
                    LOG_WARNING << "[BCH-CREATE-SHARE] cannot parse coinbase scriptSig from "
                                << full_coinbase.size() << "B tx -- share skipped";
                    return uint256::ZERO;
                }
            }
            BaseScript coinbase_bs(coinbase_scriptSig);

            // Stratum branches are hex of LE-internal bytes -> ParseHex+memcpy
            // (SetHex would byte-reverse and break the merkle root the miner used).
            std::vector<uint256> merkle_branches;
            merkle_branches.reserve(job.merkle_branches.size());
            for (const auto& bhex : job.merkle_branches) {
                uint256 b;
                auto bb = ParseHex(bhex);
                if (bb.size() == 32) std::memcpy(b.begin(), bb.data(), 32);
                merkle_branches.push_back(b);
            }

            // Exclusive tracker lock (non-blocking): defer to the next submit if
            // the compute thread is mid-think rather than freezing the io_context.
            std::unique_lock<std::shared_mutex> lk(node.tracker_mutex(), std::try_to_lock);
            if (!lk.owns_lock()) {
                LOG_INFO << "[BCH-CREATE-SHARE] tracker busy -- share deferred";
                return uint256::ZERO;
            }

            // Author at the current tip's version (35 on an empty chain), voting
            // desired=36. Same-version authoring never trips the 60%-by-work
            // accept gate; the ratchet-driven upgrade to v36 is a follow-up slice.
            // Author at the frozen share_version the ref_hash was computed
            // under (job.frozen_ref.share_version) so the create-side ref
            // reconstruction is byte-exact; fall back to the prev-tip version
            // (cold start: v35 voting v36) when ref_hash_fn produced no frozen
            // data (bits == 0).
            int64_t create_ver = PoolConfig::CROSSING_FLOOR_VERSION;   // crossing-floor default; tip version overrides below (ratchet-current)
            if (job.frozen_ref.bits != 0) {
                create_ver = job.frozen_ref.share_version;
            } else if (!job.prev_share_hash.IsNull() &&
                node.tracker().chain.contains(job.prev_share_hash)) {
                node.tracker().chain.get_share(job.prev_share_hash).invoke(
                    [&](auto* s) {
                        using ST = std::remove_pointer_t<decltype(s)>;
                        create_ver = ST::version;
                    });
            }

            uint256 share_hash;
            try {
                share_hash = bch::create_local_share(
                    node.tracker(), min_header, coinbase_bs,
                    /* subsidy */               job.subsidy,
                    /* prev_share */            job.prev_share_hash,
                    merkle_branches, payout_script,
                    /* donation bps */          50,
                    /* merged_addrs */          {},
                    /* stale_info */            StaleInfo::none,
                    /* segwit_active */         false,        // BCH: no segwit
                    /* witness_commitment */    {},
                    /* message_data */          {},
                    /* actual_coinbase_bytes */ full_coinbase,
                    /* witness_root */          uint256(),
                    /* override_max_bits */     job.share_max_bits,  // pin share target to
                    /* override_bits */         job.share_bits,      // what the miner was issued
                    /* frozen_absheight */      job.frozen_ref.absheight,
                    /* frozen_abswork */        job.frozen_ref.abswork,
                    /* frozen_far_share_hash */ job.frozen_ref.far_share_hash,
                    /* frozen_timestamp */      job.frozen_ref.timestamp,
                    /* frozen_merged_payout */  job.frozen_ref.merged_payout_hash,
                    /* has_frozen */            (job.frozen_ref.bits != 0),
                    /* frozen_merkle_branches*/ job.frozen_ref.frozen_merkle_branches,
                    /* frozen_witness_root */   uint256(),   // BCH: never segwit
                    /* frozen_merged_cb_info */ {},          // BCH: standalone, no merged
                    /* share_version */         create_ver,
                    /* desired_version */       36);
            } catch (const std::exception& e) {
                LOG_WARNING << "[BCH-CREATE-SHARE] threw: " << e.what();
                return uint256::ZERO;
            }

            // Drop the exclusive lock BEFORE broadcast/notify (they take their
            // own locks / post to the io_context).
            lk.unlock();
            if (!share_hash.IsNull()) {
                node.broadcast_share(share_hash);
                node.notify_local_share(share_hash);
                // Ring the stratum work-refresh so the next mining.notify carries
                // the new sharechain tip as prev_share (chain links past height 1).
                if (*stratum_notify) (*stratum_notify)();
                LOG_INFO << "[BCH-CREATE-SHARE] OK + broadcast v" << create_ver
                         << " hash=" << share_hash.GetHex().substr(0, 16);
            }
            return share_hash;
        });

    LOG_INFO << "[BCH-POOL] sharechain WRITE path wired (mining_submit ->"
             << " create_local_share -> broadcast_share + notify_local_share);"
             << " ref_hash/pplns are a follow-up slice.";

    std::unique_ptr<core::StratumServer> stratum_server;
    if (stratum_port != 0) {
        stratum_server = std::make_unique<core::StratumServer>(
            ioc, stratum_addr, stratum_port, work_source);
        if (stratum_server->start()) {
            // Wire the local-share bridge to the now-constructed stratum server.
            *stratum_notify = [srv = stratum_server.get()]() { srv->notify_all(); };

            // Ring the SAME work-refresh on a PARENT-CHAIN new tip, not only on
            // a local share. HeaderChain fires m_on_tip_changed when the BCH tip
            // advances (network block via embedded P2P / RPC fallback); ring
            // stratum_notify so every miner is pushed a fresh mining.notify
            // (clean_jobs) built on the NEW prevhash instead of grinding a stale
            // height-1 template until the next share. cached_template() already
            // rebuilds on a tip_hash change (the poll half); this closes the
            // PUSH half. m_on_tip_changed is single-slot and unused elsewhere in
            // the BCH tree. stratum_notify captured by shared_ptr copy so the
            // sink outlives ioc.run() alongside the daemon that owns the chain.
            daemon.chain().set_on_tip_changed(
                [stratum_notify](const uint256& /*old_tip*/, uint32_t /*old_h*/,
                                 const uint256& new_tip, uint32_t new_h) {
                    if (*stratum_notify) (*stratum_notify)();
                    LOG_INFO << "[BCH-POOL] parent tip -> h=" << new_h << " "
                             << new_tip.GetHex().substr(0, 16)
                             << " : pushed clean mining.notify to miners";
                });
            LOG_INFO << "[BCH-POOL] stratum listening on " << stratum_addr << ":"
                     << stratum_port << " (BCHWorkSource: SHA256d, no-segwit,"
                     << " CashTokens transparent-carry; hit block routes the"
                     << " dual-path broadcaster).";
        } else {
            LOG_ERROR << "[BCH-POOL] stratum FAILED to bind " << stratum_addr << ":"
                      << stratum_port << " -- stratum disabled, daemon run-loop continues.";
            stratum_server.reset();
        }
    } else {
        LOG_INFO << "[BCH-POOL] stratum disabled (no --stratum bind given);"
                 << " embedded daemon run-loop only.";
    }

    // ── Operator-facing dashboard + graph_db stats persistence (H-STATS.944) ─
    // Option A (integrator 2026-08-03): construct core::WebServer INSIDE this
    // factored standup rather than an inline main_bch block, so btc/dgb adopt
    // the SAME shape. ISOLATION: constructs existing core classes only -- ZERO
    // src/core edits -- so this stays OFF the four-coin smoke gate. Held in a
    // unique_ptr at function scope (like stratum_server) so it and its stats
    // timer outlive ioc.run() alongside the daemon/node they observe. node ==
    // nullptr: BCH's Node does not implement core::IMiningNode; the dashboard +
    // graph_db path (share/hashrate stat log) does not require it, and a live
    // IMiningNode adapter is a follow-up slice. Blockchain::BITCOIN selects the
    // SHA256d graph_db constant pairing (BCH has no dedicated enum value; adding
    // one would be a src/core edit == the exceptional four-smoke path, avoided).
    std::unique_ptr<core::WebServer> web_server;
    std::shared_ptr<boost::asio::steady_timer> stats_timer;
    if (http_port != 0) {
        // No-silent-ctor bracket (integrator req #2, per-lane port of ltc #1041).
        // core::WebServer's ctor already logs "core::WebServer constructed on ..."
        // (shared, blockchain= numeric only); these two BCH-namespaced lines make
        // the boot log self-identify THIS lane's dashboard standup on the way in
        // and out, so a ctor that throws mid-standup shows as an unmatched
        // "standing up" with no "constructed" follow-up. src/impl/bch only.
        LOG_INFO << "[BCH-POOL] standing up core::WebServer + MiningInterface (http bind "
                 << http_addr << ":" << http_port << ") ...";
        web_server = std::make_unique<core::WebServer>(
            ioc, http_addr, http_port, is_testnet,
            std::shared_ptr<core::IMiningNode>{},        // no IMiningNode adapter yet
            c2pool::address::Blockchain::BITCOIN);       // SHA256d graph_db pairing
        auto* mi = web_server->get_mining_interface();
        if (mi == nullptr) {
            LOG_ERROR << "[BCH-POOL] core::WebServer constructed but MiningInterface is"
                      << " NULL -- dashboard disabled, run-loop continues.";
            web_server.reset();
        }
        if (mi != nullptr) {
        LOG_INFO << "[BCH-POOL] core::WebServer + MiningInterface constructed (coin=BCH, "
                 << "http " << http_addr << ":" << http_port << "); MiningInterface alive.";
        // Coin identity is set unconditionally — it must not depend on the
        // version macro. BCH runs on Blockchain::BITCOIN, so without this label
        // /node_info would fall back to the enum and advertise bitcoin/BTC on a
        // Bitcoin-Cash pool.
        mi->set_coin_label("BCH");
#ifdef C2POOL_VERSION
        mi->set_pool_version("c2pool/" C2POOL_VERSION);
#endif
        // Control-plane M1 (SAFE): install the READ-ONLY config endpoints
        // (lambdas read the immutable snapshot published in main_bch). POST
        // /api/config/apply stays inert (503); runtime mutation not armed.
        mi->set_config_fns(
            []() { return c2pool::config_endpoint::resolved_config_json(); },
            []() { return c2pool::config_endpoint::catalog_schema_json(); });
        mi->set_io_context(&ioc);
        web_server->set_stratum_port(stratum_port);
        // Advertise the REAL stratum bind as worker_port (was the LTC-template
        // default 9327). The sharechain listener IS now stood up (step 5b above,
        // core::Server::listen(P2P_PORT)), so advertise the real 9349 p2p_port
        // rather than a truthful-0 or a template constant.
        mi->set_worker_port(stratum_port);
        mi->set_p2p_port(PoolConfig::P2P_PORT);

        // Cross-coin dashboard parity: serve the shared refined web-static
        // dashboard over --http (bch.voidbind, same UI as LTC/DASH). This lane
        // passes a NULL IMiningNode, so refresh_work() never fills
        // m_cached_template and the readiness gate (http_session.cpp) would
        // redirect every .html to loading.html forever; mark the dashboard
        // always-ready (mirror main_dash.cpp) and point static serving at
        // web-static so "/" resolves. Display-only — no share/reward/consensus.
        // src/impl/bch only (PER-COIN ISOLATION); zero src/core edits.
        mi->set_dashboard_always_ready(true);
        web_server->set_dashboard_dir("web-static");

        // D-BCH dashboard feeds (integrator 2026-08-03): wire the live BCH
        // data sources into the MiningInterface the H-STATS.944 seam already
        // stood up (it was constructed with a NULL IMiningNode + zero feeds,
        // so /api rendered empty). Reuses core/web_server.hpp generic feed
        // setters (the same LTC-parity shape) -- ZERO src/core edit. The
        // lambdas capture daemon/node by reference; both are declared at the
        // top of standup_pool_run and outlive ioc.run(), so no dangle. All
        // reads are display-only (lock-free snapshots / atomics).
        //   /api/node_topology -- BCHN embedded daemon peers + synced height.
        mi->set_node_topology_fn([&daemon]() { return daemon.dashboard_topology(); });
        //   /broadcaster_status header-sync fields -- the embedded BCH
        //   header-chain tip + single-peer startingheight (display-only; the
        //   core merge computes sync_percent/synced/connected_peers from it).
        mi->set_coin_sync_status_fn([&daemon]() { return daemon.sync_status(); });
        //   share-peers -- the pool node sharechain P2P peer snapshot.
        mi->set_peer_info_fn([&node]() { return node.get_peer_info_json(); });
        //   pool hashrate -- lock-free tracker snapshot published by think().
        mi->set_pool_hashrate_fn([&node]() { return node.get_tracker_snapshot().pool_hashrate; });
        //   sharechain stats -- chain/verified/head counts + hashrate.
        mi->set_sharechain_stats_fn([&node]() {
            auto s = node.get_tracker_snapshot();
            return nlohmann::json{
                {"chain_count", s.chain_count},
                {"verified_count", s.verified_count},
                {"head_count", s.head_count},
                {"pool_hashrate", s.pool_hashrate},
            };
        });

        // ââ Found-block verifier: confirm/orphan a won block vs the chain ââ
        // #995 BCH arm. Before this a BCH won block was recorded "pending"
        // forever and an orphan (the class that lost DASH block 2508008) surfaced
        // only to humans. Two halves, BOTH TELEMETRY-ONLY and strictly downstream
        // of the block submit -- neither gates broadcast, mint, target or payout:
        //   (a) record + arm: when BCHWorkSource dispatches a won block, record it
        //       to /recent_blocks and arm the confirm/orphan poller.
        //   (b) verdict fn: resolve confirm/orphan daemonless-first off the
        //       embedded HeaderChain (authoritative best branch), with the
        //       always-retained BCHN-RPC getblockheader confirmations as fallback.
        work_source->set_on_found_block_fn(
            [mi](uint32_t height, const uint256& block_hash,
                 const std::string& miner, bool reached_network) {
                const double pool_hr = mi->get_local_hashrate();
                uint64_t     subsidy = 0;
                auto tmpl = mi->get_current_work_template();
                if (!tmpl.is_null() && tmpl.contains("coinbasevalue"))
                    subsidy = tmpl["coinbasevalue"].get<uint64_t>();
                const std::string hash_hex = block_hash.GetHex();
                mi->record_found_block(
                    height, block_hash,
                    static_cast<uint64_t>(std::time(nullptr)),
                    "BCH", miner, hash_hex,
                    mi->get_network_difficulty(),
                    /*share_difficulty=*/0.0, pool_hr, subsidy);
                mi->schedule_block_verification(hash_hex);
                if (!reached_network)
                    LOG_WARNING << "[BCH-POOL] recorded found block height=" << height
                                << " that reached NO network sink";
            });

        mi->set_block_verify_fn(
            [mi, &daemon](const std::string& hash_hex) -> int {
                uint256 h; h.SetHex(hash_hex);
                auto& hc = daemon.chain();

                // found_height: authoritative from our own found-block record
                // (survives an orphan whose header peers never relayed to us);
                // else recovered from the embedded header chain.
                uint32_t found_height = 0;
                bool     have_height  = false;
                for (const auto& b : mi->get_found_blocks()) {
                    if (b.hash == hash_hex) {
                        found_height = static_cast<uint32_t>(b.height);
                        have_height  = true;
                        break;
                    }
                }
                if (!have_height) {
                    if (auto e = hc.get_header(h)) {
                        found_height = e->height;
                        have_height  = true;
                    }
                }

                if (have_height) {
                    auto winner_at = [&hc](uint32_t hh) -> std::optional<uint256> {
                        if (auto e = hc.get_header_by_height(hh)) return e->block_hash;
                        return std::nullopt;
                    };
                    int v = coin::block_confirm::resolve_status(
                        winner_at, hc.height(), h, found_height);
                    // Daemonless-first: trust a definite confirmed/orphaned verdict.
                    // A 0 (pending) with the header chain ALREADY past found_height
                    // is a genuine shallow-pending; only fall through to RPC when
                    // the header chain has not yet reached the height.
                    if (v != 0) return v;
                    if (hc.height() >= found_height) return 0;
                }

                // Fallback arm (header chain absent or behind): external BCHN-RPC
                // getblockheader confirmations. c < 0 => off the best chain.
                int c = daemon.rpc_block_confirmations(h);
                if (c != std::numeric_limits<int>::min()) {
                    if (c < 0) return -1;
                    if (c >= static_cast<int>(coin::block_confirm::kDefaultConfirmDepth))
                        return c;
                }
                return 0; // still pending
            });

        // graph_db stats persistence -- survives restarts (LTC-parity site 2/3;
        // mirrors main_ltc.cpp:1967-1973). BCH-namespaced sub-dir keeps the
        // per-coin stat log isolated under the shared config path.
        {
            std::string net_label = is_testnet ? "testnet" : "mainnet";
            std::string graph_db_path = (core::filesystem::config_path()
                / net_label / "bch" / "graph_db").string();
            // #1040 gap (STATS.944 restart proof, 2026-08-03): the graph_db parent
            // dir (config_path()/<net>/bch/) was never created, so save_stat_log's
            // tmp-write + rename failed every 100s and NO stats survived restart.
            // Mirror the main_btc.cpp:358 / main_dgb.cpp:196 create_directories(net_dir)
            // best-effort pattern, targeting the actual stat-log parent.
            std::error_code graph_db_mkdir_ec;
            std::filesystem::create_directories(
                std::filesystem::path(graph_db_path).parent_path(), graph_db_mkdir_ec);
            mi->set_stat_log_path(graph_db_path);
            mi->load_stat_log();
            LOG_INFO << "[BCH-POOL] graph_db stats persistence -> " << graph_db_path;
        }

        if (web_server->start()) {
            // LTC-parity site 3/3: periodic save_stat_log every 100s (matches
            // p2pool graph_db + main_ltc.cpp:7429). Self-rescheduling steady_timer
            // on the SAME ioc the run-loop drives; captured by shared_ptr so it
            // outlives each async_wait continuation.
            stats_timer = std::make_shared<boost::asio::steady_timer>(ioc);
            auto save_fn = std::make_shared<std::function<void(boost::system::error_code)>>();
            *save_fn = [stats_timer, save_fn, mi](boost::system::error_code ec) {
                if (ec) return;
                mi->save_stat_log();
                stats_timer->expires_after(std::chrono::seconds(100));
                stats_timer->async_wait(*save_fn);
            };
            stats_timer->expires_after(std::chrono::seconds(100));
            stats_timer->async_wait(*save_fn);
            LOG_INFO << "[BCH-POOL] dashboard live on http://" << http_addr << ":"
                     << http_port << " (graph_db persist every 100s).";
        } else {
            LOG_ERROR << "[BCH-POOL] WebServer FAILED to bind " << http_addr << ":"
                      << http_port << " -- dashboard disabled, run-loop continues.";
            web_server.reset();
        }
        } // if (mi != nullptr)
    } else {
        LOG_INFO << "[BCH-POOL] dashboard disabled (no --http bind given).";
    }

    // Periodic think/clean tick (every 5s, safety net) — mirrors the LTC/dash
    // tick. Without it, think() fired only on share arrival: no stale-head
    // eating, unbounded raw-tracker growth past 2*CHAIN_LENGTH+10, and a timed-
    // out bootstrap download was never retried if all peers went silent.
    // clean_tracker() runs think() inline then prunes on the compute thread under
    // the exclusive lock. `node` is a by-value local that outlives ioc.run(),
    // captured by reference. On shutdown ioc.stop() cancels the timer → the
    // handler is invoked with ec set and returns without re-arming.
    auto bch_think_timer = std::make_shared<boost::asio::steady_timer>(ioc);
    std::function<void(boost::system::error_code)> bch_think_tick;
    bch_think_tick = [&node, bch_think_timer, &bch_think_tick](boost::system::error_code ec) {
        if (ec) return;
        bch_think_timer->expires_after(std::chrono::seconds(5));
        bch_think_timer->async_wait(bch_think_tick);
        try {
            node.clean_tracker();
        } catch (const std::exception& e) {
            LOG_ERROR << "[CLEAN-TRACKER] error: " << e.what();
        } catch (...) {
            LOG_ERROR << "[CLEAN-TRACKER] unknown error";
        }
    };
    bch_think_timer->expires_after(std::chrono::seconds(5));
    bch_think_timer->async_wait(bch_think_tick);

    // Drive the shared io_context: pool node + embedded daemon + stratum run together.
    ioc.run();

    // LTC-parity site 3/3 (the TRUE third, missing until now): save the stat log
    // on clean shutdown. load-on-start (site 1) + periodic-100s (site 2) only
    // persist at tick boundaries, so without this every clean restart drops
    // whatever accumulated since the last 100s tick. Mirrors BTC #1100
    // (main_btc.cpp) / main_ltc.cpp:7456-7457 (\"Save stats on shutdown\").
    // web_server (declared above, outside the http_port block) is still alive
    // here -- the reset()/teardown happens when this function returns, after this
    // flush. mi is block-local to the standup block, so re-fetch it through the
    // still-live web_server. Precondition: GRACEFUL stop (ioc.stop() from the
    // signal handler unwinds ioc.run()); SIGKILL flushes neither lane. Display-
    // only stat log; p2pool-merged-v36 surface: NONE.
    if (web_server) {
        if (auto* mi = web_server->get_mining_interface())
            mi->save_stat_log();
    }
}

} // namespace bch