#pragma once
// V37 MRR roundabout — fixed-point arithmetic + deterministic decay tables.
// Spec: docs/c2pool-v37-mrr-roundabout-buffer.md §8.1–8.3.
//
// Consensus rules enforced here:
//   * no floating point anywhere
//   * every multiply truncates toward zero
//   * tables generated by iterated truncating integer multiplication only
//
// Range pinning (the "exact ranges to be pinned in the implementation spec"
// of §8.1): FRAC_BITS = 62, not 64. Rationale: with Q62 every table entry
// (decay <= 1.0, inverse-decay <= 2^{E/half_life} < 4.0) fits a u64, every
// w_raw (full u64 range) x table product fits native unsigned __int128, and
// accumulator sums fit U256. Q62 is 2^22 finer than V36's Q40. Flagged in
// IMPLEMENTATION-NOTES.md as an erratum against the spec's "64 fractional
// bits" wording; the spec delegates final range pinning here.

#include <array>
#include <cstdint>
#include <cstddef>
#include <stdexcept>
#include <string>
#include <vector>

namespace v37 {

using u64  = std::uint64_t;
using u128 = unsigned __int128;

static constexpr unsigned FRAC_BITS = 62;
static constexpr u64 Q_ONE = u64(1) << FRAC_BITS;            // 1.0 in Q62
static constexpr u64 LN2_MICRO = 693147;                     // V36 lineage

// ── U256: minimal unsigned 256-bit integer (4 x u64 limbs, little-endian) ──
// Only the operations the consensus path needs; all wrap-free uses are
// guarded by the Q62 range pinning above.
struct U256 {
    std::array<u64, 4> v{0, 0, 0, 0};

    constexpr U256() = default;
    constexpr U256(u64 x) : v{x, 0, 0, 0} {}
    static U256 from_u128(u128 x) {
        U256 r;
        r.v[0] = static_cast<u64>(x);
        r.v[1] = static_cast<u64>(x >> 64);
        return r;
    }
    bool is_zero() const { return !(v[0] | v[1] | v[2] | v[3]); }

    U256& operator+=(const U256& o) {
        u128 c = 0;
        for (int i = 0; i < 4; ++i) {
            u128 s = u128(v[i]) + o.v[i] + c;
            v[i] = static_cast<u64>(s);
            c = s >> 64;
        }
        return *this;  // overflow impossible under range pinning
    }
    U256& operator-=(const U256& o) {
        u128 borrow = 0;
        for (int i = 0; i < 4; ++i) {
            u128 d = u128(v[i]) - o.v[i] - borrow;
            v[i] = static_cast<u64>(d);
            borrow = (d >> 64) ? 1 : 0;
        }
        return *this;  // callers only subtract amounts previously added
    }
    friend U256 operator+(U256 a, const U256& b) { a += b; return a; }
    friend U256 operator-(U256 a, const U256& b) { a -= b; return a; }
    friend bool operator==(const U256& a, const U256& b) { return a.v == b.v; }
    friend bool operator!=(const U256& a, const U256& b) { return !(a == b); }
    friend bool operator<(const U256& a, const U256& b) {
        for (int i = 3; i >= 0; --i)
            if (a.v[i] != b.v[i]) return a.v[i] < b.v[i];
        return false;
    }

    // (this * m) >> FRAC_BITS, truncating — the Q62 scale-application step.
    // Used for: acc x decay (query), bucket scaled x epoch shift.
    U256 mul_q(u64 m) const {
        // 256 x 64 -> 320-bit intermediate held as 5 limbs, then >> 62.
        u64 r[5] = {0, 0, 0, 0, 0};
        u128 carry = 0;
        for (int i = 0; i < 4; ++i) {
            u128 p = u128(v[i]) * m + carry;
            r[i] = static_cast<u64>(p);
            carry = p >> 64;
        }
        r[4] = static_cast<u64>(carry);
        U256 out;
        constexpr unsigned s = FRAC_BITS;          // 62: cross-limb shift
        for (int i = 0; i < 4; ++i)
            out.v[i] = (r[i] >> s) | (u64(r[i + 1]) << (64 - s));
        // r[4] >> s contributes to out.v[3]'s high bits:
        // already folded via r[4] << (64-s) above when i==3.
        return out;
    }

    // General left shift (k < 256); callers guarantee no overflow.
    U256 shl(unsigned k) const {
        U256 r;
        unsigned limb = k / 64, bits = k % 64;
        for (int i = 3; i >= 0; --i) {
            u64 v_ = 0;
            int src = i - static_cast<int>(limb);
            if (src >= 0) {
                v_ = v[src] << bits;
                if (bits && src > 0) v_ |= v[src - 1] >> (64 - bits);
            }
            r.v[i] = v_;
        }
        return r;
    }

    // floor(num * 2^FRAC_BITS / den) clamped to Q_ONE — the Q62 ratio used
    // by vesting (§4.3). Deterministic: restoring binary division, truncating
    // (integer division is already part of the §8.2 consensus toolbox).
    static u64 ratio_q(const U256& num, const U256& den) {
        if (den.is_zero() || !(num < den)) return Q_ONE;
        U256 n = num.shl(FRAC_BITS);   // num < den <= 2^194 head-room safe
        u64 q = 0;
        for (int i = static_cast<int>(FRAC_BITS) - 1; i >= 0; --i) {
            U256 d = den.shl(static_cast<unsigned>(i));
            if (!(n < d)) {
                n -= d;
                q |= u64(1) << i;
            }
        }
        return q;
    }

    std::string hex() const {
        static const char* d = "0123456789abcdef";
        std::string s;
        for (int i = 3; i >= 0; --i)
            for (int j = 15; j >= 0; --j)
                s.push_back(d[(v[i] >> (j * 4)) & 0xf]);
        return s;
    }
};

// (a * b) >> FRAC_BITS for two u64 Q62 factors (both values < 4.0).
inline u64 mul_q64(u64 a, u64 b) {
    return static_cast<u64>((u128(a) * b) >> FRAC_BITS);
}

// ── Deterministic decay tables (§8.2) ─────────────────────────────────────
// All entries are generated by integer-only, iterated, truncating procedures
// anchored on LN2_MICRO — identical on every conforming platform.
struct DecayTables {
    u64 half_life = 0;
    u64 epoch_len = 0;          // E
    u64 decay_per = 0;          // lambda = 2^(-1/half_life), Q62
    u64 inv_per = 0;            // lambda^(-1), Q62 (value slightly > 1.0)

    std::vector<u64> decay;     // decay[d]   = lambda^d,    Q62, d in [0, span]
    std::vector<u64> inv_decay; // inv_decay[j] = lambda^-j, Q62, j in [0, E)
    std::vector<u64> epoch_shift; // epoch_shift[i] = lambda^(E*i), Q62

    void init(u64 half_life_, u64 epoch_len_, u64 max_depth, u64 max_epochs) {
        if (half_life_ == 0 || epoch_len_ == 0)
            throw std::invalid_argument("v37: zero decay parameter");
        half_life = half_life_;
        epoch_len = epoch_len_;

        // V36-lineage per-step factor at Q62:
        //   decay_per = 1.0 - ln2/half_life  (first-order, exactly as V36's
        //   Q40 formula, widened): Q_ONE - (Q_ONE * LN2_MICRO) / (1e6 * HL)
        decay_per = Q_ONE - static_cast<u64>(
            (u128(Q_ONE) * LN2_MICRO) / (u128(1000000) * half_life));

        // inv_per = floor(2^124 / decay_per): the Q62 reciprocal of a Q62
        // value (2^124 = Q_ONE << FRAC_BITS fits u128 exactly).
        inv_per = static_cast<u64>((u128(Q_ONE) << FRAC_BITS) / decay_per);

        decay.assign(max_depth + 1, 0);
        decay[0] = Q_ONE;
        for (u64 d = 1; d <= max_depth; ++d)
            decay[d] = mul_q64(decay[d - 1], decay_per);

        inv_decay.assign(epoch_len, 0);
        inv_decay[0] = Q_ONE;
        for (u64 j = 1; j < epoch_len; ++j) {
            inv_decay[j] = mul_q64(inv_decay[j - 1], inv_per);
            // Headroom guard: the true sequence is strictly increasing
            // (every entry >= 1.0 and inv_per > 1.0), so any non-increase
            // is a u64 wrap — the lane geometry violates the inverse-decay
            // headroom (requires lambda^-(E-1) < 4.0, i.e. roughly
            // epoch_len <= 2 * half_life). Refuse rather than corrupt.
            if (inv_decay[j] <= inv_decay[j - 1])
                throw std::invalid_argument(
                    "v37: epoch_len/half_life ratio overflows inverse-decay "
                    "headroom (need lambda^-(E-1) < 4.0)");
        }

        if (max_depth < epoch_len)
            throw std::invalid_argument("v37: decay table shorter than epoch");
        epoch_shift.assign(max_epochs + 1, 0);
        epoch_shift[0] = Q_ONE;
        for (u64 i = 1; i <= max_epochs; ++i)
            epoch_shift[i] = mul_q64(epoch_shift[i - 1], decay[epoch_len]);
    }
};

} // namespace v37
