// SPDX-License-Identifier: AGPL-3.0-or-later
//
// KAT-gated correctness tests for the M2-A cross-coin converter + address
// construct (design §4.1, requirement 5; #961 money-misdirection guard).
//
// A wrong conversion misdirects funds, so every vector is authoritative or
// independently derivable: the P2PKH/P2SH base58 and bech32/bech32m address
// strings below were generated by a from-scratch BIP173/350 + Base58Check
// reference (no c2pool code), and the P2WPKH/P2TR vectors match the published
// BIP173/BIP341 test vectors (bc1qw508d6...v8f3t4 and bc1p0xlxvl...zk5jj0).
//
// Coverage:
//   ACCEPT  LTC<->DOGE P2PKH (same hash160), BTC<->LTC P2WPKH (HRP swap),
//           BTC<->LTC/DGB P2TR (bech32m HRP swap), LTC->DASH/NMC base58 (NMC leaf).
//   REFUSE  BCH prefix-swap, DOGE-taproot (type absent), segwit->DOGE,
//           mainnet<->testnet, source-foreign, source-invalid (CashAddr as base58).
//   BCH     CashAddr<->base58 transcode helper (payload round-trip).
//   BUILD   P2SH / P2WSH / P2SH-P2WSH / P2SH-P2WPKH construct (encode).
// The #961 round-trip payload equality is asserted on EVERY accept.

#include "../Convert.hpp"
#include "../ConvertCoins.hpp"
#include "../BchTranscode.hpp"
#include "../AddressConstruct.hpp"
#include "../../hdkeys/HexUtil.hpp"

#include <cstdio>
#include <string>
#include <vector>

using namespace c2w::convert;

static int g_pass = 0, g_fail = 0;

#define CHECK(cond, msg)                                                        \
    do {                                                                        \
        if (cond) { ++g_pass; }                                                 \
        else { ++g_fail; std::printf("  FAIL: %s  (%s:%d)\n", msg, __FILE__, __LINE__); } \
    } while (0)

// Authoritative vectors (single shared hash160 / x-only payload).
static const std::string H160  = "751e76e8199196d454941c45d1b3a323f1433bd6";
static const std::string XONLY = "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798";

static const std::string LTC_P2PKH  = "LVuDpNCSSj6pQ7t9Pv6d6sUkLKoqDEVUnJ";
static const std::string DOGE_P2PKH = "DFpN6QqFfUm3gKNaxN6tNcab1FArL9cZLE";
static const std::string DASH_P2PKH = "XmN7PQYWKn5MJFna5fRYgP6mxT2F7xpekE";
static const std::string NMC_P2PKH  = "N7FdkoPbHSxKfrSVVbRu3NZtrLqc1oKpAR";
static const std::string BTC_P2WPKH = "bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4";
static const std::string LTC_P2WPKH = "ltc1qw508d6qejxtdg4y5r3zarvary0c5xw7kgmn4n9";
static const std::string BTC_P2TR   = "bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqzk5jj0";
static const std::string LTC_P2TR   = "ltc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqpj6zg2";
static const std::string DGB_P2TR   = "dgb1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqlussds";

// BCH transcode vectors (same hash160 as above).
static const std::string BCH_CASHADDR = "bitcoincash:qp63uahgrxged4z5jswyt5dn5v3lzsem6cy4spdc2h";
static const std::string BCH_LEGACY   = "1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH"; // base58 P2PKH ver 0x00

// Assert an accepted conversion: right target, and the #961 round-trip payload
// equality holds (source payload == target payload == the expected hash/program).
static void expect_accept(const char* what, const std::string& addr,
                          const char* from, const char* to,
                          const std::string& expect_target,
                          const std::string& expect_payload)
{
    auto r = convert_address(addr, from, to);
    CHECK(r.ok(), what);
    CHECK(r.target_address == expect_target, what);
    CHECK(!r.source_payload_hex.empty() &&
          r.source_payload_hex == r.target_payload_hex, "#961 round-trip payload equality");
    CHECK(r.source_payload_hex == expect_payload, "payload matches authoritative hash");
}

static void expect_refuse(const char* what, const std::string& addr,
                          const char* from, const char* to, Status expect)
{
    auto r = convert_address(addr, from, to);
    CHECK(!r.ok() && r.status == expect, what);
}

int main()
{
    std::printf("== c2wallet-qt M2-A convert + construct KATs ==\n");

    // ---- ACCEPT: LTC <-> DOGE P2PKH (same hash160), both directions ----
    expect_accept("LTC->DOGE P2PKH", LTC_P2PKH, "LTC", "DOGE", DOGE_P2PKH, H160);
    expect_accept("DOGE->LTC P2PKH", DOGE_P2PKH, "DOGE", "LTC", LTC_P2PKH, H160);

    // ---- ACCEPT: BTC <-> LTC P2WPKH (bech32 HRP swap) ----
    expect_accept("BTC->LTC P2WPKH", BTC_P2WPKH, "BTC", "LTC", LTC_P2WPKH, H160);
    expect_accept("LTC->BTC P2WPKH", LTC_P2WPKH, "LTC", "BTC", BTC_P2WPKH, H160);

    // ---- ACCEPT: BTC -> LTC / DGB P2TR (bech32m HRP swap) ----
    expect_accept("BTC->LTC P2TR", BTC_P2TR, "BTC", "LTC", LTC_P2TR, XONLY);
    expect_accept("BTC->DGB P2TR", BTC_P2TR, "BTC", "DGB", DGB_P2TR, XONLY);

    // ---- ACCEPT: base58 spread exercising the NMC leaf + DASH ----
    expect_accept("LTC->NMC P2PKH (NMC leaf)", LTC_P2PKH, "LTC", "NMC", NMC_P2PKH, H160);
    expect_accept("LTC->DASH P2PKH", LTC_P2PKH, "LTC", "DASH", DASH_P2PKH, H160);

    // ---- REFUSE (the #961 guard) ----
    // (a) BCH is never a prefix swap.
    expect_refuse("BCH prefix-swap refused (target)", BTC_P2WPKH, "BTC", "BCH",
                  Status::RefuseBchNoPrefixSwap);
    expect_refuse("BCH prefix-swap refused (source)", BCH_CASHADDR, "BCH", "BTC",
                  Status::RefuseBchNoPrefixSwap);
    // (b) type absent on target — taproot -> DOGE, and segwit -> DOGE.
    expect_refuse("DOGE-taproot refused (type absent)", BTC_P2TR, "BTC", "DOGE",
                  Status::RefuseTypeAbsentOnTarget);
    expect_refuse("DOGE-segwit refused (type absent)", BTC_P2WPKH, "BTC", "DOGE",
                  Status::RefuseTypeAbsentOnTarget);
    // (c) mainnet <-> testnet.
    expect_refuse("mainnet<->testnet refused", LTC_P2PKH, "LTC", "BTC-t",
                  Status::RefuseNetworkMismatch);
    // (d) source foreign / invalid.
    expect_refuse("source-foreign refused", DOGE_P2PKH, "BTC", "LTC",
                  Status::RefuseSourceForeign);
    expect_refuse("source-invalid (CashAddr as base58) refused", BCH_CASHADDR, "BTC", "LTC",
                  Status::RefuseSourceInvalid);

    // ---- BCH CashAddr <-> base58 transcode helper (payload round-trip) ----
    {
        const auto* btc = convert_coin("BTC");
        const auto* bch = convert_coin("BCH");
        auto a = bch_cashaddr_to_base58(BCH_CASHADDR, *btc);
        CHECK(a.ok, "BCH CashAddr -> base58 transcode");
        CHECK(a.target_address == BCH_LEGACY, "BCH->base58 target matches");
        CHECK(a.payload_hex == H160, "BCH->base58 payload matches");

        auto b = base58_to_bch_cashaddr(BCH_LEGACY, *btc, *bch);
        CHECK(b.ok, "base58 -> BCH CashAddr transcode");
        CHECK(b.target_address == BCH_CASHADDR, "base58->BCH target matches");
        CHECK(b.payload_hex == H160, "base58->BCH payload matches");
    }

    // ---- Address CONSTRUCT (encode) for script-defined types ----
    {
        auto redeem = c2w::hdkeys::from_hex(
            "51210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179851ae");
        CHECK(redeem.has_value(), "redeemScript hex parses");
        auto rs = *redeem;

        auto p2sh = c2w::construct::build_p2sh(0x05, rs);
        CHECK(p2sh.ok() && p2sh.address == "3DicS6C8JZm59RsrgXr56iVHzYdQngiehV", "build P2SH");

        auto p2wsh = c2w::construct::build_p2wsh("bc", rs);
        CHECK(p2wsh.ok() &&
              p2wsh.address == "bc1q9qs9xv7mjghkd69fgx62xttxmeww5q7eekjxu0nxtzf4yu4ekf8s4plngs",
              "build P2WSH");

        auto nested = c2w::construct::build_p2sh_p2wsh(0x05, rs);
        CHECK(nested.ok() && nested.address == "344YToRR99ER5CRo975kXTUAnYcBrVxQYm", "build P2SH-P2WSH");

        auto pk = c2w::hdkeys::from_hex(
            "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798");
        auto p2shwpkh = c2w::construct::build_p2sh_p2wpkh(0x05, *pk);
        CHECK(p2shwpkh.ok() && p2shwpkh.address == "3JvL6Ymt8MVWiCNHC7oWU6nLeHNJKLZGLN",
              "build P2SH-P2WPKH");

        // The bare-multisig helper reproduces the redeemScript above.
        auto ms = c2w::construct::build_bare_multisig_script(1, {*pk});
        CHECK(c2w::hdkeys::to_hex(ms) == c2w::hdkeys::to_hex(rs), "build bare 1-of-1 multisig script");
    }

    std::printf("\n== M2-A KATs: %d passed, %d failed ==\n", g_pass, g_fail);
    return g_fail == 0 ? 0 : 1;
}
