#pragma once

#include <filesystem>
#include <string>

namespace core {

/// Cookie-based authentication for the c2pool HTTP API.
///
/// Follows the bitcoind/.cookie pattern:
/// - On daemon startup: generate random 32-byte hex token, write to <datadir>/.cookie
/// - File permissions: 0600 (owner-only read/write)
/// - Qt client on same machine reads the cookie file automatically
/// - Remote clients must be given the token out-of-band (e.g. SSH)
/// - On daemon shutdown: delete the cookie file
class CookieAuth {
public:
    static constexpr const char* kCookieFilename = ".cookie";

    /// Generate a random auth cookie and write it to datadir/.cookie.
    /// Returns the generated token string.
    /// Sets file permissions to 0600 on POSIX systems.
    static std::string generate(const std::filesystem::path& datadir);

    /// Read the cookie token from datadir/.cookie.
    /// Returns empty string if file doesn't exist or can't be read.
    static std::string read(const std::filesystem::path& datadir);

    /// Delete the cookie file (call on daemon shutdown).
    static void cleanup(const std::filesystem::path& datadir);

    /// Validate a token against the active cookie.
    /// Returns true if token matches the cookie generated by this process.
    static bool validate(const std::string& token);

    /// Get the active cookie for this process (empty if not generated yet).
    static const std::string& active_cookie();

private:
    static std::string s_active_cookie;
};

} // namespace core
