#SET(HUNTER_ROOT ${CMAKE_CURRENT_BINARY_DIR}/hunter)
#set(HUNTER_GATE_ROOT ${CMAKE_CURRENT_BINARY_DIR})
#message("HUNTER_ROOT = ${HUNTER_ROOT}")
#message("BINARY DIR = ${CMAKE_CURRENT_BINARY_DIR}")

include(${CMAKE_CURRENT_LIST_DIR}/HunterGate.cmake)