#!/usr/bin/env bash
# HiveOS custom miner manifest for c2pool
# https://github.com/frstrtr/c2pool

MINER_NAME=c2pool
MINER_LOG_BASENAME=/var/log/miner/c2pool/c2pool
MINER_API_PORT=8080
MINER_LATEST_VER=1.0.0
