// SPDX-License-Identifier: AGPL-3.0-or-later
#pragma once

/// DNS seed hostnames and hardcoded fallback IPs for the DigiByte P2P network
/// (embedded coin daemon peer discovery — NOT the c2pool sharechain, which
/// uses PoolConfig::P2P_PORT 5024). DigiByte network default ports: mainnet
/// 12024, testnet 12026.
///
/// Sources (DigiByte Core v8.22.2, github.com/DigiByte-Core/digibyte):
///   - DNS seeds:   src/chainparams.cpp  (CMainParams / CTestNetParams vSeeds)
///   - fixed seeds: contrib/seeds/nodes_main.txt + nodes_test.txt
/// Refresh: re-harvest from the same upstream files on each DigiByte Core
/// version bump (they are regenerated by contrib/seeds/makeseeds.py against
/// Pieters DNS crawler); keep the fixed list a representative sample, DNS
/// seeds are the primary discovery path.

#include <core/dns_seeder.hpp>
#include <core/netaddress.hpp>
#include <vector>

namespace dgb {
namespace coin {

/// DNS seeds for DigiByte mainnet (port 12024).
inline std::vector<c2pool::dns::DnsSeed> dgb_mainnet_dns_seeds()
{
    return {
        {"seed.digibyte.io",              12024},
        {"seed.diginode.tools",           12024},
        {"seed.digibyteblockchain.org",   12024},
        {"eu.digibyteseed.com",           12024},
        {"seed.digibyte.link",            12024},
        {"seed.quakeguy.com",             12024},
        {"seed.aroundtheblock.app",       12024},
        {"seed.digibyte.services",        12024},
    };
}

/// DNS seeds for DigiByte testnet (port 12026).
inline std::vector<c2pool::dns::DnsSeed> dgb_testnet_dns_seeds()
{
    return {
        {"testnetseed.diginode.tools",        12026},
        {"testseed.digibyteblockchain.org",   12026},
        {"testnet.digibyteseed.com",          12026},
        {"testnetseed.digibyte.link",         12026},
        {"testnetseed.digibyte.services",     12026},
    };
}

/// Hardcoded fallback peers for DigiByte mainnet (port 12024).
/// Used only if DNS seeds fail. Representative sample of contrib/seeds/nodes_main.txt.
inline std::vector<NetService> dgb_mainnet_fixed_seeds()
{
    return {
        {"65.21.137.242",   12024},
        {"51.89.40.32",     12024},
        {"173.212.197.63",  12024},
        {"75.119.133.163",  12024},
        {"64.227.97.247",   12024},
        {"172.105.162.72",  12024},
        {"5.9.193.21",      12024},
        {"157.230.194.126", 12024},
        {"168.119.147.118", 12024},
        {"136.144.215.219", 12024},
    };
}

/// Hardcoded fallback peers for DigiByte testnet (port 12026).
inline std::vector<NetService> dgb_testnet_fixed_seeds()
{
    return {
        {"198.58.124.101",  12026},
        {"157.245.63.215",  12026},
        {"37.59.20.42",     12026},
        {"217.72.6.241",    12026},
    };
}

/// Get DNS seeds for the appropriate DGB network.
inline std::vector<c2pool::dns::DnsSeed> dgb_dns_seeds(bool testnet)
{
    return testnet ? dgb_testnet_dns_seeds() : dgb_mainnet_dns_seeds();
}

/// Get fixed fallback seeds for the appropriate DGB network.
inline std::vector<NetService> dgb_fixed_seeds(bool testnet)
{
    return testnet ? dgb_testnet_fixed_seeds() : dgb_mainnet_fixed_seeds();
}

} // namespace coin
} // namespace dgb
